### ISSUE TITLE
Div non chiusi in Episodio RR

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#10]
## Descrizione
Nella pagina dell'[Episodio RR](https://wiki.pokemoncentral.it/Episodio_RR) non sono stati chiusi alcuni div nella sezione "Lotte principali", infatti il box in fondo con le categorie ha dei problemi.

## Risoluzione del problema
C'è da capire dove manca la chiusura dei div. Voglio sperare che non sia il modulo a dare problemi ma non credo perché nelle altre pagine sembra andare tutto bene.

**Comment by lucas992x** [comment]
@Cruifer Questa pagina contiene 12 `</div>` ma non viene aperto nessun `<div>`. Ho provato a toglierli, ma l'anteprima mi mostra ancora il box categorie sminchiato esattamente come adesso.

**Comment by Cruifer** [comment]
penso che i div vengano aperti nel modulo Party quando viene chiamato così: `{{#invoke: Party | Div|color=bianco light}}` ma non posso investigare molto perché sono da cell

**Comment by flavio-a** [comment]
In realtà tipo tutte le chiamate del modulo party lasciano dei div non chiusi, la chiamata ``{{#invoke: Party | Tag | ... }}`` ne lascia addirittura due, ma questi sono dettagli. Ho sistemato.
