### ISSUE TITLE
Problemi overflow-auto

### ISSUE THREAD

**Issue by CiaobyDany** [pokemoncentral/wiki-project#11]
## Descrizione
L'overflow-auto a quanto ho capito è una cosa che è potenzialmente molto utile ma che con MediaWiki fa più danni che altro. Credo che sia doveroso avere un punto di riferimento in cui segnalare tutti gli errori in proposito e/o spiegare come risolverli autonomamente.

## Screenshot
![immagine](https://user-images.githubusercontent.com/38566659/39299805-ecca8ed8-4949-11e8-91a9-597b9e4808b9.png)

## Pagine affette
* https://wiki.pokemoncentral.it/Home

## Risoluzione del problema
Immagino che basti dare degli attributi differenti a mano, ma non sono sicuro

PS: prima issue che apro, mi auguro di non aver fatto casini

**Comment by davla** [comment]
Hai assegnato a me, nel senso che devo spiegare?
Mica so come funziano le cose, ma ho fatto una classe dal nome difficile da ricordare (`.overflow-auto`). Provate a metterla un po' in giro sui contenitori delle cose e vedere se risolve i problemi.
Non è che non ho voglia di spiegarvi o la cosa è troppo tecnica, è esattamente quello che farei io.

**Comment by Cruifer** [comment]
@lucas992 la pagina è [Tea & Teo](https://wiki.pokemoncentral.it/Tea_%26_Teo), dovrebbe bastare mettere la class `overflow-auto` al [Template:TrainerPoké](https://wiki.pokemoncentral.it/Template:TrainerPok%C3%A9).

![immagine](https://user-images.githubusercontent.com/38588039/45032969-6e0e3880-b053-11e8-8613-048c3cc31b2b.png)

**Comment by Cruifer** [comment]
@lucas992 

![99deb7e6-a8cc-4cdb-97a5-3a7a6dba744e](https://user-images.githubusercontent.com/38588039/45240622-944d0600-b2e9-11e8-83b6-b884d61cd74d.jpeg)

**Comment by lucas992x** [comment]
Fixato, tra un po' potrei iniziare a metterlo ovunque a caso :D

**Comment by Cruifer** [comment]
![schermata 2018-09-09 alle 14 29 11](https://user-images.githubusercontent.com/38588039/45264443-cc189280-b43c-11e8-86ff-e27bfc6f4349.png)

>tra un po' potrei iniziare a metterlo ovunque a caso

Spoiler: no. Mettiamolo solo se serve altrimenti si fanno danni (lo so che stavi scherzando ma vabbè)

**Comment by davla** [comment]
Nessuno se la caga più. E le issues vanno chiuse, altrimenti non hanno senso.
