### ISSUE TITLE
Aggiungere una class text-center-xs

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#12]
## Descrizione
In alcuni template servirebbe una class text-center-xs che allinei il testo al centro solo su mobile. Questo perché le scritte sono allineate a destra per via della verione desktop, quindi una classe del genere servirebbe per migliorare l'estetica e rendere coerente l'allineamento delle scritte. 

## Screenshot
![screenshot_20180426-212103](https://user-images.githubusercontent.com/38588039/39327467-6655b928-4998-11e8-89b6-986d1e1a0dcd.png)

**Comment by davla** [comment]
Sono tutti d'accordo? @pokemoncentral/wiki (Ma 'sta cosa funzia davvero?)

**Comment by Cruifer** [comment]
Che possa funzionare o meno io non ne ho idea (ma non vedo perché non dovrebbe). Comunque mi sembra l'avessi proposto tu sul gruppo (o era qualcun altro? boh)

**Comment by davla** [comment]
'sta cosa è il @pokemoncentral/wiki. Il CSS funzia tranquillamente.

**Comment by flavio-a** [comment]
Credo avessimo deciso che le etichette a destra andavano bene, considerando anche la possibilità del ``text-center-xs``. Poi ovviamente possiamo cambiare idea, però sono quasi sicuro fosse stata una scelta consapevole all'epoca.

**Comment by Cruifer** [comment]
In realtà no. Giuro, ho controllato nella chat, è che non avevamo sbatti di implementare una soluzione (vai all'1 settembre se non ti fidi). E poi dai, a meno che uno non sia strabico non vedo come possa leggerlo bene, è scomodo.

**Comment by flavio-a** [comment]
Allora a me va benissimo aggiungerla. Lo faccio anche subito, se va bene.

**Comment by davla** [comment]
Non fare il pidocchioso e metti tutti gli allineamenti. Sono ben 15 classi di una riga ciascuna in più, il peso del CSS non ne risentirà.
