### ISSUE TITLE
Embed della Twitter TimeLine glitchatissimo

### ISSUE THREAD

**Issue by davla** [pokemoncentral/wiki-project#14]
## Descrizione
il box twitter è glitchatissimo, almeno su desktop, a ogni hover/scroll si scazza il layout

## Pagine affette
* https://wiki.pokemoncentral.it/Utente:CiaobyDany/Newhome
* https://wiki.pokemoncentral.it/Home

## Risoluzione del problema
Sembrerebbe qualcosa di risolvibile con un `z-index` negativo, o all'`iframe` del'embed o al suo wrapper immediato (quello con `position: relative`), o a entrambe

**Comment by mexicat** [comment]
Dato che non riesco a riprodurre il problema (ogni tanto va, ogni tanto no), e dato che sembra essere  specifico di Chrome su Mac, direi che possiamo ignorarlo per il momento e almeno finché non capita anche a qualcun altro oltre a me.
