### ISSUE TITLE
Versione mobile del tt

### ISSUE THREAD

**Issue by flavio-a** [pokemoncentral/wiki-project#20]
## Descrizione
Il template tt non funziona da mobile, quindi tutte le informazioni che veicola sono irraggiungibili per gli utenti mobili.

## Pagine affette
* https://wiki.pokemoncentral.it/Template:tt e tutte quelle che lo includono

## Risoluzione del problema
Si accettano altre proposte, tra quelle già uscite la più accreditata è quella di usare un popup che si apre premendo sul testo del tt.

- [x] Capire come implementare i popup (estensione di mw da installar? Custom js? O qualcosa di diverso dai popup?)
- [x] Implementare la soluzione scelta sul server/js/altro
- [x] Aggiornare il tt di conseguenza

## Commenti personali
Delle altre soluzioni l'unica che ricordo era qualcosa tipo i references, con un numerino in alto e un elenco in fondo alla sezione. Devo dire però che non mi piace tanto perché consultare i tt in questo modo mi sembra scomodo, quindi resto dell'idea che i popup siano la soluzione migliore proposta fin'ora. Se qualcuno ha altre idee però ben vengano.

**Comment by mexicat** [comment]
Un javascript che mostra un tooltip al tocco?

**Comment by flavio-a** [comment]
Sembra una buona idea, molto simile a quella su desktop. Il tooltip resterebbe fino ad un successivo tocco o per un tempo fissato? (mi sembra più ragionevole la prima, se possibile)

**Comment by mexicat** [comment]
Direi la prima: se si clicca su un `tt` appare il tooltip, se si clicca su qualsiasi punto della pagina scompare.

**Comment by davla** [comment]
A me piaceva questa: https://www.mediawiki.org/wiki/Extension:SimpleTooltip.
È basata su Tooltipster, che è un plugin Javascript che so funzionare molto bene.
L'unica è che attualmente viene solo mantenuta, non aggiungono nuove features da tipo tre anni.

**Comment by mexicat** [comment]
Propongo https://github.com/chrisdavies/tlite - pesa poco, possiamo metterlo direttamente nel `Common.js` (sono 130 righe di js, più un po' di css). Poi bisognerà un attimo capire come invocarlo manualmente (su mobile) o in hover (su desktop).

**Comment by flavio-a** [comment]
Maze faceva notare che con un tooltip che supporta contenuto html potremmo risolvere il problema del Movelist/breed: per esempio [in questa pagina](https://m.wiki.pokemoncentral.it/Baldeali_(mossa)#Tramite_Accoppiamento) si può notare come le colonne dei genitori occupino molto spazio da mobile (e non è una delle più grosse). Si può invece pensare una soluzione à la Bulba ([esempio](https://bulbapedia.bulbagarden.net/wiki/Brave_Bird_(move)#By_breeding)) con un semplice segno (più sfondo colorato) per le generazioni in cui un Pokémon può imparare la mossa, ed aggiungere un tooltip che contiene tutti i genitori.
Il tooltip a mio parere è superiore al box collassato per due motivi: primo nasconderebbe i genitori anche da mobile; secondo far sparire il tooltip una volta trovare le informazioni interessanti è più comodo che collassare nuovamente il box, sia da mobile che da desktop.

**Comment by mexicat** [comment]
Più che altro un elenco di sprite secondo me non è molto utilizzabile, anche dentro un tooltip. Forse sarebbe meglio un elenco di nomi. E se vogliamo html arbitrario, serve qualcosa di più complesso che includa anche del codice di posizionamento smart (vedi [Popper](https://popper.js.org/) - SFW) perché sennò c'è il rischio che il popup esca fuori dallo schermo o deformi il viewport della pagina.

Tra l'altro pensavo che in realtà abbiamo già l'estensione [Popups](https://www.mediawiki.org/wiki/Extension:Popups) attivata. Forse si riesce a riciclare il JS in qualche modo, così ci sono zero dipendenze in più e anche come stile siamo più coerenti.

**Comment by flavio-a** [comment]
Mi sembra difficile riuscire ad usare l'estensione Popups  perché ho guardato un po' ma il codice crea il popup a partire praticamente solo dal titolo della pagina chiedendo al server i dati, non c'è una funzione più interna che lo genera partendo dal contenuto. Poi forse riusciamo a riciclare un po' del css, ma se dobbiamo riscrivere il js tanto vale usare una libreria esterna imo.

**Comment by flavio-a** [comment]
Ho provato a guardare un po' l'estensione linkata da Gika (https://github.com/chrisdavies/tlite) e penso che possa andare per noi. Solo non mi pare aver visto un modo integrato di far sparire il popup apparso con il tocco semplicemente toccando da un'altra parte delle schermo, ma credo che questo problema si possa risolvere.

**Comment by davla** [comment]
Bisogna decidere sul mettere o meno HTML nei tooltip. Con [questa](https://github.com/chrisdavies/tlite) non si può fare.

**Comment by lucas992x** [comment]
@davla [Commento da semplice utente, non ho idea di come effettivamente sia la cosa a livello tecnico]

Secondo me un popup contenente i soli sprite non sarebbe male; in alternativa vedrei bene una lista sprite + nome; in ogni caso gli sprite li trovo utilissimi in una lista del genere.
Altra domanda. Nel caso di mosse con tanti possibili genitori, verrebbe un popup con le dimensioni della pagina (o poco meno) in cui si possa scorrere o un popup più grande che occupa uno spazio maggiore? Non so se mi spiego.

**Comment by flavio-a** [comment]
@lucas992 Nomi più sprite temo possa diventare troppo lunga. Inoltre considerando l'altezza del peggiore dei casi (ovvero metà dell'altezza dello schermo) temo che il tooltip andrebbe a sforare spesso fuori dallo schermo, con conseguente difficoltà di lettura (scorrere con il tooltip aperto lo fa sparire, no? E in ogni caso mi sembra poco naturale). Io per quello preferirei una cosa più invasiva, tipo un vero popup stile quelli della pubblicità che si aprono a centro pagina e oscurano tutto quello che c'è dietro.
In breve la mia posizione è di limitare il contenuto dei tooltip a solo testo (come viene usato attualmente il tt), mentre un'eventuale soluzione con popup per il movelist/breed può essere cercata ed implementata in un altro momento (oppure si può pensare a qualcosa di diverso).

**Comment by flavio-a** [comment]
@lucas992 per rispondere alla tua domanda (scusa se non l'ho fatto con il precedente messaggio ma ero un po' impegnato e ho risposto di fretta): un tooltip più grande dello schermo non credo sia utilizzabile (come ho già scritto prima), quindi dovremmo in ogni caso cercare di farlo "scorribile" (tipo le tabelle di Mediawiki su mobile, per intenderci), ammesso che ci si riesca (penso di sì).
PS: tu con popup intendevi tooltip (o comunque una cosa in quello stile), giusto?

**Comment by lucas992x** [comment]
@flavio-a Sì, mi riferisco a un tooltip, non sapevo il nome

**Comment by lucas992x** [comment]
A me piacerebbe una cosa che da desktop funzioni sia come hover che come tooltip manuale. Nel senso, che mostri il contenuto nascosto passandoci il mouse ma che in caso di click lo lasci lì anche spostando il puntatore o cliccando altrove, finché non lo si nasconde di nuovo a mano cliccandoci su. Mi farebbe comodo ad esempio per confrontare due cose diverse lasciandole entrambe sempre visibili, come i Movelist/breed.

**Comment by davla** [comment]
Sì, dovrebbe essere fattibile, a meno che @mexicat non voglia un'estensione super mega lightweight.
