### ISSUE TITLE
Testo "abbassato" in molte pagine contenenti EpisodeInfobox

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#23]
## Descrizione
In alcune pagine che contengono EpisodeInfobox, il testo ad inizio pagina viene abbassato invece di stare in cima. Pensavo che dipendesse semplicemente dal fatto di andare a capo una volta in più, ma due cose mi fanno pensare che il problema sia dovuto ad altro: il fatto che questo problema capiti solo con EpisodeInfobox, e il fatto che non tutte le pagine che lo contengono abbiano questo problema.

## Pagine affette
https://wiki.pokemoncentral.it/Template:EpisodeInfobox template incriminato
Da un rapido controllo sembra che quasi tutte le pagine contenenti EpisodeInfobox abbiano questo problema, mentre siano immuni tutti gli altri Infobox e anche alcune pagine contenenti questo Infobox. Di seguito alcuni esempi con relativo screenshot di pagina e pezzo di codice.

https://wiki.pokemoncentral.it/SM036 qui c'è lo spazio e si presenta il problema
https://wiki.pokemoncentral.it/SM037 qui c'è lo spazio ma non si presenta il problema
https://wiki.pokemoncentral.it/SM047 qui non c'è lo spazio e quindi non si presenta il problema
![issue](https://user-images.githubusercontent.com/38510975/40687352-a255f64c-639a-11e8-80df-174c9a066755.png)

## Risoluzione del problema
Sinceramente non ho idea di quale possa essere la causa. Ho provato a impostare margin e padding identici ad altri template e persino a sostituire tutta la prima riga con quella di un template "funzionante", ma senza successo. Anche togliere il template poco sopra (EpicodePrevNext) dalla pagina non risolve. A sto punto penso sia un bug di qualcosa di esterno alle mie possibilità.

**Comment by Cruifer** [comment]
[Fixed](https://wiki.pokemoncentral.it/index.php?title=Template:EpisodeInfobox&curid=38295&diff=587679&oldid=586352). Buon divertimento nel vedere l'edit.
