### ISSUE TITLE
Implementare il Modulo:Stats

### ISSUE THREAD

**Issue by flavio-a** [pokemoncentral/wiki-project#25]
## Descrizione
Finire il modulo:Stats e sostituirlo al template:Stats.

## Risoluzione del problema
Dato che dovrebbe essere quasi pronto, credo si tratti solo di fare un po' di debug sul modulo e poi caricarlo.

- [x] Debuggare il modulo
- [x] Sostituirlo nelle pagine al template:Stats

**Comment by flavio-a** [comment]
Il bot ha fatto buona parte del lavoro di sostituzione, ma visto che faccio sempre le cose molto safe sono rimaste un po' di pagine su cui, nel dubbio, il bot non ha agito. Naturalmente sono una persona saggia, quindi ho loggato (in modo un po' di merda, ma comunque l'ho fatto) le pagine non corrette.
La domanda è: c'è un volontario per prendersi l'elenco e sostituire a mano il template con il modulo? Magari anche solo darmi una mano non sarebbe male, ecco.

PS: la parte che non vi ho detto è quante sono le pagine rimaste ^^'

**Comment by Cruifer** [comment]
A questo punto ho paura a chiedertelo... ma vabbè volendo posso dare una mano

**Comment by flavio-a** [comment]
Le stime dicevano sui 115, in realtà si sono rivelati essere 85. Però ero stato troppo pessimista, in un'oretta di lavoro li ho sistemati tutti io. Chiudo.

**Comment by Cruifer** [comment]
Anche questo andrebbe implementato per i Pokémon glitch.

**Comment by flavio-a** [comment]
Causa un bug, fino a 1 minuto fa non si potevano passare gli speciali al modulo, ma ora è tutto a posto. Lo "svantaggio" se volete è che non c'è un modulo dati per le statistiche, quindi la chiamata non può essere con un semplice "BASEPAGENAME" ma deve contenere tutte le statistiche (esempio: https://wiki.pokemoncentral.it/Missingno.)
Personalmente non farei un modulo dati per questo visto che non credo verranno usate da qualche altra parte oltre che nelle pagine stesse dei glitch.
Adesso vedo se riesco a sostituire nelle pagine con il bot, se non ci riesco scriverò alla ricerca di uno ~~schiavo~~ volontario.

**Comment by flavio-a** [comment]
Ok, sostituzione fatta con il bot (o mano dove serviva). Chiudo.
