### ISSUE TITLE
Nuovo layout per il template mosse improvvisate

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#26]
## Descrizione
Il Template:Mosse improvvisate è decisamente da rifare. Il layout attuale è poco pratico e si vede male da mobile. Per cominciare bisognerebbe spezzare il template in almeno due sottotemplate (header ed entry) per poterci mettere quante mosse si vuole (non so perché non ci avessi pensato quando avevo fatto il template, ma vabbé). Poi andrebbe ripensato il layout, appunto: da desktop va abbastanza bene, ma è comunque migliorabile, mentre da mobile no. Quindi andrebbe anche reso responsive, ma con le nuove class di dedalo non dovrebbe essere troppo complicato (spero). Il problema è che io non ho alcuna idea di come risistemarlo, quindi si accettano suggerimenti.

Ah,  e c'è anche da sistemare le mosse per Franky, ma per quello ho già un'idea.

## Pagine affette
* [Template:Mosse improvvisate](https://wiki.pokemoncentral.it/Template:Mosse_improvvisate)
* [Template:Mosse Z](https://wiki.pokemoncentral.it/Template:Mosse_Z) (analogo all'altro)

**Comment by lucas992x** [comment]
Ora che l'altro template è finito e caricato, sto provando a pensare qualcosa per questo qui. Innanzitutto, vedo che al momento è una tabella che ripete 20 volte lo stesso "pezzo", quindi mi chiedo se valga la pena di spezzare in due parti, un header e un entry. Cioè, tecnicamente è fattibilissimo, il problema sarebbe poi aggiornare tutte le pagine già esistenti.
Se decidessimo di seguire questa strada, forse converrebbe creare un nuovo template e pian piano sostituire nelle pagine, in modo da non rompere i contenuti già presenti. Con le Mosse Z sarebbe relativamente semplice visto che è contenuto solo in una decina di pagine e 1-2 volte per ciascuna, per le altre invece sarebbe più laborioso.

**Comment by flavio-a** [comment]
Di quante pagine stiamo parlando?

**Comment by lucas992x** [comment]
@flavio-a Per le mosse Z una decina, le improvvisate una trentina

**Comment by lucas992x** [comment]
Ho creato al volo una proposta, sempre nelle stesse pagine e sottopagine di prima:
https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate
https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate/AltreProveTemplate
https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate/AltreProveTemplate2

**Comment by CiaobyDany** [comment]
@lucas992 Non so, l'immagine sotto non mi convince molto, di solito sta sopra/sinistra, no? Cioè, che stia a destra non mi crea problemi, ovviamente, solo che lasciarla sopra stando a destra è un puttanaio

**Comment by lucas992x** [comment]
Ho provato a spostare a sinistra e sopra, e devo dire che non mi dispiace.

**Comment by CiaobyDany** [comment]
@lucas992 #Danittatura wins again

**Comment by lucas992x** [comment]
Breve riassunto di ciò che si è detto in chat per quanto riguarda il template delle mosse Z.
- Va bene l'etichetta "Debutto" o è meglio "Primo utilizzo"? Io preferisco la seconda.
- L'immagine sta meglio a sinistra e sopra o a destra e sotto? Io preferisco la seconda ma non mi dispiace neanche la prima.

**Comment by lucas992x** [comment]
Sempre qui https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate ho messo una possibilità per le mosse improvvisate, ovviamente non ho ripreso pari pari quello precedente cambiando giusto 2-3 parametri.
