### ISSUE TITLE
Spostare Minior meteora e un nucleo da UselessForms/data ad AltForms/data

### ISSUE THREAD

**Issue by flavio-a** [pokemoncentral/wiki-project#28]
## Descrizione
Adesso tutte le forme di Minior sono useless, però cambiano le statistiche da nucleo a meteora. La mia proposta è di spostare la forma meteora e uno dei nuclei (scelto arbitrariamente) nel modulo AltForms/data e vedere se il merge delle due tabelle quando serve (tipo per la sottopagina dei modelli) viene sensato.

## Pagine affette
* https://wiki.pokemoncentral.it/Modulo:Stats nella pagina di Minior non funziona bene perché mostra solo le statistiche della forma nucleo.

## Risoluzione del problema
Come proposto sopra, io separerei le forme di Minior tra useless e altforms. Sto pensando alle controindicazioni (oltre ad incasinare il merge dei due moduli dati).

@davla cosa ne pensi?

**Comment by davla** [comment]
Ho paura

**Comment by flavio-a** [comment]
Vuoi la verità? Anch'io. Ma di fatto meteora e nucleo sono due forme alternative non useless. Il problema è che poi ci sono un sacco di nuclei useless. Hai altre idee per gestire questa cosa (oltre che a mano in tutti moduli in cui serve -> no)?
Alla fine con Pikachu sembra funzionare abbastanza bene...

**Comment by flavio-a** [comment]
Non so perché io non abbia chiuso quest'issue con  pokemoncentral/wiki-lua-modules@14454c6a0db7434bc2875470b8450104180bed1b (nonostante sia meraviglioso farlo). Comunque FYI ho aggiunto un modulo dati apposta (BothForms-data) per gestire i Pokémon che hanno sia AltForms che UselessForms. E ve lo dico lo stesso anche se a molti di voi non fregherà un cazzo.
