### ISSUE TITLE
Redesign della gallery

### ISSUE THREAD

**Issue by CiaobyDany** [pokemoncentral/wiki-project#29]
## Descrizione
Avendo notato che c'è un leggero overflow da mobile è comunque emerso che la gallery necessita di un deciso restyling

## Pagine affette
Tutte quelle che usano le gallery, un esempio: https://wiki.pokemoncentral.it/Pok%C3%A9mon:_Let%27s_Go,_Pikachu!_e_Let%27s_Go,_Eevee!

## Risoluzione del problema
Direi che non è qualcosa di urgente, e che potremmo lasciare un layout simile a quello attuale, magari facendo semplicemente lo sfondo bianco dell'immagine e un gradiente light to normale pcwiki del background. Tuttavia noto che in www.wikidex.net sono riusciti a fare i box che hanno altezze diverse per le didascalie, e sarebbe il caso di implementarlo anche da noi se possibile, perché risolveremmo diversi problemi.

**Comment by davla** [comment]
@CiaobyDany Please, linka una gallery di Wikidex

**Comment by CiaobyDany** [comment]
@davla https://www.wikidex.net/wiki/Ruta_1_(Alola)
NB: NON voglio copiare tutto il layout (implementare le ombreggiature, per quanto fighe, richiederebbe una nuova revisione di tutta la grafica del sito e non mi sembra il caso al momento), solo l'altezza variabile in base al contenuto. Sostanzialmente mi paiono più simili a dei thumb nostri che a delle gallery vere e proprie.

**Comment by davla** [comment]
Visto che mi si fa notare. rispondo.

Non ho capito una mazza.

Cioè, uguale a come è ora solo con altezza variabile?

**Comment by CiaobyDany** [comment]
> potremmo lasciare un layout simile a quello attuale, magari facendo semplicemente lo sfondo bianco dell'immagine e un gradiente light to normale pcwiki del background

**Comment by davla** [comment]
Quindi è come è ora?

**Comment by CiaobyDany** [comment]
@davla No! Devi mettere lo sfondo bianco all'immagine anziché quel grigino smunto con bordo di 1 pixel e fare il gradiente pcwiki sullo sfondo (magari iniziando a fare il normal-light-normal che aveva chiesto gika mesi fa e che dovremmo iniziare ad implementare)

**Comment by davla** [comment]
Sto cominciando a odiare il colore background. Per me è bianco. E i bordini di 1px manco li vedo

Comunque:
- Il colore background quindi non si usa come background al posto del bianco perché a te non piace? Poi sono io quello che ha i colori accecanti.
- Il gradiente __alla gika__ non va bene lì. I box della gallery sarebbero troppo piccoli perché si noti anche la presenza di un gradiente.
