### ISSUE TITLE
Possibilità di svuotare la cache CloudFlare lato admin

### ISSUE THREAD

**Issue by mexicat** [pokemoncentral/wiki-project#3]
## Descrizione

Se vengono caricati file sostitutivi di immagini già presenti, la cache CloudFlare continua a mostrarne la versione precedente. Servirebbe un comando (lato Telegram? lato MediaWiki?) che permetta di vuotare la cache di singoli URL senza accedere al resto della configurazione CloudFlare, oppure un hook post-salvataggio che faccia questa cosa in automatico.

## Risoluzione del problema

- [x] Valutare il modo più semplice e mantenibile di svuotare la cache per singoli file
- [x] Implementazione

**Comment by CiaobyDany** [comment]
Dopo il problema causato da LGPE faccio un up su questa issue perché servirebbe poterlo fare in tempi umani.

**Comment by mexicat** [comment]
Su https://cfbust.herokuapp.com trovate una mini-webapp che assolve a questo compito. Si può usare con il form o con una chiamata in POST a `/api` con del JSON formattato tipo `{urls: ["url1", "url2", ...]}`. In futuro metterò online il repo e aggiungerò una qualche forma di autenticazione.

**Comment by CiaobyDany** [comment]
@mexicat Molto figo, ma essendo questa pagina pubblica non credo che sia il caso di lasciare qui il link 😅
