### ISSUE TITLE
Versione mobile dell'Evobox

### ISSUE THREAD

**Issue by flavio-a** [pokemoncentral/wiki-project#30]
## Descrizione
L'Evobox (o come accidenti si chiama) da mobile è inguardabile.

## Risoluzione del problema
Ottima domanda. La proposta più ovvia (che mi sembra ragionevole) è un layout verticale, con ramificazioni affiancate, per quasi tutti i Pokémon. Fanno eccezione quelli con almeno 3 rami (ovvero Eevee, Tyrogue e Rockruff), che necessitano di un layout custom.
Visto che tutti e tre hanno una sola evoluzione, si stava pensando di mettere la forma base a sinistra e tutte le evoluzioni in verticale a destra (un po' come le evoluzioni ramificate attuali), realizzandolo con due elementi separati per desktop e mobile (nascosti a seconda della dimensione dello schermo).

## Discussione iniziale
In generale si è pensato di togliere molti elementi presenti nel template da mobile. Le proposte sono:
- Mettere i MS invece degli sprite (Dany disapprova)
- Togliere le scritte "prima evoluzione", etc... lasciando solo quella per i Pokémon baby
- Togliere i tipi

**Comment by CiaobyDany** [comment]
@flavio-a Se mi mettete i MS solo da mobile e da fisso rimangono i modelli statici posso approvare (tanto so che non potrei evitarlo comunque)

**Comment by davla** [comment]
Sì, ovvio. Le modifiche di cui si parla qui affliggono solo la versione Mobile

EDIT:
![tyrogue](https://user-images.githubusercontent.com/12073088/41591508-3c0bf7ee-73ba-11e8-91c2-3fca3175bfd9.png)

Non c'è bisogno di fare niente, siamo già a posto :stuck_out_tongue_closed_eyes:

**Comment by flavio-a** [comment]
\*_**Reiso deddo** sull'issue_\*
C'è una cosa che non mi è chiara: vogliamo tenere il layout orizzontale da desktop e farlo diventare verticale da mobile o vogliamo farlo diventare sempre verticale? Così inizio a lavorare su un prototipo.

**Comment by CiaobyDany** [comment]
Direi la più facile/leggera sulla pagina: sempre verticale. Peraltro ho visto la tua sandbox e non mi è parsa malvagia, nonostante i bordi in solid color.

**Comment by flavio-a** [comment]
Ok, via ai commenti (anche da telefoni stretti)
https://wiki.pokemoncentral.it/Utente:Ff300/sandbox#Prove_Evobox
questo concept dovrebbe funzionare bene su qualsiasi dispositivo ed essere abbastanza modulare da gestire qualsiasi cosa non richieda più di due forme affiancate.
Dovrebbe essere comodo anche per cose buffe tipo Necrozma, che mi immagino in un layout verticale 1-2-1

**Comment by CiaobyDany** [comment]
@flavio-a E... No, non mi convince. Non ho capito le doppie frecce oblique/basse, immagino che fosse da scegliere tra le due. Direi basse perché oblique dovrebbero formare una linea obliqua nel diagramma della evoluzione e trovo la cosa abbastanza infattibile. Provare come per il template degli allenatori bordo esterno in gradiente, box bianco, e ogni box Pokémon ugualmente con bordo in gradiente, box bianco e modello su gradiente radiale?

**Comment by CiaobyDany** [comment]
@CiaobyDany Oppure al contrario, bordo esterno in gradiente, megabox bianco, singoli box in gradiente e cerchio del modello bianco. Forse questa è più soddisfacente di soluzione.

**Comment by davla** [comment]
Non in ordine

* Se non metti i casi patologici tipo Eevee non se ne fa niente
* Il box bianco puzza. Io sono per mettere più padding tra i box e toglierli.

**Comment by flavio-a** [comment]
Spoiler:
>  Fanno eccezione quelli con almeno 3 rami (ovvero Eevee, Tyrogue e Rockruff), che necessitano di un layout custom.
Visto che tutti e tre hanno una sola evoluzione, si stava pensando di mettere la forma base a sinistra e tutte le evoluzioni in verticale a destra.

Quindi Eevee non va preso in considerazione :P

**Comment by flavio-a** [comment]
@CiaobyDany sì, le frecce oblique sono un'idea che mi era venuta ma non mi avevano convinto più di tanto, le avevo lasciate solo perché nel caso non mi andava di cercarle di nuovo su Google.

La soluzione _à la Maze_ per la linea singola mi piace abbastanza, il problema è sulla linea doppia che non distingue benissimo tra le due evoluzioni affiancate. Prevengo già la proposta di @davla di aumentare il padding tra le due forme dicendogli che se vogliamo tenerle affiancate da mobile non possiamo lasciare troppo spazio vuoto. Poi non dico che non si possa fare ma prima di proporlo tieni in considerazione questo fatto. C'è da dire che le `img-fluid` aiutano molto, ho provato a restringere lo schermo a 300px di largehzza e si vede ancora abbastanza bene, però eviterei di giocarci troppo spazio vuoto in mezzo.

La soluzione _à la Dany_ (a parte che ha poco padding sui box, si sistema ma adesso ho sonno) pensavo venisse molto peggio e invece ci stà finché abbiamo un colore simile. Se iniziano a spuntare box di tutti i colori in giro fa abbastanza tamarro, però c'è da dire che quasi sempre le evoluzioni condividono almeno un tipo, se non sono proprio uguali.

**Comment by Cruifer** [comment]
Si potrebbe provare una cosa più simile ai template dei Pokémon di tizio? Mi spiego meglio, intendo un box con il classico gradiente, un bordo bianco intorno al box del Pokémon e il gradiente radiale dentro. Non è detto che venga bene, ma volevo almeno avere un'idea. 
P. S. io metterei il box grande a `width-sm-100` è brutto forte vederlo stretto come adesso.

**Comment by davla** [comment]
Avrò gusti orrendi, ma i cerchi binachi mi fanno schifo e tanto. Però secondo me ci sta la seconda versione senza il cerchio bianco. Proprio con niente, lo sprite sopra sullo sfondo gradiente del resto del box e basta.

**Comment by flavio-a** [comment]
@Cruifer È quello che c'era prima e che Dany ha disapprovato, comunque dopo lo ritiro fuori dalla cronologia

**Comment by Cruifer** [comment]
@flavio-a Sì, ma quello che c'era prima aveva il box grande bianco con dentro anche le scritte sotto del Pokémon (o ricordo male io?). Comunque ci sarebbe da considerare la proposta di dedalo, che alla fine come compromesso secondo me può anche andare bene.

**Comment by flavio-a** [comment]
@Cruifer ah scusa, avevo capito male cosa intendevi. Sì, quello di prima aveva il box bianco rettangolare con anche nome, tipo, etc. dentro; tu invece vorresti provare una cosa tipo bordo bianco che separa il modello dal gradiente esterno, giusto?

Ammetto che tra le prove (vedi galleria dopo) quella di Maze è abbastanza convincente. La versione Crusca con bordino bianco tondo è... strana. La versione con box quadrato non mi piace, preferivo la proposta originale con il box che include anche le scritte

Galleria:
Se ho capito bene questo è come voleva Crusca.
![crusca](https://user-images.githubusercontent.com/11007745/43893445-4c7ed8de-9bcf-11e8-8c89-32cce140af66.png)

L'altra possibilità è che volesse questo
![crusca2](https://user-images.githubusercontent.com/11007745/43893502-7b929ec6-9bcf-11e8-8d23-8469bd048763.png)

Questo dovrebbe essere quello che proponeva Maze
![maze](https://user-images.githubusercontent.com/11007745/43893513-866bda92-9bcf-11e8-98b3-3866ff47f65b.png)

Questo non lo so però non mi piace.
![boh](https://user-images.githubusercontent.com/11007745/43893528-9262d954-9bcf-11e8-9f99-26b9bc824256.png)

**Comment by Cruifer** [comment]
Sì quello che intendevo io era il secondo, e onestamente è quella che mi piace di più rispetto alle altre. Anche l'ultima non è male comunque.

**Comment by flavio-a** [comment]
Il problema dell'ultima a mio avviso è che c'è troppo spazio tra il modello e le scritte relative ad un Pokémon, e questo spazio non si può togliere (quello è il minimo che si può ottenere) perché i modelli sono 150x150, quindi hanno del "padding intrinseco". Cioè, guarda Bulbasaur.

Io resto per le immagini 2 e 3 (e comunque a me non dispiaceva box bianco per ogni Pokémon con immagine su gradiente radiale che Dany ha bocciato).

**Comment by davla** [comment]
Il *padding intrinseco* si può togliere in qualche modo. Il punto è che ci sono modelli che lo spazio lo prendono tutto.

Ad essere onesto, la 2 senza gradienti radiali è quella che mi piace di più. Cioè, quel cerchio bianco sarebbe brutalmente un bordo. Sarebbe da provare con modelli grossi, tipo MegaCharizard Y.

**Comment by flavio-a** [comment]
@davla Cosa intendi con "la 2 senza gradienti radiali"? Intendi la 4 (che è la seconda immagine senza gradienti radiali) o intendi una versione modificata della 2?

**Comment by davla** [comment]
La seconda che hai detto. Se lasci al roba in sandbox, oltre che fare gli screenshot, la prossima volta aggiungo io stesso.

**Comment by flavio-a** [comment]
Mi rompe avere 400 versioni del template in sandbox (che poi diventa altissima), è una menata mia.

Tornando IT: la 2 senza gradienti radiali non è quella che c'è adesso in sandbox con solo il cerchio bianco?

**Comment by CiaobyDany** [comment]
A me piace molto la 2 per il momento, btw, in [Linkable](https://wiki.pokemoncentral.it/Utente:Ff300/Linkable) metterei le dimensioni dei modelli fissi a 192px, altrimenti se hai qualcosa che sfora ti ritrovi disallineamenti e gli OCD si triggerano tantissimo.

**Comment by flavio-a** [comment]
Il problema è che non c'è nessuna garanzia che 192px sia (e resti) la dimensione massima di un modello. Anzi, UltraNecrozma è già largo 202px, e personalmente non sono molto a favore di hardcodare così la dimensione massima di un modello in un template. Anche perché distinguiamo tra due problemi: se ci sono in verticale due modelli di dimensione diversa gli OCD si arrangiano anche se i cerchi non sono della stessa larghezza. Se invece i due modelli di dimensione diversa sono allineati in orizzontale beh, sono casi rari  (ho trovato solo Exeggutor e Charizard nel box delle mega). Piuttosto propongo di rimpicciolire a 150px i modelli troppo grossi quando vengono affiancati.

**Comment by flavio-a** [comment]
Ma quindi piace a tutti la 2 (più o meno)? Nel caso butto via tutto il resto e inizio a lavorare solo su quella.

Vorrei anche sottoporre un altro problema: lasciare sempre l'evobox in verticale occupa un sacco di spazio lasciando vuoto di lato da desktop. Da mobile chiaramente è l'unica soluzione, ma da desktop pensavo di provare a "girarlo" in orizzontale, soprattutto visto https://wiki.pokemoncentral.it/Floette#Evoluzioni. Da mobile non ci si può fare niente e soprattutto le sezioni sono collassate di default, quindi uno deve scrollare infinito solo se apre la sezione (e quindi si suppone voglia leggerla). Da desktop invece con gli Evobox verticali verrebbe una cosa schifosamente alta, che fai notte ogni volta che devi scrollare.

**Comment by Cruifer** [comment]
@flavio-a Perché, come verrebbe su desktop? Puoi mettere uno screen? Comunque io lo dicevo che la due è la meglio

**Comment by flavio-a** [comment]
Se intendi Floette non ho uno screen, però l'evobox verticale in generale viene qualcosa del tipo
![screenshot_13-08_20 01](https://user-images.githubusercontent.com/11007745/44049197-bd23db86-9f33-11e8-8b95-14b27f408a60.png)
(lascia perdere che è una versione vecchia, avevo quello a portata di mano, lo spazio bianco di fianco non cambia)

Comunque ora potete trovare nella mia sandbox la versione che si gira (guardandola da mobile non dovreste vedere differenze da prima).
https://wiki.pokemoncentral.it/Utente:Ff300/sandbox
È implementata la versione 2, che mi sembra quella che riscontra più successo, ma cambiare forma/colore/sfondo dei box non dovrebbe essere difficile tenendo quel layout.

**Comment by Cruifer** [comment]
Andrebbe implementato anche per i Pokémon glitch. C'è modo di farlo utilizzando lo stesso modulo?

**Comment by flavio-a** [comment]
Questa è una domanda non banale. La risposta vorrebbe essere sì, ma al momento è decisamente no. Per come è fatto il modulo adesso, ci sono degli ostacoli notevoli. Questa è una debolezza del modulo attuale che sto parzialmente risolvendo mentre cerco di creare il tanto atteso (da me e Maze) modulo Evo/data, ma se mi dici che l'Evobox dovrà gestire anche i glitch (come in effetti sembra sensato) lo dovrò considerare nelle modifiche future. Ci lavorerò.
Comunque vi direi di non aspettarvi aggiornamenti a breve su questo fronte.

**Comment by davla** [comment]
Consiglio di fare un modulo a parte, magari con input manuale. I glitch fanno cosi stranissimi, e a conti fatti l'evobox non fa millemila calcoli come il `DebRes`. L'unica cosa è verificare se l'utilità dell'`Evobox/data` per i glitch in altri contesti possa essere utile (per esempio, le mosse in corsivo nei `learnlists`).

**Comment by flavio-a** [comment]
Sicuramente non avevo intenzione di fare un modulo dati per le evoluzioni dei glitch (che magari iniziano ad evolversi in modi a caso, brrr...). L'idea era solo di riciclare tutto il macchinario dell'Evobox (grafica, funzioni che creano certi box, etc...) nel limite del possibile con una chiamata manuale.

**Comment by davla** [comment]
Se pensi che sia inutile, allora a postissimo.

**Comment by flavio-a** [comment]
Non ho guardato per i glitch, ma ho guardato per il modulo dati delle evoluzioni, prometto che poi guarderò anche per quelli (anche perché l'interfaccia con parametri è sempre utile).
In pokemoncentral/wiki-lua-modules@ad77d06023e78c638182c29e772355eaeffc28df potete vedere che ho aggiunto le evoluzioni per livello di (spero) tutti i Pokémon che si evolvono in quel modo, più qualcosa per un po' di altri Pokémon che però è probabilmente a caso. Al momento si cercano volontari per aggiungere le famiglie mancanti, che dovrebbero grossomodo corrispondere a quelle in [questa pagina](https://wiki.pokemoncentral.it/Evoluzione/Evoluzioni_particolari). In giro per il modulo ci dovrebbero essere esempi per più o meno qualsiasi cosa (fatti da me per testing), che potete trovare già radunati [a questo indirizzo](https://github.com/pokemoncentral/wiki-lua-modules/blob/2ea3fb8004182f123c6e8aba0ed5ae2d77a60771/Evo-data.lua). Altrimenti potete sempre chiedere a me.
Naturalmente non è necessario fare tutto in una volta. Se aggiungete qualche Pokémon basta committare (magari scrivete nel messaggio cosa avete fatto), e io penso lavorerò così per pezzi.
PS: mi ricordo che @lucas992 voleva offrirsi volontario. Vero, Luca?

**Comment by lucas992x** [comment]
Diciamo che sono stato gentilmente offerto come volontario :P quindi potreste essere altrettanto gentili ad abilitarmi per modificare cose, visto che mi dice "You must be on a branch to make or propose changes to this file" (oppure spiegarmi cosa devo fare per auto-abilitarmi se ne sono in grado).

**Comment by flavio-a** [comment]
https://github.com/pokemoncentral/wiki-lua-modules/edit/evo-data/Evo-data.lua
Da qui non ti fa modificare?

**Comment by lucas992x** [comment]
Da lì sì, è il terzo link del messaggio precedente che me lo impedisce mostrandomi quel messaggio, ma se quello che devo modificare è quest'altro non ci sono problemi, mi ci metterò con comodo (così ne approfitto anche per ricontrollare quelle già inserite).

**Comment by flavio-a** [comment]
Ah no, il terzo link è solo un comodo elenco di quelli già fatti da cui si dovrebbe (spero) capire cosa fare nei vari casi. E non è davvero modificabile (ma non sembra neanche una buona idea, visto che mi sono sbattuto per creare in automatico tutti quelli per livello).

**Comment by flavio-a** [comment]
Ok, ho finalmente guardato per i glitch e con un po' di lavoro (che non ha ridotto considerevolmente il lavoro, purtroppo) dovrei aver prodotto una cosa funzionante che gestisce anche i glitch (al costo di volere parametri per _tutto_).
L'altra cosa da fare (forse) è aggiungere i dati per il cambio di forma all'Evo-data, devo valutare un attimo il rapporto vantaggi/sbatti (visto che comunque c'è già la funzione con la chiamata manuale anche per quello).

**Comment by Cruifer** [comment]
non è per essere insistente, ma riapro di nuovo perché mancano ancora i glitch

**Comment by flavio-a** [comment]
Eh che palle, solo ai glitch sai pensare. Devo metterlo nelle pagine, ma sembra che sarà più difficile del previsto, non sembra si riesca a fare in automatico.

**Comment by Cruifer** [comment]
boh se mi dici cosa c'è da fare in particolare posso farlo io di metterlo nelle pagine

**Comment by flavio-a** [comment]
In realtà (a parte Missigno. che non funziona perché fa cose che non mi aspettavo) posso finire di farlo io, sono già oltre metà e se prendo il ritmo ci metto relativamente poco a fare una pagina.

EDIT: mancano solo i seguenti Pokémon, che per ora non si possono fare per limitazioni del modulo:
- [ ] https://wiki.pokemoncentral.it/Missingno.#Evoluzione
- [ ] https://wiki.pokemoncentral.it/PkMn_%3F_A#Evoluzioni
- [ ] https://wiki.pokemoncentral.it/%3F%3F%3F%3F%3F_(FE)#Evoluzioni
- [ ] https://wiki.pokemoncentral.it/%3F%3F%3F%3F%3F_(FF)#Evoluzioni
- [ ] https://wiki.pokemoncentral.it/Bad_Clones#Evoluzioni_dei_Bad_Clones

**Comment by lucas992x** [comment]
Bisogna aggiungere la nebbia a Sliggoo (lo scrivo come promemoria, sempre se qualcuno non mi precede).

**Comment by CiaobyDany** [comment]
@lucas992 L'ho già aggiunta io ieri. L'ho messa nelle pagine di Goomy, Sliggoo e Goodra e nella pagina delle evoluzioni particolari. Va segnato anche altrove?

**Comment by lucas992x** [comment]
@CiaobyDany Nel modulo dati, ossia Evo-data.

**Comment by CiaobyDany** [comment]
@lucas992 Oh. Mi ero perso il fatto che sia diventato un modulo. Ottimo.

**Comment by flavio-a** [comment]
@CiaobyDany fatto
