### ISSUE TITLE
Merge pagine "pietre evolutive" e "strumenti evolutivi tenuti" in "strumenti per evolvere i Pokémon" (tentative title)

### ISSUE THREAD

**Issue by CiaobyDany** [pokemoncentral/wiki-project#33]
## Descrizione
Poiché le due pagine trattano argomenti decisamente simili sotto molti aspetti, potrebbe essere utile una loro unione in un'unica pagina che raccolga tutto, considerando che ci ritroveremo ad avere una pagina per singolo strumento (issue #31), pertanto dovrebbe diventare un banale elenco non particolarmente lungo.

## Pagine affette
* https://wiki.pokemoncentral.it/Pietre_evolutive
* https://wiki.pokemoncentral.it/Strumenti_evolutivi_tenuti

## Risoluzione del problema
Come per la issue #32, considerando l'elevatissimo numero di visite delle pagine vorremmo sentire il parere di @mexicat prima di procedere con il merge.

**Comment by mexicat** [comment]
👍

**Comment by lucas992x** [comment]
La fusione è stata completata. Chiudo.
