### ISSUE TITLE
Gestione lingue straniere con caratteri non latini in tabelle/infobox

### ISSUE THREAD

**Issue by CiaobyDany** [pokemoncentral/wiki-project#34]
## Descrizione
Credo che sia il caso di decidere una regola uniforme da seguire in tutto il sito così da evitare di rifare le stesse modifiche 10 volte annullandosele a vicenda. Da sempre i nomi in lingue non latine (prevalentemente giapponese, cinese e coreano) hanno avuto trascrizioni di qualche tipo in caratteri latini per consentire ai visitatori di capire meglio di cosa si trattasse. Tuttavia ogni tanto mettiamo traslitterazioni (ovvero come si legge il nome straniero con l'alfabeto latino secondo regole di trascrizione più o meno condivise globalmente), ogni tanto mettiamo traduzioni, ogni tanto mettiamo entrambi.

## Pagine affette
Praticamente ogni pagina del wiki, visto che abbiamo quasi sempre la sezione in altre lingue

## Risoluzione del problema
Credo di essere il membro dello staff più giappofag e che conosce meglio il giapponese, quindi credo anche di essere anche la persona più indicata per gestire la questione.
Negli infobox tendenzialmente mettiamo il nome italiano (siamo un'enciclopedia italiana), il nome inglese (quello più noto al mondo, spesso le persone lo conoscono meglio di quello italiano) e quello giapponese (il nome originale che è decisamente worth mentioning). A volte è presente la traduzione letterale di questi nomi negli infobox (parlo di mosse, abilità, ecc., non di nomi propri di personaggi ovviamente), e secondo me è utile mantenerla, poiché spesso nei langtable a fondo pagina la traduzione non è presente e quindi il visitatore non ha modo di ottenere quell'informazione in altro modo. Oltre a questo io sarei favorevole all'introduzione dei romaji (trascrizione in caratteri latini del giapponese) in tt sopra al nome giapponese (nota a margine: finalmente il tt non va in conflitto con gli span lang, come in passato, quindi questa soluzione è effettivamente attuabile), così che i giappofag (che presumo siano la maggior parte di chi va a controllare quel nome) abbiano modo anche di leggerlo (no, essere jappofag non ti fa automaticamente imparare 8000 ideogrammi, quindi non è detto che si sappia leggere).
Questione langtable. Bulba non mette il giapponese perché lo lascia sempre nell'introduzione. Imo repetita juvant, quindi a discapito di dove si trovi altrove, il giapponese lo rimetterei anche nel langtable. E userei lo standard ja={{j|kanji}} ''romaji''. _Senza la traduzione in tt_. Per motivazioni ignote al mondo, infatti, per il coreano e il cinese Bulba mette la traduzione in tt sopra la trascrizione. Il che è privo di significato da noi, perché abbiamo un parametro apposito per la traduzione/spiegazione (<lang>mean), se volessimo inserirla, e non capisco perché dovremmo mettere la traduzione solo di cinese, giapponese e coreano e non di tutte le altre lingue. E poiché è oggettivamente difficile ottenere le traduzioni di ogni lingua in ogni pagina (lavoro immenso, che richiede conoscenze estese di ogni lingua che si traduce, e a volte abbiamo anche vietnamita e greco che dubito qualcuno conosca, e oggettivamente di scarso interesse per il visitatore medio), credo che sia più sensato non metterle da nessuna parte anche per una questione di uniformità.
Una volta trovato lo stile uniforme da seguire non credo sia utile lavorare esclusivamente per rendere il sito coerente con la decisione presa, basta tenerlo a mente e correggere quando capita di lavorare alle pagine per altre motivazioni.

Ci sarebbe da discutere anche della presenza dell'italiano nel langtable, ma prima vorrei risolvere questo problema.

Nota a margine correlata ma non troppo all'issue. Capita che i nomi cinogiapporeani siano in realtà nomi inglesi trascritti nei rispettivi alfabeti. In tali casi è pratica comune (almeno in giapponese) che la ri-trascrizione in romaji sia il nome originale inglese piuttosto che la lettura dei caratteri giapponesi. Esempio chiarificatore: マジックミラー è la trascrizione dell'inglese "magic mirror", ma letteralmente si leggerebbe Majikkumirā. È evidente che la seconda trascrizione non farebbe comprendere a chiunque non conosca le regole di trascrizione giapponese che il termine di riferimento sia magic mirror, facendo perdere parte del significato. Immagino funzioni similmente in coreano e in cinese, tuttavia non ho competenze in quelle lingue per poterlo appurare con certezza. Di solito se vedo che Bulba ha lo stesso nome inglese per giapponese e coreano assumo che derivino entrambi da quel nome e lo lascio così anche in coreano, ma il cinese è troppo complesso per poter fare ragionamenti simili.

NB: ho detto di essere il più indicato a gestire la questione, ma non vuol dire che non voglia discutere la mia posizione, altrimenti non avrei aperto l'issue. Se avete idee che ritenete migliori della mia esponetele tranquillamente.

**Comment by lucas992x** [comment]
Per gli infobox, io sono d'accordo a mettere `{{tt|kanji|romaji}} (traduzione)`, mi sembra la cosa migliore (ovviamente la traduzione solo dove ha senso).

Per il langtable:
- Sono favorevole a metterci tutte le lingue anche se presenti altrove (che sia un infobox o altro).
- Anche se comprendo la questione uniformità, preferirei lasciare il significato dove disponibile invece di toglierlo a prescindere.
- L'italiano lo lascerei solo se ci sono pochissime altre lingue (non più di 2-3), in modo da "popolarlo" un po' finché non se ne trovano altre.

Per i nomi giapponesi trascritti dall'inglese, sarebbe bello poter indicare entrambe le cose (la pronuncia e il fatto che in realtà sia "inglese giapponesizzato"), ma mi rendo conto che sia una cosa complicata. A sto punto dovendone scegliere una sola, se Bulba mette direttamente il nome originale inglese lascerei quello anche da noi, più che altro per semplicità (quell'informazione l'abbiamo già mentre la pronuncia è più difficile da reperire).

**Comment by CiaobyDany** [comment]
Preferiresti lasciare il significato dove disponibile con che modalità?

Se ti viene in mente un layout decente con cui indicarlo sono favorevolissimo a farlo. Su Bulba non si fanno problemi perché essendo il nome in inglese mettono l'originale inglese al posto della traduzione e la traslitterazione dall'altra parte (cosa che comunque non fa capire che il nome giapponese _è_ il nome inglese). Da noi abbiamo già: katakana, inglese e italiano. Aggiungere i romaji è onestamente difficile.

Ho girato il link della discussione ad Ale che in modo del tutto inaspettato è stato d'accordo con me su ogni punto. I'm really impressed.

**Comment by flavio-a** [comment]
@lucas992 Sono contrario a questo uso dell'italiano come riempitivo. Per l'italiano dovrebbe esserci _solo_ se c'è l'origine del nome/nomi diversi, altrimenti uno lo può leggere dal titolo della pagina.

I nomi giapponesi trascritti dall'inglese non mi sembra così necessario indicarli, però se si trova un modo ragionevole non sono contrario (non un'altra scritta, però, troppo affollamento a mio parere inutile)

**Comment by CiaobyDany** [comment]
@flavio-a Sono abbastanza d'accordo con te per l'italiano.

Intendi le trascrizioni letterali (majikumiraa)? Sono d'accordo anche su quello

**Comment by flavio-a** [comment]
@CiaobyDany Non so il nome, intendo roba tipo <un po' di caratteri giappi> che si leggono _faasto eido_ con traduzione "first aid"

**Comment by lucas992x** [comment]
Si potrebbe fare in modo che il parametro __qualcosameaning__ non vada a creare una nuova colonna ma scriva nella stessa casella, in modo da non ritrovarsi delle caselle vuote.

**Comment by CiaobyDany** [comment]
@lucas992 Il che è inutile, se lo metti nella stessa casella tanto vale aggiungerlo di fianco al nome.

**Comment by CiaobyDany** [comment]
Up! @Cruifer @davla non hanno detto niente quindi è silenzio assenso? @flavio-a non hai detto cosa ne pensi dei tt su cinoreani con le traduzioni.

**Comment by flavio-a** [comment]
Per la cosa di Bulba che mette la traduzione di giappocinoreano assolutamente a caso? Ramiamo via tutto, traduzioni o sempre o mai (e sempre è troppo difficile se non ci sono su Bulba), non traduciamo solo gli asiatici perché hanno degli alfabeti strani. Le traduzioni dei giappi sono ok negli infobox, ma nel langtable niente.

**Comment by Cruifer** [comment]
Allora, mi sono un po' escluso da questa discussione perché non credo di essere abbastanza competente ma vabbè. Comunque siamo sicuri di volere la traduzione dei nomi jappo? Perché di solito (o sbaglio?) da noi la traduzione è in realtà la traduzione della traduzione in inglese. Secondo me si rischia di perdere sfumature nel significato che potrebbe storpiarne il risultato, ma non sono sicuro.

**Comment by CiaobyDany** [comment]
@Cruifer Una doppia traduzione non è mai auspicabile, vero. Ma è altrettanto vero che spesso i nomi sono così basilari che sono difficili da tradurre in modo errato. Anche perché hai un contesto preciso su cui basarti. In ogni caso non capisco perché rimuovere un'informazione perché in alcuni casi non è completamente corretta (conta che comunque hai spesso nomi inglesi quindi è una traduzione diretta).

**Comment by davla** [comment]
Ah, non mi sono mai impicciato di questa cosa. Ma as long as mettete il `lang="ISO-CODE"` nell'HTML mi va bene tutto.

**Comment by CiaobyDany** [comment]
Posto che non avendo avuto nessun parere contrario serio sto continuando nella mia strada sulle langtable, mentre sistemavo una pagina ho trovato un'idea carina da usare per lo standard degli infobox. La nomenclatura dei parametri preferibilmente dovrebbe essere più user friendly, ma volendo mantenere quanto già presente non avevo molte alternative, btw, la prova è questa: https://wiki.pokemoncentral.it/Foresta_degli_Shroomish

**Comment by Cruifer** [comment]
@CiaobyDany Ma quindi da ora in avanti lo standard è questo?

![50fe0055-06d7-490f-a3df-40cc0c3e24cc](https://user-images.githubusercontent.com/38588039/45483711-07270880-b752-11e8-90b2-f6860c49a6c8.jpeg)

Se mi dai conferma guardo se c'è da modificare qualcosa in #52. E si potrebbe anche pensare di chiudere l'issue, in effetti.

**Comment by CiaobyDany** [comment]
@Cruifer In linea di massima direi di sì. Ho visto una variante con anche i nomi stranieri in corsivo che mi convinceva molto poco principalmente perché il giapponese in corsivo è un'invenzione occidentale, se provi a scrivere un kanji storto ti sparano.

**Comment by Cruifer** [comment]
@CiaobyDany quindi questa cosa sarebbe da evitare come la morte, sì?
![dfc54c7c-530c-4762-b519-72d8b383fb20](https://user-images.githubusercontent.com/38588039/45486836-c97bad00-b75c-11e8-9a8b-5501d4ade047.jpeg)

**Comment by CiaobyDany** [comment]
@Cruifer Direi di sì. Si può lasciare l'inglese in corsivo volendo, ma sono sempre più convinto che il giapponese in corsivo sia una bestemmia. Mi aveva sempre lasciato stranito ma non riuscivo a capire quale fosse il problema nel concreto.

**Comment by Cruifer** [comment]
Ho sistemato. Ne approfitto per chiudere l'issue, tanto il layout così mi sembra più che soddisfacente.
