### ISSUE TITLE
Rimozione gen in gensup e genblackabbrev

### ISSUE THREAD

**Issue by CiaobyDany** [pokemoncentral/wiki-project#35]
## Descrizione
Ho realizzato che in realtà il "gen" più che essere brutto, occupare spazio, metterci in disaccordo su maiuscola/minuscola e fare casino con i layout non fa molto. Inoltre se togliamo il gen imo risultano molto meno awkward i mallopponi di sigle in parte con i giochi e in parte con le generazioni. (tra l'altro faccio notare che gli elenchi abilità già non hanno il termine gen per indicare i cambi generazionali)

## Pagine affette
* https://wiki.pokemoncentral.it/Adamasfera esempio genblackabbrev
* https://wiki.pokemoncentral.it/Magispecchio esempio gensup

## Risoluzione del problema
Togliamo il gen dal gensup in modo molto easy. Per il genblackabbrev non sono sicuro mi soddisferebbe il trattino su sfondo grigio, e d'altro canto lasciarlo su sfondo bianco sarebbe anche peggio, quindi voglio sapere da voi.

**Comment by lucas992x** [comment]
Come mai non ti soddisferebbe il trattino su sfondo grigio?

**Comment by flavio-a** [comment]
Approvo togliere il gen dal gensup (si capisce abbastanza, e ci sono i link).
Per il trattino su sfondo grigio a me non dispiace, anche perché si vede poco
![schermata 2018-08-04 alle 17 06 29-fullpage](https://user-images.githubusercontent.com/11007745/43677827-e1a1cce8-9808-11e8-95fd-5823e89cc728.png)

**Comment by CiaobyDany** [comment]
Quindi sul gensup siamo tutti d'accordo, sul genblackabbrev?

**Comment by flavio-a** [comment]
Io sono a favore del trattino su sfondo grigio. Per quanto riguarda il `gen` non mi dispiace se c'è solo una chiamata a genblackabbrev; al contrario se si trova in un elenco insieme ad un po' di sigle di giochi lo toglierei. Si potrebbe pensare di aggiungere un parametro per far apparire la scritta "gen" davanti (di default però non la metterei).

**Comment by CiaobyDany** [comment]
@flavio-a Onestà 100%: mi peserebbe molto il culo aggiungere il parametro e peserebbe ancora di più inserirlo considerando che spesso il template è richiamato da altri template e non è così facile aggiungere parametri in più rispetto a quelli base.

**Comment by flavio-a** [comment]
Vero anche questo. Niente parametro e tutti contenti. Quindi io voto trattino grigio e togliere gen davanti anche al genblackabbrev.

**Comment by CiaobyDany** [comment]
@flavio-a Avete tempo fino a domenica per farci cambiare idea, poi chiudo e tolgo gen ovunque.

**Comment by Cruifer** [comment]
@CiaobyDany comunque domenica è passata :P

**Comment by CiaobyDany** [comment]
E c'hai ragione pure tu. Fatto.
