### ISSUE TITLE
Traduzione post-game in italiano

### ISSUE THREAD

**Issue by CiaobyDany** [pokemoncentral/wiki-project#36]
## Descrizione
Su Bulba viene spesso utilizzato il termine post-game e tendenzialmente non abbiamo una linea guida da seguire unica per la sua traduzione.

## Risoluzione del problema
Possibili soluzioni: lasciare post-game, oppure tradurlo con dopo aver terminato la trama principale e/o aver compiuto l'effettiva azione che fa sbloccare tale azione (tendenzialmente diventare campioni).

**Comment by lucas992x** [comment]
Per quanto riguarda il nome da usare, io proporrei post-Lega, breve ed efficace. In ogni caso comunque ci creerei una pagina, qualcosa da dire c'è.

**Comment by flavio-a** [comment]
post-Lega mi piace, anche se non sono sicuro che sia sempre preciso. Ci sono giochi in cui il "post-game" non è dopo la Lega? E poi ci sono gli spin-off: anche quelli hanno il post-game, ma sicuramente non è un post-Lega.
Io direi questo: se siamo sicuri che nella serie principale post-Lega vada bene sempre (credo di sì) usiamo quello, per gli spin-off invece sceglierei un  "dopo aver terminato la trama principale" perché vorrei evitare di inserire spoiler. La "trama principale" di solito è ben definita dai titoli di coda (in effetti ripensandoci si potrebbe usare "dopo i titoli di coda") e in molti spin-off è brutto spoilerare la fine, mentre nella serie principale si sa che in fondo c'è sempre la Lega (ok, forse ad Alola non è così ovvio, ma pace).

**Comment by lucas992x** [comment]
Per la serie principale va sempre bene post-Lega, ma se vogliamo essere generici e includere gli spin-off possiamo stabilire post-game che è più generico, e nelle rispettive sezioni metterci il solito avviso spoiler (o anche nella pagina stessa).

**Comment by flavio-a** [comment]
Secondo me non è un problema separare tra serie principale e spin-off. Posto che comunque post-game non mi dispiace anche se è in inglese.

**Comment by davla** [comment]
Post-trama?

**Comment by lucas992x** [comment]
@davla Idea interessante, anche se forse non è del tutto corretta visto che in alcuni giochi c'è una trama che continua dopo i titoli di coda. Però non la scarterei, ci penso un po' su.

**Comment by flavio-a** [comment]
A me non convince perché succede spesso che la trama continui dopo la Lega (mi vengono in mente sul momento due MD e Nero 2).

**Comment by CiaobyDany** [comment]
"dopo aver terminato la trama principale" mi sa di lungo e noioso. Post-trama non va bene perché spesso è usato per riferirsi alla trama post-lega che quindi è ancora trama. Post-game è chiaro all'universo, ma è pur sempre inglese, ci va bene comunque? (so che sto criticando le mie proposte iniziali, ma mi fanno cagare entrambe)

**Comment by flavio-a** [comment]
A me va bene anche post-game, ma erano saltate fuori due proposte interessanti: "post-Lega" per la serie principale e "dopo i titoli di coda" per gli spin-off. Queste non ti aspirano interesse (cit.)?

**Comment by CiaobyDany** [comment]
@flavio-a Post-Lega rimane ambiguo perché la lega la puoi battere n volte, sono sempre più propenso per il trovare il termine dell'evento specifico (dopo essere diventati campione nella serie principale ad esempio)

**Comment by lucas992x** [comment]
@CiaobyDany A sto punto userei post-game che è universale e ci farei una pagina dedicata in cui si scrive cosa significa in ciascun gioco

**Comment by CiaobyDany** [comment]
@lucas992 Like per la pagina, non ci avevo pensato.

**Comment by davla** [comment]
Se si è deciso per post-game, chiudo @CiaobyDany @flavio-a
