### ISSUE TITLE
Citazioni: da rimuovere?

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#38]
Franky e Naty propongono di rimuovere del tutto le citazioni dal wiki, perché ce ne sono poche e perché non le va a leggere nessuno. Anche se non hanno tutti i torti, io non sono molto convinto.

**Comment by flavio-a** [comment]
In teoria le citazioni si potrebbero ottenere dai dump, rendendo più facile reperire quelle dei nuovi giochi. Si potrebbe addirittura provare ad automatizzare la cosa partendo dal sorgente di Bulba (non garantisco niente).
A parte questo sono abbastanza neutrale, mi va bene sia con che senza. Sono lì per completezza, ma non credo le guardi qualcuno.

**Comment by lucas992x** [comment]
Io l'ho già automatizzata in parte, ho scritto un programmino che se in un dump trova una riga identica al testo inserito dall'utente va a leggere la riga corrispondente dal secondo dump e la riporta lì. L'avevo creato per i nomi ma poi l'ho anche modificato per funzionare meglio con le citazioni (ora c'è una spunta per sostituire automaticamente i `\n` con spazi), volendo se si può fare qualcos'altro per migliorarlo posso farlo.

**Comment by flavio-a** [comment]
L'idea era quella, volevo aggiungere qualche altra sostituzione per mettere cose tipo `<giocatore>` che abbiamo noi e poco altro. Il problema sono le azioni tra le frasi (tipo "da al giocatore la MT38") e le scelte del giocatore, che si possono tradurre solo quando sono esattamente identiche. Comunque dovrebbe rimanere abbastanza poco da correggere a mano, che è già un bel vantaggio.

**Comment by CiaobyDany** [comment]
Sinceramente non vedo perché toglierle in toto. Abbiamo già deciso che non sono un elemento determinante per rendere le pagine incomplete, ma perché rimuovere anche quelle che già ci sono? Poi onestamente con i dump recuperarle non è più così pesante come lo era fino a qualche anno fa. Se qualcuno ha sbatti di aggiungerle ben venga.

**Comment by lucas992x** [comment]
Alla fine della fiera, decidiamo quindi di lasciarle? In tal caso, bisognerebbe scegliere uno standard di "posizionamento", perché come mi ha fatto notare un utente a volte si trova nella sezione giochi e altre in una sezione sua.

**Comment by flavio-a** [comment]
Io direi sezione a parte, tra "Nei giochi" e "Artwork" (o "Sprite", non mi ricordo come si chiama quella sezione lì).

**Comment by CiaobyDany** [comment]
@flavio-a Ma se le citazioni vengono dai giochi non avrebbe più senso lasciarli come sottosezioni dei giochi?

**Comment by flavio-a** [comment]
Anche sprite e modelli vengono dai giochi ma hanno una sezione a parte. La mia idea era di evitare 19 livelli di titoli, visto che servono almeno __Citazioni__ e __\<nomegioco\>__, e magari anche __\<posto/situazione\>__, però ha anche senso metterli dentro giochi.

**Comment by lucas992x** [comment]
@flavio-a Sono d'accordo con Flavio e aggiungo: da mobile la sezione ==Citazioni== verrebbe collassata, mentre ===Citazioni=== no, costringendo quindi gli utenti mobile a scrollare parecchio per una cosa che alla fine in pochi guardano.

**Comment by flavio-a** [comment]
Abbiamo deciso di lasciarle in sezione a parte. Chiudo
