### ISSUE TITLE
Rimozione dei suffissi di disambiguazione

### ISSUE THREAD

**Issue by flavio-a** [pokemoncentral/wiki-project#4]
## Descrizione
Bisogna togliere dai titoli delle pagine i suffissi di disambiguazione superflui (es: "Azione (mossa)" -> "Azione").

## Risoluzione del problema

- [x] Fare un elenco dei suffissi da rimuovere
- [x] Fare un elenco delle pagine che avrebbero lo stesso nome
- [x] Spostare in massa tutte le altre
- [x] Modificare i template di collegamento principali

### Opzionale
- [x] Creare delle pagine di disambiguazione per le pagine con lo stesso nome

## Roba da cambiare
- [x] Modulo DebRes
- [x] Modulo DebRes-1-glitch
- [x] Modulo Links

### Abilità
- [x] Modulo Abillits
- [x] Template a 
- [x] Template Acolor

### Mossa
- [x] Template M
- [x] Template Mcolore
- [x] Modulo MTCompatto
- [x] Modulo Wikilib/learnlists

### Tipo
- [x] Modulo Box
- [x] Modulo Dexlist
- [x] Template t
- [x] Template t2
- [x] Template tcolore
- [x] Template Coloretipo
- [x] Template Coloretipo2
- [x] Modulo Typebattle

**Comment by lucas992x** [comment]
Mosse da non spostare:
Bullo
Confusione
Purificazione
Sub

Abilità da non spostare: nessuna.

Tipi da non spostare:
Lotta
Volante
Coleottero
Acqua
Erba
Drago

Tipi del GCC da non spostare:
Erba
Fuoco
Acqua
Combattimento?
Psiche
Drago
Folletto

Gruppi uova da non spostare:
Erba
Coleottero
Volante
Campo
Drago
Ditto
Sconosciuto
Genere sconosciuto?

Classi allenatore da non spostare:
Bellezza
Bullo
Cinturanera
Doppioteam
Anziano?
Proprietario
Sub
Psiche

**Comment by mexicat** [comment]
@flavio-a ricordate di tenere tutti i redirect (se ci sono redirect multipli non è un un problema, posso sistemarlo io coi CLI tools di mediawiki)

**Comment by lucas992x** [comment]
Suffissi da rimuovere:
mossa
abilità
tipo (compresi quelli del GCC?)
classe allenatore
gruppo uova

**Comment by flavio-a** [comment]
Io aggiungerei anche:
* superquattro
* gruppo uova
* virtù

Inoltre non farei una pagina di disambiguazione se un tipo ha lo stesso nome di qualcos'altro (esempio Volante tipo e gruppo uova) ma metterei il [template:Stesso nome](https://wiki.pokemoncentral.it/Template:Stesso_nome) come avviso ad inizio pagina (perché il 90% della gente che cerca Volante vuole vedere il tipo, non un altro omonimo).

**Comment by lucas992x** [comment]
@flavio-a Situazione Superquattro:
- Drake ha un omonimo e ha già la pagina di disambiguazione, quindi va lasciato così.
- Frida ha un'omonima che però è molto meno importante (è il personaggio del giorno di un episodio di BW), e già adesso non ha la dicitura (Superquattro) che non trovo motivi per aggiungere.
- Aaron ha uno pseudo-omonimo, Sir Aaron; attualmente Aaron reindirizza alla pagina Aaron (Superquattro).
- Solo gil altri 3 Superquattro di Sinnoh hanno il suffisso (Superquattro), quindi facciamo anche prima a spostare le 3 pagine a mano.

**Comment by davla** [comment]
Questa è mia, giù le zampe Flavìo!
@mexicat Ma il fixing dei redirect non è la stessa cosa che fa il bot?

**Comment by mexicat** [comment]
@davla volendo si può fare anche con https://www.mediawiki.org/wiki/Manual:FixDoubleRedirects.php - non credo cambi niente però.

**Comment by davla** [comment]
Io approvo li'idea di @flavio-a Di mettere "Stesso nome". Quindi farò così. La gerarchia è:

1. Tipo
2. Abilità
3. Mossa
4. Tipo GCC
5. Gruppo upva
6. Classe allenatore
7. Virtù
8. Superquattro

So che ci sono casi che non capiteranno mai (un tipo con lo stesso nome di un'abilità, fx) ma è tanto per essere completi.

**Comment by lucas992x** [comment]
@davla Promemoria: aggiornare la pagina di aiuto sui template di collegamento

**Comment by davla** [comment]
E dove sarebbe?

**Comment by flavio-a** [comment]
@davla https://wiki.pokemoncentral.it/Aiuto:Template/Collegamento
https://wiki.pokemoncentral.it/Aiuto:Template/Collegamento/Elenco

**Comment by lucas992x** [comment]
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Normale
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Lotta
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Volante
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Veleno
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Terra
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Roccia
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Coleottero
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Spettro
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Acciaio
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Fuoco
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Acqua
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Erba
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Elettro
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Ghiaccio
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Drago
https://wiki.pokemoncentral.it/Template:Mosse_di_tipo_Folletto

**Comment by flavio-a** [comment]
Ho sistemato i template, inoltre @davla non hai spostato la mossa Pugni Plasma.

**Comment by davla** [comment]
Sì, so che ne mancavano alcune, ma ho preso la Categoria:Mosse e le pagine che finivano in **(mossa)**, ma ovviamente mi sono scordato che le categorie puzzano.

@lucas992 Sei fortunato che ho avuto una reminescenza del problema relativo ai link. La prossima volta, basta anche linkare uno solo di quei template, ma devi anche spiegare cosa ci devo fare, LOL

**Comment by davla** [comment]
Cosa si fa per Pokémon Ranger?
Immagino che il gioco prenda precedenza sulla classe allenatore, giusto?

EDIT:
E per [questa](https://wiki.pokemoncentral.it/Team_Flare_(classe_allenatore)) (Team Flare (classe allenatore))? Ovviamente Team Flare esiste già.

EDIT 2:
Stesso per Team Plasma

EDIT 3:
Guess what? Ultrapattuglia

**Comment by flavio-a** [comment]
Nel caso del Team Flare direi decisamente di lasciare il suffisso alla ca e lo mettere lo stesso nome nel Team Flare.
Nel caso di Ranger la questione è più delicata, intanto perché non è così ovvio che lo spin-off di 10 anni fa sia più importante della ca della serie principale che compare ancora oggi (anche se io direi di sì). Inoltre c'è il problema che le pagine sono tre: [gioco](https://wiki.pokemoncentral.it/Pok%C3%A9mon_Ranger_(gioco)), [ca](https://wiki.pokemoncentral.it/Pok%C3%A9mon_Ranger_(classe_allenatore)) e [serie](https://wiki.pokemoncentral.it/Pok%C3%A9mon_Ranger_(serie_Ranger)). Forse essendo tre si può pensare di lasciare i suffissi a tutte e tre e mettere la pagina "Pokémon Ranger" come disambiguazione.

**Comment by CiaobyDany** [comment]
@davla Direi di sì

**Comment by CiaobyDany** [comment]
@flavio-a In effetti questa soluzione è più intelligente. Never mind.

**Comment by davla** [comment]
Quindi, per Ranger si lascia come è. Le altre le ho sistemate.
Va da sé che il template `tc` serva comunque, quindi non lo sostituisco. A meno che non vogliare fare i precisini e farmi dannare a sostituire solo le chiamate alle classi allenatore a cui è stato tolto il suffisso.

EDIT:
Potrei anche argomentare con: "Vai a sapere se in un gioco nuovo dovessero mettere l'abilità "Podista", poi vanno cambiati tutti i link ed è un macello"

**Comment by davla** [comment]
Gruppi uova: 7 su 16 richiedono il suffisso. Quasi la metà. Io sarei per lasciarlo a tutti.
Uno dei 7 è "Campo", che attualmente rimanda alla meccanica di gioco (https://wiki.pokemoncentral.it/Campo). Se anche dovessimo aggiungere un suffisso *(meccanica)* a quest'ultima, resterebbero comunque 6 su 16 pagine a necessitare il suffisso *(gruppo uova)*, che per me giustifica il lasciarlo a tutte.

**Comment by lucas992x** [comment]
@davla Concordo, con i gruppi uova lo lascerei.

**Comment by davla** [comment]
Same for Tipi GCC: 5 su 11 richiedono suffisso.
@lucas992 Non è che la tua opinione non conti, ma voglio un altro consenso prima di decidere.

**Comment by davla** [comment]
La questione di Drake dei superquattro credo sia stata già risolta. Si lascia il disambigua, no? Non mi pare che uno dei superquattro in cinque giochi della serie principale sia più importante del personaggio dell'anime, o vice-versa.

**Comment by flavio-a** [comment]
Gruppi uova e Tipi GCC non li sposterei neanch'io con così tanti conflitti.

**Comment by davla** [comment]
Una delle più grandi soddisfazioni della mia vita
