### ISSUE TITLE
Update al TrainerPoké

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#44]
## Descrizione 
Il [Template:TrainerPoké](https://wiki.pokemoncentral.it/Template:TrainerPok%C3%A9) è da rendere mobile-friendly, ma come al solito se non lo scrivo qui me ne scordo.

**Comment by lucas992x** [comment]
Ho notato che _Allenatore#Pokémon_ rimanda alla giusta sezione di pagina solo se il nome è singolo, non funziona con quelli che si sono evoluti (e che quindi hanno le forme evolutive precedenti scritte per esteso). Se riesci a sistemare anche questa cosa sarebbe ottimo.

**Comment by davla** [comment]
Ho l'impressione che non sia facile per niente. Mi puoi spiegare meglio, magari con un esempio?

**Comment by lucas992x** [comment]
https://wiki.pokemoncentral.it/Ash_Ketchum#Cobalion rimanda correttamente alla sezione della pagina, mentre https://wiki.pokemoncentral.it/Ash_Ketchum#Butterfree non rimanda al Pokémon che trovi subito sotto Cobalion. Forse è solo un problema di _anchor_ mancante o usato male, non ho ancora guardato per bene il codice del template, ma l'ho scritto per non dimenticarlo.

**Comment by davla** [comment]
Sì, è l'anchor che viene fatto sullo stesso testo visualizzato, ossia tutta la catena evolutiva con tanto di freccine. Quindi il testo dopo # deve essere esattamente quello.

**Comment by lucas992x** [comment]
@davla Io però avevo provato anche a metterci quel testo e non funzionava. Potete fare una prova anche voi?

**Comment by davla** [comment]
Eh, non cagarlo a mano nell'URL. Probabilmente MediaWiki mette una pezza sulle freccine, che non sono esattamentissimamente URL friendly. La cosa migliore sarebbe un parametro per specificare l'anchor, ma poi va usato l'anchor giusto in tutti i template che generano il link. È una questione spinosa.

**Comment by lucas992x** [comment]
@davla Si potrebbe mettere un parametro facoltativo per l'_anchor_ che di default sia uguale al nome, in modo da non sminchiare nulla né dover correggere ogni singola pagina. Basterebbe sistemare i pochi casi in cui ci sono le frecce o altri caratteri strani.

**Comment by davla** [comment]
Però poi devi correggere gli usi dell'anchor. Tipo, un link a `Ash_Ketchum#Metapod` va trasformato in `Ash_ketchum#Butterfree`

**Comment by Cruifer** [comment]
Allora, ho sentito Ale e per renderlo mobile friendly si è deciso di farlo seguendo lo stile di #26, vedi [sandbox](https://wiki.pokemoncentral.it/Utente:Cruifer/Sandbox/2#Template:TrainerPok.C3.A9). A parte il discorso tecnico sull' `anchor` di cui ci ho capito molto poco, è emerso un problema. La scritta che riguarda le mosse prima veniva mandata a capo con degli spazi, col nuovo template però non funziona. (per intendersi la scritta in fondo)

**Prima**
![immagine](https://user-images.githubusercontent.com/38588039/44931774-13c75c00-ad63-11e8-8b9a-a199bdc88715.png)

**Dopo**
![immagine](https://user-images.githubusercontent.com/38588039/44931759-0a3df400-ad63-11e8-897b-f1e66b1d9bd2.png)

Qualcuno ha idea del perché? Invoco @lucas992, visto che ha lavorato al template simile e magari ha riscontrato problemi simili (credici)

**Comment by CiaobyDany** [comment]
Ho aggiunto il link al template in questione nel primo messaggio per rendere più comoda la navigazione.
Non va a capo perché il doppio a capo funziona solo se sei in testo aperto e crea automaticamente i due `<p>`. In un `<div>` i `<p> `non sono creati perché sei già in un div, e quindi i doppi a capo non funzionano. Come questo si risolva non saprei, ho già provato a mettere un `<p>` dentro al div, ma non funziona perché include tutto dentro allo stesso `<p>` e quindi non prende ugualmente l'a capo (prima ancora andando alla cieca avevo provato a mettere uno span e non aveva funzionato ugualmente).

**Comment by lucas992x** [comment]
Con il [template mossa improvvisata](https://wiki.pokemoncentral.it/Template:Mossa_improvvisata) la situazione era un pochino diversa perché c'erano sempre 3 etichette (debutto, partner e mosse), quindi l'altezza era simile all'immagine: per gestire il tutto avevo messo le 3 etichette dentro a un `div` unico, ciascuna dentro al proprio `div` in modo da farle andare a capo.
Qui cambia perché potrebbe esserci il solo debutto oppure più cose, quindi stavo pensando a un layout che da desktop potesse gestire bene la cosa (da mobile il problema non si pone dovendo impilare tutti gli elementi). Forse si possono affiancare i doppiatori connazionali invece di andare a capo dopo ognuno, in modo da sfruttare meglio lo spazio.

Domanda: è così frequente il caso in cui ci sono più di 3/4 doppiatori in totale?

**Comment by lucas992x** [comment]
Ho rapidamente riciclato il template delle mosse improvvisate, provatelo e vedete se vi sembra buono (l'ho messo nella stessa sandbox in una sezione separata per comodità).

**Comment by Cruifer** [comment]
@CiaobyDany sì, immaginavo fosse un probelma del genere. Non mettere in assoluto il div potrebbe risolvere il problema? Anche se immagino di no perché è comunque dentro al div grande.

@lucas992 ho sentito Ale per il layout e boh preferisce quello di prima. E il punto è che comunque non risolve il problema della scritta. Ah, l'anchor che hai messo in cima al tuo layout risolve il problema di cui avevate discusso tu e dedalo?

**Comment by lucas992x** [comment]
Con la mia soluzione andare due volte a capo funziona esattamente come ti aspetteresti dal wikicode, ossia iniziando un nuovo paragrafo, come succedeva prima. Ecco un esempio: 
![scr](https://user-images.githubusercontent.com/38510975/44945602-1bcbde00-aded-11e8-81d7-c0a2d06120c0.png)
Per quanto riguarda l'_anchor_, al momento ho messo un parametro facoltativo per correggerlo se dovesse servire. Ora che ci penso però, forse è il caso di metterne anche più di uno, in modo che per esempio funzionino sia `Ash Ketchum#Metapod` che `Ash Ketchum#Butterfree`.

**Comment by Cruifer** [comment]
Però questa cosa è strana, perché ad esempio:
![439635294_10956237030348245147](https://user-images.githubusercontent.com/38588039/44945694-4ae34f00-adef-11e8-9714-5b6fb5ef64a1.jpg)

![446622078_5543068337676677680](https://user-images.githubusercontent.com/38588039/44945695-4e76d600-adef-11e8-8342-4f4df9220a51.jpg)

**Comment by lucas992x** [comment]
Ho messo la descrizione direttamente fuori dal `flex`, che tanto non le serve visto che occupa sempre l'intera larghezza, e ora dovrebbe funzionare sempre.

**Comment by Cruifer** [comment]
uh, sì ora funzia sempre. Riferisco a Frænky.

**Comment by lucas992** [comment]
Prova (ignorate questo commento)

**Comment by CiaobyDany** [comment]
@lucas992 No, non lo ignoro. Problemi?

**Comment by lucas992x** [comment]
Tanto l'avevo già cancellato ancora prima che tu rispondessi :P
