### ISSUE TITLE
Modulo:Stats sbaglia su Shedinja

### ISSUE THREAD

**Issue by flavio-a** [pokemoncentral/wiki-project#45]
## Descrizione
Il modulo Stats, quando usato su Shedinja, mostra erroneamente come limite max e min dei PS i valori ottenuti con la formula normale, mentre Shedinja ha sempre 1 PS.

## Pagine affette
- https://wiki.pokemoncentral.it/Shedinja#Statistiche

**Comment by davla** [comment]
Me ne ero scordato. @pokemoncentral/wiki qualcuno sa di casi analoghi? Mi pare non ce ne siano.

**Comment by CiaobyDany** [comment]
@davla Ringraziando il cielo c'è solo lui che ha statistiche a cazzo e mi sembra più che sufficiente. Ma sicuramente nell'ottava generazione GF compenserà

**Comment by davla** [comment]
Sono fiducioso. Implemento con un simpatico `if`.
