### ISSUE TITLE
Cosa fare con l'elenco Pokémon per strumento tenuto

### ISSUE THREAD

**Issue by CiaobyDany** [pokemoncentral/wiki-project#47]
## Descrizione
Abbiamo trovato un compromesso sul layout che accontenta quasi tutti, ma non abbiamo comunque risolto i problemi che affliggono la pagina. In particolare mi riferisco al superamento del limite di template da parte dell'elenco. Intanto quello che dovrebbe diventare il nuovo template di base è [questo](https://wiki.pokemoncentral.it/Utente:CiaobyDany/sandbox2), mentre la pagina con l'elenco temporaneo è [questa](https://wiki.pokemoncentral.it/Utente:CiaobyDany/sandbox3).

## Risoluzione del problema
Sostanzialmente abbiamo tre opzioni:
-Qualcuno fa una magia per cui improvvisamente il limite di template non viene più triggerato.
-Spezziamo la pagina per ogni generazione di Pokémon.
-Spezziamo la pagina per ogni generazione di giochi.
Avevo già discusso la questione in chat, ma la riprendo brevemente qui. Spezzare la pagina per generazione di Pokémon consente di vedere nell'arco delle generazioni quali strumenti gli sono stati assegnati indipendentemente dalla sua presenza o meno nei giochi allo stato selvatico. Questa informazione non è presente nelle pagine dei singoli Pokémon che mostrano (giustamente) solo gli strumenti che possono effettivamente tenere. Esempio: Butterfree e Beedrill che tengono lo stesso strumento da Rubino e Zaffiro (dove non erano nemmeno presenti) fino a Ultrasole e Ultraluna. Spezzare la pagina per generazione di giochi consente di avere pagine complete riguardanti ogni gioco (NB: in questo caso mi rifiuto di lasciare il layout da 1 Pokémon per riga perché sarebbe immensamente vuoto e ricorrerei ad un width-xl-25 width-md-33 width-sm-50 width-xs-100 o qualcosa di simile).

Decidete come fare e vediamo di metterlo nel #LastMonthOnPCW di settembre.

**Comment by Cruifer** [comment]
Modulizzare la pagina aiuterebbe in qualche modo a superare il problema dei template?

**Comment by CiaobyDany** [comment]
Parrebbe di sì, ma non è una cosa certa. E in ogni caso bisognerebbe trovare qualcuno disposto a farlo, ma Flavio sicuramente è impegnato in altro e Maze non so cosa stia facendo in questo periodo, quindi ce lo dirà lui. In ogni caso come per qualsiasi altro elenco alla fine bisogna vedere se e come spezzarlo quando diventerà troppo lungo.

**Comment by flavio-a** [comment]
Se la modulizziamo il problema del limite di template non si pone più perché non ci sono più template, solo moduli :P
Tornando seri, modulizzare funzionerebbe perché si può trasformare la pagina in un'unica chiamata ad un modulo (molto complessa, ma sempre una). La proposta di Maze di usare un modulo dati sarebbe una bella cosa, ma il problema è che questo modulo dati è da fare. L'altra possibilità è di passare i dati e usare il render, una cosa tipo i movelist per intenderci ([esempio](https://wiki.pokemoncentral.it/index.php?title=Baldeali&action=edit&section=3)). Maze mi ucciderà per questa seconda soluzione, però ha il vantaggio che si mette su facilmente, praticamente copio il template in un modulo e abbiamo finito.
Prima di muovermi però aspetterei di sentire se @davla ha altre idee.

**Comment by CiaobyDany** [comment]
Il render mi ispira di più sinceramente perché poi almeno può gestirla in autonomia Lugia mentre il modulo non lo può toccare.

**Comment by davla** [comment]
Il render mi fa schifo, è la mia creazione di cui mi vergogno di più.

Ma se dici che Lugia deve fare cose, immagino che i dati non siano tutti pronti, quindi il modulo dati non si può fare. A meno che Lugia non sia abbastanza sveglio da saper ricopiare la sintassi avendo esempi a disposizione, e mi pare di sì. Ma se preferite la soluzione render-based, e se Flavìo si occupa del tutto (non voglio vedere quell'aborto), a me va bene.

Io in ogni caso sto scrivendo una Master Thesis al momento, LOL

**Comment by CiaobyDany** [comment]
Potrebbe lavorare alla parte dei dati del modulo in una sandbox locale e
poi passarla per l'upload. In realtà il 99% è già pronto, però
periodicamente sbucano casi strani per cui bisogna rimetterci le mani,
soprattutto per gli esemplari di cui è presente una sola specie con
incontro overworld in cui non è chiaro se lo strumento sia tenuto per
l'evento o perché tutti i selvatici sono programmati per tenerlo. Tuttavia
non credo che sia un'eventualità che accade troppo spesso, quindi si
faranno le correzioni a mano credo.

**Comment by flavio-a** [comment]
So che odi il render ma a me non sembra male come idea. Comunque anche secondo me è un problema usare un modulo dati perché dopo Lugia149 non può modificarlo, e sicuramente ci vuole più tempo a mettere su il modulo dati che il render.

Poi niente ci vieta in futuro di aggiungere il modulo dati in questione.

**Comment by davla** [comment]
@flavio-a Fintantoché lo fai tu, a me sta bene tutto

**Comment by flavio-a** [comment]
Ho provato a fare un modulo per sostituire il template da chiamare con il render ma è sorto un imprevisto: all'interno del render non si può usare una chiamata ad un template/modulo come valore di un parametro. Questo non vuol dire che non si riesca a fare, ma il tutto diventa più impegnativo da realizzare, quindi sto riprendendo in considerazione l'ipotesi di un modulo dati.

**Comment by flavio-a** [comment]
Ok, dopo un po' di lavoro dovrei aver fatto il modulo dati (oltre al modulo per stampare l'elenco. Risultato: https://wiki.pokemoncentral.it/Utente:Ff300/sandbox
Questo è esattamente l'output del modulo, quindi quello che si vedrà nella pagina se lo vogliamo usare. Dovrebbe essere perfettamente identico alla vecchia sandbox di Dany, ma ovviamente non posso escludere errori nella creazione (automatizzata) del modulo dati (nonostante le mie ricerche, sia a mano che automatiche, non abbiano rilevato niente). Avverto anche Lugia149, ma se vi piace direi che si può usare (essendo un unica chiamata ad un modulo non avrà i problemi di limite dei template).

**Comment by lucas992x** [comment]
@flavio-a Un paio di osservazioni:
- La pagina è piuttosto pesante, valuterei uno split.
- Esiste la classe black-text, che si può usare per "semplificare" qualcosa.
- Per i Colorabbrev, proverei ad aggiungere uno spazietto prima e dopo, invece di lasciarli tutti così attaccati.

**Comment by CiaobyDany** [comment]
@lucas992 Veramente il modulo era stato creato per evitare di splittare ^^"
A parte questo, mi sembra ok, ma bisognerebbe cambiare il nome delle forme in tutte le forme per chi ne ha una con le eccezioni delle forme di Alola e di Basculin credo, ma ti darò conferma in seguito

**Comment by flavio-a** [comment]
@lucas992 prima di valutare la pesantezza aspetterei di usare davvero il modulo, visto che non ho idea dell'impatto sulle performance (al momento il sorgente sono infinite righe di codice generate dall'esecuzione del modulo sulla mia macchina). La classe `black-text` è una buona idea, più tardi vedo se/quanto semplifica le cose. Lo spazio tra le abbrev vedo quanto si riesce a fare comodamente, se no mi sa che faremo senza.
@CiaobyDany aspetto tue notizie

**Comment by flavio-a** [comment]
Ho messo il modulo nella pagina, a me non sembra troppo pesante una volta che il browser a cachato i MS. Non è leggera, per carità, ma mi sembra ragionevole. Il `black-text` verrà implementato in un prossimo update del modulo, insieme ad eventuali altre modifiche (es: quella di aggiungere gli spazi o per le forme alternative).

**Comment by lucas992x** [comment]
Noto che in alcuni casi i giochi vengono mostrati in ordine crescente di percentuale e non secondo l'ordine canonico di uscita dei giochi stessi. Secondo me avrebbe più senso il secondo dei due. Guardate per esempio Growlithe e Arcanine, dove RFVF viene prima di RZS e N2B2 prima di NB.
Sempre in Growlithe e Arcanine OAC sono ripetuti due volte. Non so se si tratti di un errore o di qualcosa che ha un suo senso, in tal caso questo senso andrebbe spiegato.

In linea generale comunque mi sembra buono!

**Comment by flavio-a** [comment]
@lucas992 L'ho fatto apposta perché era così nella sandbox di Dany, però in effetti anch'io preferisco l'altro

**Comment by flavio-a** [comment]
Aggiornamento: ho sentito VeeTamer/Lugia149 sui due dubbi che erano rimasti aperti.
- bisognerebbe cambiare il nome delle forme in tutte le forme per chi ne ha una con le eccezioni delle forme di Alola e di Basculin? (es: Castform ha scritto sotto Forma Castform e non tutte le forme)
> Se vuoi il mio parere, puoi anche mettere il "tutte le forme" ma credo che non sia così necessario perché lo si deduce da sé.
Specialmente per Pokémon tipo castform/shaymin. Oddio magari potrebbe avere senso per Pokémon come flabébé o unown che si trovano in forma diversa senza che debbano esserci delle condizioni particolari però... imho vale quello che ho detto su. Cioè più che altro immagino che richieda anche tempo questa cosa e non ci vedo questa enorme utilità
- era uscita la proposta di ordinare prima per nome e poi per percentuale , mentre adesso è al contrario (es: Arcanine che ha prima la bacca al 50% in RFVF e poi quella al 100% in RZS perché 50% viene prima di 100%)
> Mmm per me stanno melgio ordinate per percentuale. Per nome mi sembra che diventi più un caos, ma non mi sento di giudicare

Il tutte le forme ci può stare, appena finisco i movelist per LGPE guardo se il modo facile che ho pensato per farlo funziona. L'ordinamento per percentuale/per gioco a me non cambia molto, faremo una votazione appena c'è tempo.

**Comment by lucas992x** [comment]
Io resto dell'idea che la cosa migliore sia dividerli per gioco e se all'interno di quel gruppo di giochi ci sono più strumenti ordinarli per percentuale decrescente.

**Comment by flavio-a** [comment]
Non ho idea di quale fosse questo modo facile, il meglio che so fare con poca fatica è non scrivere niente se è l'unica forma (mi sembra un buon compromesso risultato/sbatti).
Sull'ordine sentiamo il parere degli altri @davla @Cruifer @CiaobyDany, io personalmente preferisco per gioco.

**Comment by CiaobyDany** [comment]
@flavio-a Onestamente mi è indifferente la cosa. Ho dei dubbi sul se l'ordine che volete voi possa essere impostato in automatico o se vada gestito manualmente. Nel secondo caso io vi assicuro che mi rifiuto di toccarlo, se avete voglia di sistemare voi ben venga.

**Comment by flavio-a** [comment]
In effetti avevo dato per scontato che si riuscisse facilmente, ma per come ho fatto il modulo dati (mannaggia a me) non è così immediato. Per carità, si fa se proprio serve, però in effetti sarebbe meglio non farlo. Quanto è importante questa cosa?

**Comment by flavio-a** [comment]
https://wiki.pokemoncentral.it/Utente:Ff300/sandbox
ecco, questa dovrebbe essere la versione definitiva (raggruppata per gioco e con nessuna etichetta se c'è una sola forma). Vorrei far notare Gourgeist, in cui le altre forme sono raggruppate invece di avere una entry a testa. Se me lo approvate lo metto online.

**Comment by lucas992x** [comment]
Considerazioni:
- Se un Pokémon (o una forma) non tiene nessuno strumento in nessun gioco lo toglierei proprio dall'elenco (per non allungarlo inutilmente), magari specificando brevemente a inizio pagina che gli assenti mancano per questo.
- Per i giochi in cui lo strumento è assente, metterei prima e dopo il `colorabbrev` un `&nbsp;`, in modo che occupi lo stesso spazio del `blackabbrev`, come già fatto per esempio nella pagina delle [Comparse massicce](https://wiki.pokemoncentral.it/Comparse_massicce) (nei due screen a seguire ci sono l'attuale e la mia proposta).
![scr1_cr](https://user-images.githubusercontent.com/38510975/50383669-04c13c80-06b9-11e9-93e7-144507237a6d.png)
![scr2_cr](https://user-images.githubusercontent.com/38510975/50383670-04c13c80-06b9-11e9-9d1f-9d9aed22404c.png)
- Non mi convince il fatto di mettere su una sola riga anche i Pokémon "stretti" che ptrebbero saìtare anche in 4-5 per riga da desktop, ma riconosco che è una cosa complicata da fare, quindi se non vi vengono in mente soluzioni rapide ignorate pure questo punto.

**Comment by flavio-a** [comment]
> Per i giochi in cui lo strumento è assente, metterei prima e dopo il colorabbrev un &nbsp;, in modo che occupi lo stesso spazio del blackabbrev, come già fatto per esempio nella pagina delle Comparse massicce (nei due screen a seguire ci sono l'attuale e la mia proposta).

Questa l'avevi già detta e io l'avevo approvata, però poi me l'ero scordata. Per la prima a me sembra sensato, ma capisco anche perché si vogliano mettere tutti i Pokémon quindi mi è indifferente, sentiamo gli altri. Per l'ultima o mi sganci il codice o non si fa niente (anche perché la grafica è di Dany, io l'ho solo messa in un modulo).

**Comment by CiaobyDany** [comment]
@flavio-a Uhm... Io ero favorevole a mettere più di un Pokémon per riga quando ci stava, ma me l'avevate bocciato anche perché era tecnicamente un bordello. Quanto al saltare i Pokémon che non hanno uno strumento... Uhm, non saprei. Capisco il senso, ma non è mai stato fatto per davvero.

**Comment by flavio-a** [comment]
https://wiki.pokemoncentral.it/Utente:Ff300/sandbox ho messo lo spazio intorno ai colorabbrev. Più Pokémon su una riga ce li metto anche subito se mi date l'HTML, a me sembra un bordello farlo ordinato e non lo vedo neanche così necessario, quindi non ci perderò tempo. La cosa di far sparire i Pokémon "vuoti" se mi dite di provare io provo, però come ho già detto mi sembrano ragionevoli entrambe le soluzioni.

**Comment by CiaobyDany** [comment]
@flavio-a Bug: Magby tiene l'elettritore al posto del magmatore

**Comment by CiaobyDany** [comment]
@CiaobyDany A parte questo. Dopo averla rivista con calma effettivamente sono favorevole anche io ad eliminare le righe vuote. Con un layout di questo tipo sono oggettivamente superflue. Quella di mettere più Pokémon su una riga era una mia idea da sempre su cui mi ero impuntato, ma concordo sul fatto che sia oggettivamente difficile se non impossibile da realizzare, quindi eviterei (soprattutto considerando che da mobile apparirà comunque max 1 Pokémon per riga, specie se eliminiamo quelle vuote). Inoltre eliminare le righe vuote risolve anche al 99% il problema di gestione delle forme alternative, visto che chi ha una forma alternativa non tiene strumenti, tranne quelle specificate.

**Comment by CiaobyDany** [comment]
@CiaobyDany Ciò detto, aggiungo che è presente un bug sulla spaziatura dei colorabbrev che mette spazi dove non dovrebbe. Premetto che mi pare una questione trascurabile, ma non avendo idea di come sia gestito non so se sia facile/fattibile sistemarlo oppure no (se ci vuole più di un minuto tralascerei). I Pokémon in cui appare sono: Persian, Mightyena, Shroomish, Numel, Dusclops, Glameow, Purugly, Spoink, Grumpig, Baltoy, Huntail, Electivire, Magmortar, Stunky, Skuntank, Basculin Forma Lineablu.

**Comment by lucas992x** [comment]
@flavio-a non odiarmi ma... la spaziatura andrebbe messa ai singoli giochi e non ai gruppi. In altre parole, ciò che intendevo non era `&nbsp;{{#invoke: colorabbrev | RZS }}&nbsp;` ma `&nbsp;{{#invoke: colorabbrev | Ru }}&nbsp;&nbsp;{{#invoke: colorabbrev | Z }}&nbsp;&nbsp;{{#invoke: colorabbrev | S }}&nbsp;`, e analogamente con gli altri gruppi, perché è così che un `colorabbrev` occupa esattamente la stessa larghezza di un `blackabbrev`.

**Comment by flavio-a** [comment]
>Bug: Magby tiene l'elettritore al posto del magmatore

Era per vedere se eravate attenti '^^ (grazie, fixed).

Per le due cose sul colorabbrev: sono abbastanza sbatti, sicuramente non si fanno cambiando mezza riga, quindi ditemi quanto è davvero importante.

PS: ho tolto le entry "vuote" dalla sandbox.

**Comment by lucas992x** [comment]
Credo di aver capito cosa intendi: in pratica bisognerebbe fare una modifica di questo tipo in tutte le righe che contengono dei `color`?

`{ item = 'Rapidartigli', perc = 5, games = {'DPPt', 'HG', 'SS'}, abbrTypes = {'color', 'color', 'black'} },`
&darr;
`{ item = 'Rapidartigli', perc = 5, games = {'D', 'P', 'Pt', 'HG', 'SS'}, abbrTypes = {'color', 'color', 'color', 'color', 'black'} },`

**Comment by flavio-a** [comment]
Sì, ma comunque non risolverebbe il problema sollevato da Dany, che non si può risolvere sempre con l'operazione inversa perché alcune sigle aggregate non esistono (tipo PPtHGSS)

**Comment by CiaobyDany** [comment]
@flavio-a Ribadisco che se non si può risolvere easy fa niente, sopravviviamo benissimo così, sinceramente non credo che qualcuno se ne accorgerà nemmeno.

**Comment by flavio-a** [comment]
Allora io terrei così, e secondo me si può caricare. Basta aggiungere la riga sui Pokémon che non ci sono nella pagina dell'elenco.

**Comment by flavio-a** [comment]
https://wiki.pokemoncentral.it/Utente:Ff300/sandbox
Approvatemi l'introduzione, in fondo ci aggiungo il template di collegamento e la carico su https://wiki.pokemoncentral.it/Elenco_Pok%C3%A9mon_per_strumento_tenuto. Che voglio chiudere quest'issue.

**Comment by lucas992x** [comment]
Io approvo.

**Comment by flavio-a** [comment]
https://wiki.pokemoncentral.it/Elenco_Pok%C3%A9mon_per_strumento_tenuto_(prima-quarta_generazione) e https://wiki.pokemoncentral.it/Elenco_Pok%C3%A9mon_per_strumento_tenuto_(quinta-sesta_generazione) le cancello? Non dovrebbero esserci link in entrata (nel caso si sostituiscono con quelle all'elenco completo)

**Comment by CiaobyDany** [comment]
@flavio-a Ci sono sicuramente link in entrata ma sono facilmente sostituibili

**Comment by lucas992x** [comment]
@flavio-a Ho appena controllato e quelle due pagine sono prive di link entranti. Le cancelliamo brutalmente o le trasformiamo in redirect? Poi direi che possiamo aggiungerlo al LMOPCW e chiudere la issue.

**Comment by CiaobyDany** [comment]
@lucas992 Actually servirebbero delle introduzioni un po' più dettagliate (vedasi quelle di Bulba) per seconda e quinta generazione almeno, più due righe su Insettocchi. Ho già scritto io un accenno sulle specifiche della prima generazione, ma sarebbe da ampliare.

**Comment by flavio-a** [comment]
Ho controllato con la sostituzione automatica e non ci sono link in entrata alle due pagine. Secondo me non ha senso trasformarle in redirect, chi mai andrà a cercare "Elenco Pokémon per strumento tenuto (prima-quarta generazione)"?

L'introduzione andrà riscritta bene, se domani ho tempo lo faccio.

**Comment by CiaobyDany** [comment]
@flavio-a Non ricordo mai la menata dei redirect. Cosa cambia tra cancellare e trasformare in redirect?

**Comment by flavio-a** [comment]
In effetti non so quali vantaggi reali ci siano a cancellarla piuttosto che trasformarla in redirect. Forse si risparmia qualcosa a livello di spazio su disco? Boh, dovremmo sentire Gika a questo proposito, ma piuttosto scegliamo a caso che almeno lo facciamo prima del prossimo secolo.

**Comment by CiaobyDany** [comment]
@flavio-a Kek. Vai a sentimento tu allora

**Comment by flavio-a** [comment]
@CiaobyDany [sono andato a sentimento](https://wiki.pokemoncentral.it/index.php?title=Elenco_Pok%C3%A9mon_per_strumento_tenuto_(prima-quarta_generazione)&action=edit&redlink=1).

Comunque ho iniziato la traduzione, se nessun altro lo fa a breve finisco ma intanto qua chiudo (giusto in tempo per il LMoPCW)
