### ISSUE TITLE
Infobox con scritte che non seguono gli standard

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#49]
## Descrizione
Come avevo notato un paio di settimane fa, ci sono alcuni infobox in cui le scritte non seguono gli allineamenti standard, ovvero scritte allineate a destra su desktop e centrate su mobile e le label sempre a sinistra.

## Pagine affette
- [x] https://wiki.pokemoncentral.it/Template:ZonaAnimeInfobox
- [x] https://wiki.pokemoncentral.it/Template:EpisodeInfobox
- [x] https://wiki.pokemoncentral.it/Template:ItemInfobox
- [x] https://wiki.pokemoncentral.it/Template:Canzone
- [x] https://wiki.pokemoncentral.it/Template:LibroInfobox
- [x] https://wiki.pokemoncentral.it/Template:MovieInfobox
- [x] https://wiki.pokemoncentral.it/Template:EnergyCardInfobox
- [x] https://wiki.pokemoncentral.it/Template:EnergyCardInfobox/Expansion
- [x] https://wiki.pokemoncentral.it/Aiuto:Manuale_di_stile/Avanzato#flex
- [x] https://wiki.pokemoncentral.it/Template:InfoboxEpCielo

## Risoluzione del problema
- [x] Trovare tutti gli infobox 
- [x] Sistemarli in massa

**Comment by lucas992x** [comment]
Tempo fa avevo proposto di templatizzare gli infobox, ma @CiaobyDany aveva risposto con un secco no che non ne valeva la pena perché andrebbe templatizzata la singola riga e quest'ultima si scrive con due righe di codice. Questa issue mi ci ha fatto ripensare, e sono ancora dell'idea che non sarebbe male farlo, in modo da avere sempre uniformità e poter gestire facilmente tutti gli infobox.

**Comment by CiaobyDany** [comment]
Ribadisco il no alla luce dei problemi sul limite di inclusione dei template che stanno apparendo fin troppo spesso ultimamente.

**Comment by lucas992x** [comment]
Domanda: se nella pagina includiamo un template che in realtà è composto da 100 template, per la pagina ce ne sono 100 o uno solo?

**Comment by CiaobyDany** [comment]
@lucas992 100. O non avrei problemi con l'elenco strumenti tenuti.

**Comment by lucas992x** [comment]
Altra domanda: questo limite è influenzato anche da come sono fatti template stessi o no? Perché io ho provato a includere 2500 volte `{{colore|...}}` in una pagina e funziona tranquillamente.

**Comment by flavio-a** [comment]
Come fai a sapere che sono proprio 2500 e non 2501? Eh? Li hai contati?

Comunque la verità è che lo sa solo MediaWiki. Puoi provare a cercare nella loro documentazione come contano le inclusioni template e quando si supera il limite, anche se ovviamente ti mancherà il numerino magico scelto da Gika. Tieni anche conto che 2500 template non sono così tanti, su 800 entry basta che ognuna includa altri 3 template e siamo già a 4*8=3200 template. E non ho idea di come vengano conteggiati i moduli (probabilmente non contano come template, ma non lo so davvero).

**Comment by lucas992x** [comment]
@flavio-a so che erano esattamente 2500, basta prendere sempre lo stesso e ripeterlo alternando sapientemente _Ctrl + A_ e _Ctrl + C_ / _Ctrl + V_ ;)
In un Infobox comunque dovrebbero essere al massimo qualche decina, che si può anche ridurre con alcuni accorgimenti. Se no si potrebbe valutare la possibilità di modulizzare.

**Comment by flavio-a** [comment]
Allora, ho letto tutta l'issue e non solo l'ultimo messaggio quindi adesso posso rispondere sul serio.
1 - Se fai _Ctrl + A_ / _Ctrl + C_ / _Ctrl + V_ a ripetizione puoi ottenere solo potenze di 2 quindi è assurdo che tu abbia ottenuto 2500 copie, cvd.
2 - Il limite di inclusione template si verifica nelle pagine degli elenchi, in cui non compaiono gli infobox, quindi il problema non si pone, anche perché come osservato da Luca parliamo di massimo qualche decina di template.
3 - Fosse per me io templatizzerei tutto, quindi il mio parere è chiaramente di sì. Però non conto davvero, io sarei anche per usare dei footer al posto di `|}`
4 - Per ulteriori dettagli sulla questione: https://en.wikipedia.org/wiki/Wikipedia:Template_limits, io non ho sbatti di leggerlo (so già anche troppo di come funziona MediaWiki per i tooltip e per la questione delle categorie)

**Comment by lucas992x** [comment]
@flavio-a Non ho alternato ACVACVACV..., ho usato ACVVVVV per arrivare a 5, poi di nuovo ACVVVVV per arrivare a 25, poi ACVVVV per arrivare a 100, e poi in modo simile fino alla fine, ma questo non è importante, so esattamente che erano 2500.

**Comment by davla** [comment]
Guerra tra matematici.

Anyway, non so quanto WikiCode possa essere sufficientemente flessibile da rendere la templatizzazione degli infobox conveniente. Con altri template engines, per esempio Jinja o simili, non ci penserei due volte. Però magari non ho visto abbastanza infobox da farmi un'idea. Diciamo che si potrebbe provare, ma le mie aspettative restano scarse.

Avrei pensato a fare una classe CSS `.std-infobox`, ma serve al giusto, visto che nel momento in cui vorremo cambiare grafica agli infobox sarà necessario un markup diverso, e quindi i template dovranno essere cambiati uno ad uno.
