### ISSUE TITLE
Categorie e "puntano qui" si aggiornano lentamente

### ISSUE THREAD

**Issue by flavio-a** [pokemoncentral/wiki-project#5]
## Descrizione
Quando una pagina viene modificata aggiungendo una categoria questa appare correttamente in fondo alla stessa, ma nella pagina della categoria non viene aggiunta la nuova pagina. Anche le pagine che vengono create hanno lo stesso problema. `action=purge` o un `null edit` sia sulla pagina che sulla categoria non risolvono il problema.

Allo stesso modo delle categorie, anche i "puntano qui" non si aggiornano in tempi rapidi.

Per pagine modificate molto tempo fa le categorie e i "puntano qui" si sono aggiornati, ma si parla di modifiche vecchie di mesi. Tra gli esempi si trova una modifica del 18 gennaio (tre mesi fa) aggiornata e una del 6 febbraio non aggiornata.

I primi casi di questo problema sono stati segnalati non mi ricordo se autunno 2017 o 2016 (so che è una differenza importante, ma non ricordo). Penso fosse 2016, ma non garantisco.

## Esempi
* https://wiki.pokemoncentral.it/index.php?title=Tipo_Zero&diff=prev&oldid=567727 questa modifica del 18 gennaio ha aggiunto la categoria Pokémon leggendari alla pagina. Più o meno contemporaneamente è stato modificato anche il template:Pokémon leggendari, aggiungendo in tutte le pagine che lo includono un link entrante a Tipo Zero. La pagina adesso appare nella categoria e i entranti link risultano nel suo "puntano qui".
* https://wiki.pokemoncentral.it/Mirai_connection la pagina, creata il 6 febbraio, non risulta in nessuna delle due categorie che contiene. Inoltre i suoi "puntano qui" non contengono le pagine che includono il template:Sigle d'apertura giapponesi
* https://wiki.pokemoncentral.it/Under_The_Alolan_Moon la pagina, creata il 14 aprile, non è stata aggiunta alle sue due categorie e non contiene nessun link entrante, né quelli dovuti al template:Sigle inglesi né quelli diretti ([da qui, per esempio](https://wiki.pokemoncentral.it/Perch%C3%A9_qui_ad_Alola_puoi#Versione_inglese))

## Risoluzione del problema
Non ho idea di quale sia veramente il problema, ma la presenza di un fattore tempo mi fa sospettare che sia un qualche tipo di cache. Potrebbe anche essere colpa della jobqueue di Mediawiki, ma non ho indagato troppo a fondo.

**Comment by mexicat** [comment]
Cercando un po' in giro, sembra sia un problema del sistema di job queue che non si popola correttamente dopo le modifiche alle categorie. Intanto provo con lo script di manutenzione per ricostruire tutto; al massimo posso pensare di aggiungere un cron job settimanale o giù di lì per fare questa operazione in automatico (tenendo conto che dura comunque qualche ora). Intanto vediamo se dopo questo giro le categorie si sistemano.

**Comment by mexicat** [comment]
Non sembra che l'operazione abbia funzionato; probabilmente a database i collegamenti sono corretti ma per qualche motivo la cache di render delle pagine categoria non viene svuotata come dovrebbe. Devo investigare ulteriormente.

**Comment by lucas992x** [comment]
@mexicat Il template Mart era usato solo in una pagina, Casinò di Rupepoli; ho editato la pagina in questione sabato 21/4 alle 17:36, all'inizio risultava ancora nell'elenco Puntano Qui, oggi lunedì 23/4 alle 12 non c'è più. C'è di mezzo uno svuotamento della cache o ha fatto tutto da solo?

**Comment by mexicat** [comment]
@lucas992 non so, ma la cache dei “puntano qui”, in quanto pagina speciale, non viene gestita allo stesso delle pagine dei namespace di contenuti, quindi non credo sia un evento correlato.

**Comment by flavio-a** [comment]
Non si può interrogare direttamente il database per vedere se è aggiornato? Le tabelle dovrebbero essere
https://www.mediawiki.org/wiki/Manual:Categorylinks_table
https://www.mediawiki.org/wiki/Manual:Pagelinks_table
(non ho conferme sul funzionamento, ho solo immaginato che utilizzino queste due tabelle per popolare le pagine)

Comunque nelle due pagine d'esempio i "puntano qui" si sono aggiornati (ma non le categorie).

**Comment by flavio-a** [comment]
Dopo aver corretto alcune pagine a mano, oggi ho utilizzato una sostituzione automatica per togliere il template sup. La cosa strana è che le pagine aggiornate a mano sono ancora tra i puntano qui del template (nonostante non lo includano più, sono sicuro), mentre quelle aggiornate con la sostituzione automatica sono sparite. Non so quanto possa essere rilevante, ma nel dubbio lo scrivo.

EDIT: altri esempi confermano che le sostituzioni automatiche fanno apparire/sparire una pagina dalle categorie. Continuo a non avere idea del motivo.

**Comment by flavio-a** [comment]
News di agosto:
parlando con il webmaster di WikDex (wiki spagnolo) sono venuti fuori un po' di spunti interessanti sulla questione:
- da mobile anche gli iinterwiki non si aggiornano, per esempio in Home non c'è lo spagnolo ma c'è ancora il polacco. La pagina degli interwiki da mobile viene generata con una query all'API di MediaWiki ([questa](https://m.wiki.pokemoncentral.it/api.php?action=query&format=json&meta=siteinfo&siprop=general&prop=langlinks&lllimit=max&titles=Home&formatversion=2&llprop=url%7Cautonym%7Clangname&llinlanguagecode=it&format=jsonfm)) che per qualche motivo ha il risultato sbagliato. Mia ipotesi: la query è cachata.
- [Questa query](https://wiki.pokemoncentral.it/Speciale:ApiSandbox#action=query&format=json&prop=categories&titles=Aggron) ha il risultato sbagliato: tra le categorie compare infatti "Pagine con errori di script" (e [Aggron](https://wiki.pokemoncentral.it/Aggron) appare nella [categoria](https://wiki.pokemoncentral.it/Categoria:Pagine_con_errori_di_script)), ma in fondo alla pagina stessa non c'è traccia di questa categoria, e giustamente dato che la pagina non ha errori di script. Questa cosa mi ha stupito perché non mi aspettavo che quella query fosse cachata.

La domanda che mi pongo adesso è: le query sono sbagliate perché è sbagliato il db o almeno quello giusto e il risultato è sbagliato per colpa della cache? (Io propendo per la seconda perché rebuildall non ha avuto effetto) L'unico modo per controllare è quello di chiedere direttamente al db, cosa che può fare solo @mexicat. Confermo che le tabelle sono
>https://www.mediawiki.org/wiki/Manual:Categorylinks_table
https://www.mediawiki.org/wiki/Manual:Pagelinks_table

con in più la nuova https://www.mediawiki.org/wiki/Manual:Langlinks_table per gli interwiki.

**Comment by flavio-a** [comment]
Vediamo se così funziona:
@mexicat devi copiare le seguenti query e scriverci il risultato.

Questa prima query serve solo a controllare che l'id di Aggron che ho trovato sia giusto (dovrebbe essere 12932)
```sql
SELECT p.page_id AS "page_id",
FROM page p
WHERE p.page_title = 'Aggron'
```

Questa query testa le categorie
```sql
SELECT cl.cl_to
FROM categorylinks cl
WHERE cl.cl_from = 12932
```

Questa gli interwiki della home
```sql
SELECT *
FROM langlinks ll
WHERE ll.ll_from = 1
```

Questa i puntano qui (credo)
```sql
SELECT *
FROM pagelinks pl
WHERE pl.pl_title = 'Per_la_Luna_di_Alola'
```

**Comment by mexicat** [comment]
```sql
SELECT p.page_id
FROM page p
WHERE p.page_title = 'Aggron'
```

> 12932

```sql
SELECT cl.cl_to
FROM categorylinks cl
WHERE cl.cl_from = 12932
```

> Articoli_incompleti
> Pagine_che_richiamano_file_inesistenti
> Pagine_con_errori_di_script
> Pokémon_appartenenti_a_una_linea_di_evoluzione_a_tre_stadi
> Pokémon_con_statistiche_base_totali_di_530
> Pokémon_con_statistiche_base_totali_di_630
> Pokémon_con_una_proporzione_sessuale_di_un_maschio_per_ogni_femmina
> Pokémon_dalla_sagoma_n._06
> Pokémon_di_colore_Grigio
> Pokémon_di_doppio_tipo
> Pokémon_di_gruppo_uova_Mostro
> Pokémon_di_terza_generazione
> Pokémon_di_tipo_Roccia
> Pokémon_di_tipo_rcciaio
> Pokémon_nel_gruppo_di_esperienza_Lento
> Pokémon_originari_della_regione_di_Hoenn
> Pokémon_originari_della_regione_di_Unima
> Pokémon_un_totale_massimo_di_17_stelle_prestazione

```sql
SELECT *
FROM langlinks ll
WHERE ll.ll_from = 1
```

> 1	de	Hauptseite
> 1	en	Main Page
> 1	fr	Accueil
> 1	ja	メインページ
> 1	pl	Strona główna
> 1	zh	主页

```sql
SELECT *
FROM pagelinks pl
WHERE pl.pl_title = 'Per_la_Luna_di_Alola'
```

> 40495	0	Per_la_Luna_di_Alola	0

**Comment by lucas992x** [comment]
Interessante _Pokémon_di_tipo_rcciaio_.

**Comment by flavio-a** [comment]
No più che altro interessante che le query siano sbagliate. Questo vuol dire che tutto quello che pensavo sulla cache è sbagliato, e la colpa è da un altra parte. Comunque molto strano che __rebuildall.php__ non avesse funzionato all'epoca.

Il fatto dei _Pokémon_di_tipo_rcciaio_ è carino perché è un errore recente, quindi sembra che il database si aggiorni per alcune cose e per altre no. Tra l'altro su buona parte dei Pokémon la categoria _Acciaio_ è a posto, mentre solo alcuni sono ancora in _rcciaio_.

Boh, ci penserò, spero mi venga in mente qualcosa.

**Comment by flavio-a** [comment]
Sembra che con l'aggiornamento di MediaWiki categorie e puntano qui abbiano ripreso a funzionare normalmente. Non sono troppo interessato a capire cosa fosse successo davvero prima, ma se mai dovesse ricapitare un problema del genere voglio avvisare chiunque ci lavorerà in futuro che secondo me è stato un problema di job queue che non si popolava correttamente, anche se non mi spiego come mai `rebuildall.php` non avesse funzionato. O magari aveva funzionato a DB, ma la cache impediva di vedere subito queste modifiche sul Wiki.
Intanto chiudo.
