### ISSUE TITLE
Update al GlitchPkmnInfobox

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#52]
## Descrizione
Sono due anni che ho quel [coso](https://wiki.pokemoncentral.it/Template:GlitchPkmnInfobox) in [sandbox](https://wiki.pokemoncentral.it/Utente:Cruifer/Sandbox), direi che è il momento di aggiornarlo seriamente. È da rendere mobile friendly l'ultima parte e sistemare un po' la grafica, e dovrebbe essere quasi finito.

**Comment by lucas992x** [comment]
@Cruifer Io aspetterei, in attesa di capire se si deciderà di templatizzare gli Infobox o no.

**Comment by CiaobyDany** [comment]
@lucas992 Se l'idea è come credo di fare un infobox simile al PokémonInfo non credo siano correlate. A meno che non vogliate rifare pure il PokémonInfo, cosa che vi sconsiglio altamente.
