### ISSUE TITLE
Delineare degli standard per categorie di template 

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#53]
## Descrizione
Ok, sappiamo tutti che sulla wiki abbiamo molti template che non seguono standard comuni sia strutturalmente (vedi #49) che graficamente (#41). Direi che dovremmo discutere almeno se gli standard che abbiamo attualmente vanno bene e sistemare i vari template di conseguenza. Si potrebbe anche pensare di mettere gli standard nel manuale di stile, in effetti. Poi consiglio di continuare qui la discussione sul templatizzare le righe degli infobox, che altrimenti resta persa nel dimenticatoio.

**Comment by lucas992x** [comment]
Io rimango dell'idea di templatizzare gli infobox. Si tratta di aggiungere solo qualche decina di template ad una pagina (nei casi peggiori), e le pagine che superano il limite consentito non contengono infobox (o almeno a me non risulta).

**Comment by Cruifer** [comment]
Boh dai, io non sono molto convinto però magari si può fare una prova e vedere come va.

**Comment by lucas992x** [comment]
Una categoria di template non ancora aggiornata e relativamente facile da fare è quella dei template di navigazione dei Capipalestra e simili. Per questo tipo di template, potremmo usare il layout del [template Starter](https://wiki.pokemoncentral.it/Template:Pok%C3%A9mon_Starter) oppure quello del [template dei Capitani e Kahuna](https://wiki.pokemoncentral.it/Template:Capitani_e_Kahuna_di_Alola) (occhio però che quest'ultimo nonostante le apparenze ha bisogno di qualche sistemata, per ora guardiamo solo l'estetica). In tal caso penso che la scelta migliore sia di fare due template generici, uno per il box grosso e uno per i singoli box interni (per esempio _Template:Allenatori/head_ e _Template:Allenatori/entry_), con il primo che gestisce i secondi utilizzando i `flex` as usual.
L'elenco completo dei template di questo tipo dovrebbe essere il seguente (ovviamente se ho dimenticato qualcosa aggiungetelo):
- https://wiki.pokemoncentral.it/Template:Capipalestra_di_Kanto
- https://wiki.pokemoncentral.it/Template:Capipalestra_di_Johto
- https://wiki.pokemoncentral.it/Template:Capipalestra_di_Hoenn
- https://wiki.pokemoncentral.it/Template:Capipalestra_di_Sinnoh
- https://wiki.pokemoncentral.it/Template:Capipalestra_di_Unima
- https://wiki.pokemoncentral.it/Template:Capipalestra_di_Kalos
- https://wiki.pokemoncentral.it/Template:Capitani_e_Kahuna_di_Alola
- https://wiki.pokemoncentral.it/Template:Capipalestra_dell%27Arcipelago_Orange
- https://wiki.pokemoncentral.it/Template:Assi_Hoenn
- https://wiki.pokemoncentral.it/Template:Assi_del_Parco_Gen_IV
- https://wiki.pokemoncentral.it/Template:Dame_della_Lotta
- https://wiki.pokemoncentral.it/Template:Superquattro_di_Kanto
- https://wiki.pokemoncentral.it/Template:Superquattro_di_Hoenn
- https://wiki.pokemoncentral.it/Template:Superquattro_di_Sinnoh
- https://wiki.pokemoncentral.it/Template:Superquattro_di_Unima
- https://wiki.pokemoncentral.it/Template:Superquattro_di_Kalos
- https://wiki.pokemoncentral.it/Template:Lega_di_Alola

**Comment by Cruifer** [comment]
Allora, la cosa migliore secondo me fra i due è molto meglio il template dei capitani e dei Kahuna di Alola, a patto di togliere i gradienti dei singoli box e di mettere un colore solid. Anche perché il template degli starter non risolve direttamente il problema dei gradienti vicini (anche se è solo un bordo è comunque attaccato al gradiente del box principale). Per il resto ok, mi sembra che due template siano più che sufficienti per questi.

**Comment by lucas992x** [comment]
@Cruifer Per il template starter si potrebbe risolvere facilmente impostando anche il box grosso come un rettangolo con bordo gradientato e interno bianco. EDIT l'ho appena modificato, perché efffettivamente hai ragione a dire che gradienti contro gradienti non va bene.
Anyway, se preferite comunque la seconda opzione, dentro al box mettiamo un colore solid e light con le scritte dark?

**Comment by Cruifer** [comment]
> si potrebbe risolvere facilmente impostando anche il box grosso come un rettangolo con bordo gradientato e interno bianco

too much bianco. Ce n'è già troppo

Per i colori boh, dovremmo provare, appena ho voglia faccio delle prove in sandbox (oppure fai tu se vuoi).

**Comment by lucas992x** [comment]
Allora direi che nei prossimi giorni con comodo scrivo i template, così poi ci facciamo tutti i test del caso, a meno che qualcun altro non abbia delle obiezioni e/o delle altre proposte.

**Comment by Cruifer** [comment]
Ho fatto una bozza di come mi piacerebbe che fosse ([link](https://wiki.pokemoncentral.it/Utente:Cruifer/Sandbox#regioni)). Ditemi che vi sembra. A me piace. Ovviamente è una cosa fatta un po' alla svelta e che non supporta la settima gen (per ora), ma si sistema poi con calma.

**Comment by CiaobyDany** [comment]
@Cruifer Boh, quei riquadri così piani non mi entusiasmano ma non ho idee migliori. Inoltre farei width 25 perché tranne che ad Unima le Palestre sono 8 e almeno ci stanno su due righe senza riporti.

**Comment by lucas992x** [comment]
Come idea generale non mi dispiace, salvo il fatto che metterei di default 25% su schermi grossi. Comunque ho messo la mia proposta nella [mia sandbox](https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate), ho cambiato un po' di parametri per rendere il template più "universale" (visto che non lo useremo solo con i Capipalestra).

**Comment by lucas992x** [comment]
Dimenticavo di aggiungere un paio di cose:
- Per i casi "doppi", come Rocco/Adriano nella Lega di Hoenn, io userei due box distinti in cui aggiungere un `sup` per distinguere i giochi in cui quell'Allenatore ha quel ruolo (c'è l'apposito parametro _only_).
- Per Spighetto+Chicco+Maisello userei 3 box separati specificando con il parametro _notes_ quando ognuno è sfidabile, altrimenti se vogliamo fare un box singolo per tutti e 3 lo gestirei a parte, visto che è un caso unico.

**Comment by Cruifer** [comment]
@lucas992 A me piaceva di più con la medaglia a sinistra, ma comunque va bene anche così. Magari la prossima volta edita direttamente dalla mia sandbox altrimenti non le creo per nulla :P. Per i casi doppi io metterei semplicemente le scritte di ogni tizio di colore diverso, altrimenti con troppi box rischia di essere confusionario

**Comment by lucas992x** [comment]
@Cruifer I casi doppi finora sono solo 3:
- Rocco/Adriano fra i Campioni di Hoenn.
- Aristide/Iris come Capopalestra di Unima (e separarli permetterebbe di avere 12 riquadri quindi layout più OCD).
- Nardo/Iris come Campione di Unima.

Secondo me non è un male separarli, ma se decidiamo di non farlo implementerò nel template anche questa possibilità. Tenete presente che comunque ora hanno un singolo box ma largo il doppio, quindi non cambia poi molto.

**Comment by lucas992x** [comment]
Mi sono accorto ora di avervi mentito, altri due casi doppi sono Koga/Nina e Giovanni/Blu come Capipalestra di Kanto.

**Comment by flavio-a** [comment]
Ci sono anche Adriano/Rodolfo a Hoenn.

**Comment by lucas992x** [comment]
https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate
Qui ho messo tutti i casi doppi per vederli direttamente, secondo me l'idea del box doppio e con colori appropriati anziché singolo colore neutro è la migliore. L'unico che non mi convinceva troppo è Aristide/Iris, ma perché in `md`/`sm` avendone 2 per fila si avrebbe Silvestro e Ciprian da soli sulle rispettive righe: l'unico "rimedio" che mi è venuto in mente è spostare Komor subito dopo Aloé, visto che danno la stessa Medaglia, e lo preferisco. Ditemi se vi piacciono i risultati e se avete qualche obiezione/osservazione/consiglio/altro, secondo me andrebbero bene come soluzione finale.

**Comment by lucas992x** [comment]
Ho aggiornato tutti i template sopra citati con questo nuovo layout.

La prossima categoria che mi viene in mente sono i template delle controparti per regioni (per intenderci, una cosa di [questo tipo](https://wiki.pokemoncentral.it/Template:Edifici_lotta)). Se siete d'accordo userei un layout del genere.
Template di navigazione:
- https://wiki.pokemoncentral.it/Template:Edifici_lotta
- https://wiki.pokemoncentral.it/Template:Centri
- https://wiki.pokemoncentral.it/Template:Campo_magnetico_speciale
- https://wiki.pokemoncentral.it/Template:Cimiteri
- https://wiki.pokemoncentral.it/Template:Roccia_Muschio
- https://wiki.pokemoncentral.it/Template:Roccia_Ghiaccio

Tabelle in pagina:
- https://wiki.pokemoncentral.it/Giudice_Onomastico
- https://wiki.pokemoncentral.it/Cancellamosse
- https://wiki.pokemoncentral.it/Ricordamosse
- https://wiki.pokemoncentral.it/Flash
- https://wiki.pokemoncentral.it/Pensione_Pokémon
- https://wiki.pokemoncentral.it/Affetto#Valutatori_di_affetto (da valutare)

**Comment by lucas992x** [comment]
Ecco la mia proposta: https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate
Pensavo che quasi quasi lo si potrebbe usare anche nelle pagine contenenti tabelle simili, per esempio https://wiki.pokemoncentral.it/Giudice_Onomastico#Localit.C3.A0

**Comment by CiaobyDany** [comment]
@lucas992 Why not?

**Comment by Cruifer** [comment]
@lucas992 c'è anche https://wiki.pokemoncentral.it/Template:Cimiteri

**Comment by lucas992x** [comment]
Aggiunto anche lui, thx.

**Comment by lucas992x** [comment]
Ho editato il commento precedente. Se ci sono altri casi in cui si può usare questo template aggiungeteli, tanto me ne sarò sicuramente dimenticati alcuni.

**Comment by CiaobyDany** [comment]
@lucas992 Le due rocce mi sembrano valide. Cioè, è lo stesso principio dei luoghi con campo magnetico speciale

**Comment by lucas992x** [comment]
Template di navigazione di una determinata regione: la serie principale è aggiornata (e segue uno standard), ma gli spin-off no. Secondo me l'attuale soluzione va bene, solo non mi convince il fatto che il titolo in alto sia del colore della regione mentre tutte le altre etichette sono nere; secondo me è meglio mettere anche il titolo nero (o bianco se il colore di sfondo è scuro).
Se poi decidiamo di templatizzare anche questi box, la soluzione migliore mi sembra di farne uno per il box esterno e uno per i singoli pezzi interni.

Elenco del template di questo tipo:
- https://wiki.pokemoncentral.it/Template:Kanto
- https://wiki.pokemoncentral.it/Template:Johto
- https://wiki.pokemoncentral.it/Template:Hoenn
- https://wiki.pokemoncentral.it/Template:Sinnoh
- https://wiki.pokemoncentral.it/Template:Unima
- https://wiki.pokemoncentral.it/Template:Kalos
- https://wiki.pokemoncentral.it/Template:Alola
- https://wiki.pokemoncentral.it/Template:Auros
- https://wiki.pokemoncentral.it/Template:Settipelago
- https://wiki.pokemoncentral.it/Template:Arcipelago_Orange
- https://wiki.pokemoncentral.it/Template:Isole_Cristalline
- https://wiki.pokemoncentral.it/Template:Fiore
- https://wiki.pokemoncentral.it/Template:Almia
- https://wiki.pokemoncentral.it/Template:Oblivia
- https://wiki.pokemoncentral.it/Template:Zone_PMD
- https://wiki.pokemoncentral.it/Template:Zone_PMD2
- https://wiki.pokemoncentral.it/Template:Zone_PSMD

**Comment by flavio-a** [comment]
Il template:Zone PSMD è bellissimo così come l'avevo fatto a suo tempo, se me lo tocchi ti taglio le mani :).
Scherzi a parte, in quello davvero mi piacerebbe tenere i colori dei vari continenti, però non è indispensabile.

**Comment by lucas992x** [comment]
Ti propongo questa soluzione: etichette colorate in questo modo quando si vogliono differenziare i loro colori. Volendo potremmo anche pensare di usarle negli altri template per far risaltare meglio le varie parti (città, percorsi, etc).
![scr](https://user-images.githubusercontent.com/38510975/46086665-dc549f80-c1a8-11e8-9aa3-f7159c6bc41d.png)

**Comment by flavio-a** [comment]
@lucas992 diciamo che mi posso accontentare. Le tue mani sono salve (per stavolta)

**Comment by lucas992x** [comment]
Stavo riflettendo sulla possibilità di mettere sempre le etichette come nel template PSMD. Non mi convince troppo usarlo dappertutto, fra queste 3 possibilità preferisco quella delle etichette come nello screen qui sopra.

**Comment by lucas992x** [comment]
Ho messo le due prove nella solita pagina: https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate
Per la seconda i colori li ho scelti un po' a caso, se avete idee migliori proponetele.

**Comment by flavio-a** [comment]
Io rimetterei i `text-small` per l'elenco di luoghi e lascerei i link blu invece di neri.

**Comment by lucas992x** [comment]
@flavio-a Fatto, guardate ora se vi convince

**Comment by flavio-a** [comment]
Ok ho mentito, mettiamo il testo di dimensione normale (però preferisco i link blu e non neri).

**Comment by lucas992x** [comment]
Ok, ho rimesso il testo normale senza `small-text` e senza `black-text`. Così vi piace?

**Comment by lucas992x** [comment]
https://wiki.pokemoncentral.it/Megaevoluzione
https://wiki.pokemoncentral.it/Archeorisveglio
https://wiki.pokemoncentral.it/Effetto_Sintonia
https://wiki.pokemoncentral.it/Forma_di_Alola

Tutte queste tabelle sono praticamente identiche, quindi potrebbero essere templatizzate (e sarebbe una buona occasione per aggiornarle graficamente e responsivamente). Che ne dite?

**Comment by Cruifer** [comment]
sembra una buona idea. Avevi intenzione di farlo tu?

**Comment by lucas992x** [comment]
Se qualcuno ha già un'idea può proporla, altrimenti ci penso un po' su.

**Comment by lucas992x** [comment]
https://wiki.pokemoncentral.it/Utente:Lucas992/Sandbox#Prova

**Comment by Cruifer** [comment]
una cosa, sarebbe carino mettere anche le celle delle statistiche colorate (non solo l'header per intendersi). E poi non ho capito cosa è quel gradiente sopra al nome, del rimasuglio di codice? Ultima cosa, forse è più carino mettere lo strumento sotto al nome anche su mobile, tipo come su desktop (non sotto allo sprite, per intendersi non centrato). Ma comunque sono finezze, mi sembra che per il resto vada bene

**Comment by lucas992x** [comment]
- Le celle delle statistiche colorate si fanno facilmente, a questo punto le tolgo direttamente dall'header?
- Quella linea gradientata dovrebbe essere un divisorio per separare in modo più evidente i Pokémon da desktop, verrebbe simile al template `Maps` per intenderci.
![capture _2019-01-09-09-45-57](https://user-images.githubusercontent.com/38510975/50887473-87edcc80-13f3-11e9-8be3-164fb12a2cf7.png)
- La mia intenzione era proprio quella, devo solo capire come fare :D

**Comment by lucas992x** [comment]
Update:
- Ho messo i box colorati alle statistiche, e devo dire che mi piace di più così.
- Dovrei aver fixato la posizione dello strumento, ho verificato che non dia problemi anche su Chrome e Opera oltre a Firefox (ma per sicurezza controllate che anche a voi si veda bene, visto che #CssMerda).
- Per i tipi ho sostituito le etichette precedenti con il modulo `Box` nella seconda riga, e preferisco questa soluzione.

**Comment by lucas992x** [comment]
https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate#Confronto_forme
Mi piacerebbe capire perché alcune immagini sono un pochino spostate, ma per il resto mi sembra tutto ok.

**Comment by CiaobyDany** [comment]
@lucas992 Da quando usiamo gli artwork e non i modelli statici più recenti?

**Comment by lucas992x** [comment]
@CiaobyDany Preferivo gli artwork perché non hanno tutto quel bordo bianco attorno, ma se lo standard sono gli sprite mi adeguo

**Comment by Cruifer** [comment]
@lucas992 Allora, per come è ora dopo le modifiche mi piace. Solo due cose
- quando dici immagine un po' spostate ti riferisci a Groudon?
- ha senso tenere il separatore anche nel primo pkmn in cima? Cioè, a rigor di logica non c'è nulla da separare

**Comment by CiaobyDany** [comment]
@lucas992 In teoria gli standard sono sempre stati gli sprite/modelli statici dell'ultimo gioco uscito. Ma è anche vero che gli standard erano stati decisi nell'era in cui gli sprite erano 50x50px e che la visualizzazione avveniva prevalentemente su desktop e non da mobile. Ti scoccia fare una prova con i modelli statici per confronto?

**Comment by lucas992x** [comment]
@Cruifer MegaVenusaur, MegaBlastoise e ArcheoGroudon sono leggermente spostati verso destra, non capisco il motivo. Il separatore nel primo in effetti si può togliere, dopo provvedo.

@CiaobyDany L'ho appena fatta, refresha ;)

**Comment by flavio-a** [comment]
@lucas992 c'ha ragione il browser, gli hai messo flex-items-center al parent e i figli non occupano tutto lo spazio, quindi lui sposta al centro (e i modelli vengono più a sinistra). Ma io non dovrei rispondere a voi, dovrei studiare

**Comment by CiaobyDany** [comment]
@lucas992 Non riesco a recuperare la versione precedente, ma in compenso da desktop ho visto quell'orrore di div separatore alto tipo un pixel e mezzo con il gradiente dei tipi. O lo fai più alto o lo togli perché così è abbastanza inguardabile

**Comment by lucas992x** [comment]
@CiaobyDany L'ho un po' ingrandito e ora è spesso come il bordo della tabella, va meglio? L'ho anche rimosso dalla prima entry.

**Comment by CiaobyDany** [comment]
@lucas992 Scusa, ma esattamente perché lo vuoi fare diverso il separatore da desktop e da mobile? Non va bene fare la riga di background anche su fisso?

**Comment by lucas992x** [comment]
Per farla dello stesso colore della tabella bisognerebbe mettere il parametro per il colore anche in ogni singola riga. Fattibile sì, ma non c'è una soluzione migliore? Tu cosa proporresti?

**Comment by CiaobyDany** [comment]
@lucas992 Al momento sto lavorando su Xenopedia, ma il layout cards non è estensibile anche su desktop? Basically vorrei quello

**Comment by lucas992x** [comment]
Potrei anche applicare il card layout da desktop, ma poi tutti gli elementi di ogni riga andrebbero allineati a mano con quelli delle altre (perché non ci sarebbe più la tabella a sistemarli automaticamente), non mi sembra un gran cosa.

Comunque qualcuno dovrebbe spiegarmi per quale motivo il modulo `Spr` non prende le dimensioni che gli do, eppure la sintassi dovrebbe essere giusta.

**Comment by flavio-a** [comment]
> Comunque qualcuno dovrebbe spiegarmi per quale motivo il modulo `Spr` non prende le dimensioni che gli do, eppure la sintassi dovrebbe essere giusta.

No, la dimensione è il parametro dopo, devi aggiungere un ` | ` alla chiamata.

Comunque forse si riesce a fare la riga come dice Dany anche da desktop, adesso faccio una prova.

EDIT: non è vero, la tua chiamata era giusta, era colpa del modulo, ho sistemato. Per la cosa che dice Dany ho messo una bozza, lascio a te di sistemare i dettagli che sai come funzionano tutte le parti e (spero) ci perderai meno tempo di me. In breve ho aggiunto una riga alla tabella con sfondo trasparente che sparisce su schermi piccoli, e viene l'effetto desiderato.

**Comment by lucas992x** [comment]
Bravo Flavio, ho affinato il tutto e mi sembra a posto. Oltre allo sprite che non si allinea da desktop, c'è qualcos'altro su cui discutere?

**Comment by flavio-a** [comment]
Fatto anche quello. Ti eri scordato di mettere `flex-item-fill` ai div delle forme, lo avevi messo solo alla forma base.

**Comment by lucas992x** [comment]
@flavio-a Così però il flex-item-fill ha effetto anche da mobile, che non è una cosa voluta

**Comment by lucas992x** [comment]
Adesso dovrebbe essere tutto a posto.

**Comment by Cruifer** [comment]
promemoria per me (o chiunque altro abbia voglia). C'è da aggiornare e standardizzare questi template:

- [x] https://wiki.pokemoncentral.it/Template:Cripto
- [x] https://wiki.pokemoncentral.it/Template:Fondazione_Aether
- [x] https://wiki.pokemoncentral.it/Template:Team_Flare
- [x] https://wiki.pokemoncentral.it/Template:Team_Galassia
- [x] https://wiki.pokemoncentral.it/Template:Team_Idro
- [x] https://wiki.pokemoncentral.it/Template:Team_Magma
- [x] https://wiki.pokemoncentral.it/Template:Team_Pesto_Buio
- [x] https://wiki.pokemoncentral.it/Template:Team_Plasma
- [x] https://wiki.pokemoncentral.it/Template:Team_Rocket
- [x] https://wiki.pokemoncentral.it/Template:Team_Skull

e renderli più o meno simili a [questo](https://wiki.pokemoncentral.it/Template:Team_Rainbow_Rocket)

**Comment by Cruifer** [comment]
Shout-out a Orion e Irene che hanno sistemato quei template. Chiudo.
