### ISSUE TITLE
Template Sprite da aggiornare

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#55]
## Descrizione
Un'immagine vale più di mille parole:
![capture _2018-09-15-14-36-17](https://user-images.githubusercontent.com/38510975/45586328-50fc2400-b8f5-11e8-9052-a3b9617011b3.png)

## Pagine affette
Tutte le pagine dei Pokémon,  visto che il [template Sprite](https://wiki.pokemoncentral.it/Template:Sprite) si usa lì.

## Risoluzione del problema
Una possibilità può essere sostituire le scritte con `Blackabbrev` o `Colorabbrev`, almeno da mobile.

**Comment by CiaobyDany** [comment]
@lucas992 Non basta, devi cambiare il layout in toto, ricorda che tra due mesi avrai la settima generazione con tre modelli frontali e due retro e quelli di LGPE saranno enormi

**Comment by Cruifer** [comment]
ma se accorpassimo questa issue con la #61?

**Comment by flavio-a** [comment]
Secondo me no perché questa cosa è separata dall'aggiornamento per LGPE.

**Comment by lucas992x** [comment]
Se non ci sono particolari motivi per non farlo, comincerei a mettere le mani su questo template.

**Comment by CiaobyDany** [comment]
@lucas992 Scoprire cosa facciamo con i modelli di LGPE è un motivo abbastanza particolare?

**Comment by lucas992x** [comment]
Io in questo template li resizerei, e se uno vuole vedersi il modello in tutta la sua interezza se lo apre. È sbagliata sta cosa?

**Comment by davla** [comment]
Stessa size proibitivamente grossa di sesta e settima generazione. Come ben capite, più grosso da mobile è un problema.

**Comment by lucas992x** [comment]
Ecco l'[idea generale](https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate). I box bianchi contenenti gli sprite non hanno larghezze fissate, sono semplicemente infilati dentro un `flex flex-row flex-wrap flex-items-stretch flex-main-stretch`. Vorrei impostare le larghezze, in modo da evitare che con certe dimensioni si abbia una riga con 5+ sprite e sotto una riga con un singolo sprite, ma ci sono quei 3 cazzo di Pokémon che in seconda generazione hanno alcuni sprite giappi diversi da quelli internazionali (Slowpoke, Jynx, Aipom), e il bello è che ciascuno di loro ha un differente numero di sprite giappi diversi dalla controparte internazionale.
Quindi vorrei un vostro parere sia su questa questione, sia sull'ordine in cui ho deciso di mettere i box (prendete come riferimento Jynx che ha tutti gli sprite cambiati fra Jap e Intl).
Se può interessarvi, Bulba divide in maniera più "netta" i giochi inserendo per ciascuno sia fronte che retro ([esempio](https://bulbapedia.bulbagarden.net/wiki/Jynx_(Pok%C3%A9mon)#Sprites)), ma io sinceramente eviterei visto che il retro è sempre uguale all'interno di una stessa generazione.

**Comment by CiaobyDany** [comment]
@lucas992 Tralasciando il fatto che apparentemente l'artwork di Deoxys è buggato e non saprei come interpretare la cosa, come idea di base mi piace, non vedo grossi problemi a fare roba strana con 5 sopra e uno sotto (soprattutto se parliamo letteralmente di tre casi), ma vorrei vedere un esempio di uno con due forme e con differenze di sesso per farmi un'idea di come vengano.

**Comment by CiaobyDany** [comment]
@CiaobyDany Ah, e ovviamente sti gran cazzi di mettere i retro per ogni gioco direi, anzi, visto che il nuovo layout è più "flessibile" (did you get the joke? *occhiolino*), se si riuscissero a raggruppare ulteriormente i fronte considerando che abbiamo esattamente gli stessi modelli da XY a UsUl imo è un gran passo avanti.

**Comment by lucas992x** [comment]
@CiaobyDany l'artwork di Deoxys è buggato probabilmente per i problemi di cache, aprendolo risulta ok.

Comunque, ogni generazione può essere gestita come vogliamo, quindi potremmo anche decidere di fare una cosa per questi sprite jappi e un'altra per le differenze di forma.
Da valutare seriamente anche l'accorpamento di sesta e settima generazione quando possibile!

**Comment by flavio-a** [comment]
@lucas992 Possibile è possibile sempre, i file sono dei redirect.
Approvo anche le cose anarchiche di 5 sprelli sopra e uno sotto, ma occhio con i modelli che sono più grossi e non vorrei che ne finisse mezzo per riga

**Comment by lucas992x** [comment]
Io invece preferirei evitare sbilanciamenti del genere, cercherei piuttosto di distribuirli in modo più uniforme.
Per la questione modelli, quelli di XY se non erro hanno dimensione di 150px e quindi anche su uno schermo 320px dovrebbero stare comodamente in 2 per riga.

**Comment by flavio-a** [comment]
@lucas992 Falso, 20px sono pochissimi considerando che c'è il margine del template, lo spazio in mezzo e il margine della pagina.
E comunque molti modelli sono più grandi

**Comment by lucas992x** [comment]
@flavio-a ci infilo un img-fluid? Così sui display veramente stretti si rimpicciolisce appena. (A parte che prima di arrivare alla sesta generazione ne passerà di tempo...)

**Comment by lucas992x** [comment]
Ho aggiunto la terza generazione, dove Deoxys viene gestito a parte essendo un caso unico, discuteremo poi anche di lui (intanto cerco di finire il resto con un po' di pazienza).

Domanda non troppo related: sembra che fra gli sprite di Smeraldo cromatici frontali solo quello di Deoxys sia animato, ha senso rimediare creando automaticamente i redirect ai rispettivi file .gif o non verranno mai caricati?

**Comment by flavio-a** [comment]
> @flavio-a ci infilo un img-fluid? Così sui display veramente stretti si rimpicciolisce appena. (A parte che prima di arrivare alla sesta generazione ne passerà di tempo...)

Mi sembra l'idea migliore, anche perché `img-fluid` è una cosa che vuoi mettere più o meno sempre alle immagini.

**Comment by lucas992x** [comment]
@CiaobyDany dovrei aver finito la parte della quarta generazione, che mostra un po' di casi con differenze di forma e di sesso. Sulla fila di MS che dà errore con Pichu indagherò poi.

**Comment by lucas992x** [comment]
Mi è appena venuto in mente un possibile cambiamento: quale delle due preferite?
Attuale:
![attuale](https://user-images.githubusercontent.com/38510975/67391607-53708900-f59f-11e9-8e51-3b23cca4fc32.png)
Proposta:
![proposta](https://user-images.githubusercontent.com/38510975/67391608-53708900-f59f-11e9-9647-9bb473f49253.png)

**Comment by flavio-a** [comment]
Attuale

**Comment by lucas992x** [comment]
L'ho reso definitivo, quindi chiudo. Se dovremo nuovamente discuterne per i prossimi modelli riapriremo questa issue.
