### ISSUE TITLE
Update aree amico

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#58]
## Descrizione
Avevo incominciato a lavorare alle aree amico ma non le avevo finite. Sono rimaste un po' di cose da fare tra cui:

- Update grafico ai template:
  - [x] https://wiki.pokemoncentral.it/Template:InfoboxAreaAmico
  - [x] https://wiki.pokemoncentral.it/Template:Aree_Amico
  - [x] https://wiki.pokemoncentral.it/Template:Aapkmn
  - [x] https://wiki.pokemoncentral.it/Template:Aapkmn/h
- Sistemare le categorie:
  - [x] Stagno, Bacino Levante --> Stagni
  - [x] Foreste Ponente, Giungla, Foresta Levante --> Foreste
  - [x] Vulcano --> Vulcani
  - [x] Ruderi --> Rovine
  - [x] Piane Sud, Landa --> Piane
  - [x] Deserto --> Deserti
  - [x] Laghi Levante --> Laghi
  - [x] Fiume --> Fiumi
  - [x] Catena Montuosa --> Montagne
  - [x] Zona Paludosa --> Palude
  - [x] Isole Nordiche, Isole Sud, Isole Ponente, Isole Sud-Ovest --> Isole
  - [x] Mare Sud --> Grotte
- [x] Caricare le immagini delle aree rimanenti
- [x] Creare le aree rimanenti

**Comment by flavio-a** [comment]
@Cruifer Bravo Crusca, ti darò una mano (se avrò tempo)

**Comment by flavio-a** [comment]
Ho creato le Aree Amico rimanenti, chiudo.
