### ISSUE TITLE
Immagini di strumenti con nome "sbagliato"

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#6]
## Descrizione
Parecchi file vecchi hanno nomi "sbagliati", cioè che non seguono la nomenclatura standard applicata successivamente. Nello specifico mi riferisco alle decorazioni di quarta generazione, che hanno un nome del tipo _DP_NomeDecorazione.png_ anziché _DP_NomeDecorazione_Sprite.png_. Ciò fa sì che usando i template le immagini non vengano visualizzate correttamente.

## Pagine affette
https://wiki.pokemoncentral.it/Decorazioni#Decorazioni_di_quarta_generazione File da rinominare
https://wiki.pokemoncentral.it/Centro_Commerciale_di_Rupepoli#P3:_Bambole_.26_Decorazioni Pagina che non mostra le immagini a causa del nome sbagliato.

## Risoluzione del problema
- [x] Individuare i file incriminati.
- [x] Lanciare un bot che corregga tutti i nomi.
- [x] Correggere i link già esistenti oppure lasciare redirect.

**Comment by davla** [comment]
@lucas992 Il phrasing corretto è "non senguono la nomenclatura". Lo trovi in tutti i miei commenti :P

**Comment by davla** [comment]
Quando siete sicuri che non ci siano files da spostare tickate la prima spunta che diamo il via alle danze con il bot.

**Comment by lucas992x** [comment]
[files.txt](https://github.com/pokemoncentral/wiki-project/files/1934981/files.txt)
Elenco completo dei file, non so se sia rilevante il fatto che gli ultimi 4 hanno nome _DPPt_NomeStrumento.gif_ quindi leggermente diverso.

**Comment by flavio-a** [comment]
Se ho capito bene bisogna prendere tutti e soli i file di quell'elenco e aggiungere `_Sprite` in fondo al nome (in realtà prima dell'estensione), giusto? Se confermi avvio il bot e sistemo tutto.

**Comment by lucas992x** [comment]
Esattamente.

**Comment by flavio-a** [comment]
Ho spostato, lasciato i redirect e corretto i link nelle pagine https://wiki.pokemoncentral.it/Decorazioni e https://wiki.pokemoncentral.it/Bambole_Pok%C3%A9mon, che mi pare ne contenessero la maggior parte. Se ne trovate altri in giro potete correggerli o anche fregarvene, in realtà non è davvero importante. Chiudo.
