### ISSUE TITLE
Aggiornamento a LGPE: template da creare/aggiornare

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#61]
Topic sul forum: https://forum.pokemoncentral.it/threads/27188/ (lascerei lì le informazioni che possono inserire anche gli utenti e qui le cose tecniche che dobbiamo fare noi)
- [x] https://wiki.pokemoncentral.it/Template:Zone
    - [x] Aggiungere le entry per LGPE
    - [x] Capire come risolvere il problema dei nomi lunghi (blackabbrev+colorabbrev? Accorciarli in qualche modo?)
- [x] https://wiki.pokemoncentral.it/Template:Dex:
    - [x] Aggiungere le entry per LGPE (fatto, sono commentate per non mostrarle adesso che non serve)
    - [x] Decidere se vogliamo nascondere le voci non presenti (questo è delicato da fare, e lo metterei nelle cose a bassa priorità)
    - [x] Rifare il template in modo che sia responsive (fatto, in attesa di approvazione)
- [x] https://wiki.pokemoncentral.it/Template:Catch/entryLGPE
    - [x] Fare il template
    - [x] Sostituire le immagini di RFVF con le nuove
    - [x] Rifare il template visto che il codice fa altamente pena (con comodo in futuro)
- [x] https://wiki.pokemoncentral.it/Template:Pokémon (da aggiornare per LGPE)
- [x] https://wiki.pokemoncentral.it/Template:InfoPercorso (per le mosse mappa da usare)
- [x] https://wiki.pokemoncentral.it/Template:MTInfo
    - [x] Inserire i parametri per LGPE
    - [x] Aggiornarlo per renderlo responsive (in seguito)
- [x] https://wiki.pokemoncentral.it/Template:ItemInfobox (da aggiungere la tasca specifica per LGPE?)
- [x] https://wiki.pokemoncentral.it/Template:MossaInfobox (perché le hanno cambiate di numero fra SLUSUL e LGPE senza alcun motivo sensato)
- [x] https://wiki.pokemoncentral.it/Template:Maps
- [x] https://wiki.pokemoncentral.it/Modulo:DebRes: (gestire assenza abilità)
- [x] https://wiki.pokemoncentral.it/Template:Item

Due cose da decidere quando si avranno le informazioni complete:
- [x] Nelle pagine dei Pokémon, se conviene mischiare le mosse apprese in SL+USUL e LGPE o mettere quest'ultimo in una tabella separata. (Alla fine sono state separate.)
- [x] Nelle pagine delle mosse, se conviene mettere una colonna a parte per LGPE o no.

**Comment by flavio-a** [comment]
@lucas992 Togliere ha il problema che non fa capire che il Pokémon non ha una voce Pokédex/non si trova in quel gioco

**Comment by lucas992x** [comment]
Ovviamente se decidiamo di togliere ci aggiungerei una nota, in cima o in fondo al template, per spiegarlo alla veloce.

**Comment by CiaobyDany** [comment]
@lucas992 Ma abbiamo davvero utenti così imbecilli?

**Comment by lucas992x** [comment]
@CiaobyDany Devo proprio rispondere?

**Comment by CiaobyDany** [comment]
@lucas992 No, dai, seriamente. Nello zone stiamo parlando delle nuove UC + Zeraora in SL più di tutto quello che non è prima gen in LGPE. Davvero bisogna specificare che non ci sono? Cazzo, è segnato nella prima frase "introdotto in" e che LGPE abbia solo la prima gen è specificato nella sua pagina.
Passi quasi il dex che è meno immediato, ma il zone è veramente da menomati, suvvia...

**Comment by flavio-a** [comment]
Sulla cosa delle mosse: prima vediamo i learnset, se sono radicalmente differenti poi ne parliamo (che tendenzialmente vorrà dire io che mi oppongo perché non ho voglia di smazzarmi i moduli e voi che mi convincete a fare il contrario)

**Comment by flavio-a** [comment]
Un paio di domande:
- perché c'è da fare un nuovo template Pokémon per LGPE? Non riusciamo a riusare il vecchio come al solito? Tanto supporta già l'assenza di abilità (fa le prime due gen).
- il Listmove cosa deve essere aggiornato? Perché non c'è scritto e non l'ho capito.

**Comment by CiaobyDany** [comment]
@flavio-a Mi sono perso lo storico. Ora c'è il template Pokémon con il parametro gen senza i sottotemplate? In ogni caso, bisogna aggiornare pure quello.
Il listmove credo sia da aggiornare perché le mosse di LGPE non coincidono con quelle della settima generazione

**Comment by flavio-a** [comment]
> Mi sono perso lo storico. Ora c'è il template Pokémon con il parametro gen senza i sottotemplate?

Yep, i sottotemplate sono essenzialmente dei redirect che fissano il parametro `gen`.
> Il listmove credo sia da aggiornare perché le mosse di LGPE non coincidono con quelle della settima generazione

Non coincidono cosa vuol dire? Perché viene usato solo per l'[elenco mosse](https://wiki.pokemoncentral.it/Elenco_mosse), e non vedo cosa serva cambiare per adattarlo a LGPE.

**Comment by CiaobyDany** [comment]
@flavio-a Mea culpa, rispondo quando non sono nelle condizioni di farlo senza controllare. Credo che sia stato inserito per errore perché dal nome è stato considerato un template delle pagine di mosse/Pokémon

**Comment by lucas992x** [comment]
Leggendo di fretta ho visto "template [...] per l'elenco di mosse" e ho pensato all'elenco mosse, mi sa che ho sbagliato io ad interpretare. Se è così toglietelo pure.

**Comment by davla** [comment]
Nel DebRes, che si fa con l'assenza di abilità? Per esempio Gastly non sarà più immune a Terra, tanto per dirne una. Si potrebbe cambiare il testo nella disascalia in qualcosa come *Se questo Pokémon non ha l'abilità XXX, se la perde o ne sono annullati gli effetti ...*, oppure ignorare la abilità finché LGBT sono gli ultimi main series games usciti (oddio che cringe), ma è troppo brutto

**Comment by CiaobyDany** [comment]
@davla Se questo Pokémon non ha l'abilità xxx, che vale anche per i giochi pre terza gen e gg.

**Comment by flavio-a** [comment]
@CiaobyDany hahahaha per i giochi vecchi servono dei DebRes apposta perché la tabella dei tipi è diversa (è cambiata in seconda e in sesta)

**Comment by lucas992x** [comment]
Riguardo al template Pokémon, esattamente cosa c'è da cambiare rispetto alla prima generazione a parte passargli il parametro `gen` e sostituire il nome dello sprite con quella che sarà la sintassi per i modelli di LGPE?

**Comment by flavio-a** [comment]
@lucas992 Almeno le categorie danno per le mosse

**Comment by lucas992x** [comment]
@flavio-a Ma ora che ci penso, non era in corso di rifacimento il template Pokémon assieme al Party?
EDIT ci vorrà ancora tempo

**Comment by flavio-a** [comment]
> Nelle pagine delle mosse, se conviene mettere una colonna a parte per LGPE o no.

Forse vi interesserà sapere che effettivamente esistono Pokémon che imparano la stessa mossa a tre livelli diversi in SL, USUL e LGPE. Inoltre non mi è chiaro se questa scelta cambi il modo in cui aggiornerò il modulo Movelist. La verità è che quel modulo andrebbe completamente ripensato, ma nessuno ha tempo e voglia di farlo.

**Comment by flavio-a** [comment]
Se qualcuno vuole rispondere qui resta più tracciato: https://wiki.pokemoncentral.it/Utente:Ff300/sandbox
Prova per il movelist con LGPE, con una terza celletta o su due colonne. Secondo me anche la prima opzione non è male, ed evita infinite `x` in giro.
A quanto pare però @lucas992 preferisce separate, e la sua argomentazione è che la gente percepisce LGPE come separati da SLUSUL, che effettivamente è vero.

**Comment by Cruifer** [comment]
@lucas992 quando dici
>  https://wiki.pokemoncentral.it/Template:Pokémon (da aggiornare per LGPE)

cosa c'è da aggiornare di preciso? Perché volendo inizio a guardarci visto che ho la versione nuova in sandbox, così magari inizio anche a pensare di caricare la grafica nuova

**Comment by lucas992x** [comment]
Essenzialmente bisogna fare in modo che mostri gli sprite di LGPE e che nasconda abilità e strumento tenuto, visto che non ci sono.

**Comment by CiaobyDany** [comment]
@lucas992 *modelli. Occhio a non fare casino che gli sprite di LGPE esistono (i minisprite) e sono tutt'altra cosa.

**Comment by Cruifer** [comment]
allora, i modelli sono gestiti dal modulo spr, che suppongo sia stato già aggiornato da dedalo(?). Mentre per il resto ok, è easy

**Comment by flavio-a** [comment]
Scrivo anche qui: ho aggiornato i movelist (pagine delle mosse) per livello ed MT ad LGPE. Quelli per accoppiamento non ci sono (mi dicono), quindi rimangono eventi e Insegnamosse. Questi ultimi mi dicono esistere solo per le mosse speciali degli starter.

**Comment by Cruifer** [comment]
c'è da aggiornare anche il [Template:Item](https://wiki.pokemoncentral.it/Template:Item).

**Comment by lucas992x** [comment]
Quando avrò un attimo di tempo e voglia per capire come funzionano le tasche in LGPE, li aggiorno entrambi.

**Comment by lucas992x** [comment]
Questione tasche di LGPE. Essendo molto diverse dai giochi precedenti abbiamo già deciso che saranno separate, il parametro per SLUSUL resterà `bag7` e per questi due si userà `bagLGPE` (o se avete in mente un nome migliore ditelo). Ci sono comunque un paio di questioni da decidere.
- Non esiste più la tasca degli strumenti generici, quindi bisogna decidere se per gli strumenti sparsi è meglio indicare _Nessuna_ o _Strumenti_.
- L'infobox prende automaticamente il colore della tasca più recente (anche se volendo esiste già il parametro `color` per settare a mano il colore), ma apparentemente queste tasche non hanno colori. Per gli strumenti vecchi si può risolvere facilmente usando il colore `bag7`, per quelli introdotti in LGPE (tipo i profumi o i vestiti) ha senso creare colori appositi o mettiamo un generico colore `strumenti`?

![borsa lgpe](https://user-images.githubusercontent.com/38510975/52521073-faabcb00-2c71-11e9-96c6-4480075ddaf7.jpg)

**Comment by lucas992x** [comment]
Qua rimane solo la questione del template Zone con il nome di LGP che va a capo essendo troppo lungo, tutto il resto è stato fatto, vogliamo tenere ancora aperta questa issue o la chiudiamo e amen?

**Comment by Cruifer** [comment]
@lucas992 Io metterei il colorabbrev

**Comment by flavio-a** [comment]
il black/colorabbrev sembra una buona idea, vale la pena almeno provarlo. Chi ha voglia di fare un esperimento in sandbox?

**Comment by Cruifer** [comment]
ho fatto una prova in [sandbox](https://wiki.pokemoncentral.it/index.php?title=Utente:Cruifer/Sandbox&oldid=746633), al contrario di quel che pensavo inizialmente la soluzione migliore è il blackabbrev (ho fatto solo RB e LGPE per comodità, tanto più o meno l'effetto è quello)

**Comment by lucas992x** [comment]
Però così non lo trovo comodo. Non è meglio mettere i box bianchi e dentro un `blackabbrev`/`colorabbrev` a seconda della disponibilità?

**Comment by Cruifer** [comment]
secondo me così diventa difficile da interpretare, in base a cosa il black significa disponibile e color no? risulta un po' confusionario imo

**Comment by flavio-a** [comment]
@Cruifer in base al fatto che è così in tutto il sito

**Comment by lucas992x** [comment]
Esatto, e comunque negli esclusivi di versione c'è scritto *solo NomeVersione*, quindi non penso che qualcuno possa non capire la disponibilità guardando questo template.

**Comment by Cruifer** [comment]
ok, vedo di implementare

**Comment by Cruifer** [comment]
update: ho quasi fatto, l'unica cosa è che c'è da modificare un paio di moduli per aggiungere le sigle del Parco Amici e di Blu jappo da solo. In realtà le modifiche le ho già fatte in locale, ma ho paura di aver sbagliato qualcosa quindi se domani qualcuno tipo @davla o @flavio-a ha voglia di darci un'occhiata mi farebbe un favore

**Comment by lucas992x** [comment]
@Cruifer ma non puoi semplicemente fare qualche test in locale per controllare di non aver rotto nulla?

**Comment by flavio-a** [comment]
@Cruifer definisci "in locale" e in che modo posso controllarle (perché se sono sul tuo pc faccio fatica)

**Comment by Cruifer** [comment]
fixato, thx @flavio-a per l'aiuto. chiudo.
