### ISSUE TITLE
Moduli a prova di Pokémon incompleti

### ISSUE THREAD

**Issue by davla** [pokemoncentral/wiki-project#62]
## Descrizione
I moduli fanno magie e pescano immani quantità di dati dai moduli dati. Con i Pokémon incompleti, ovverosia con informazioni mancanti perché non ancora ufficialmente rivelate o non disponibili, crashano.

## Risoluzione del problema
Sarebbe bello non dovreci stare a pensare troppo, e rendere i moduli a prova di dati mancanti. Ovvero, mettere un po' di `if` in giro e eventualmente placeholders,

**Comment by flavio-a** [comment]
Con gli annunci dei nuovi Pokémon direi che abbiamo un ottimo test sul campo per moduli con Pokémon incompleti. Direi che come deadline per quest'issue possiamo mettere SpSc, usciti quelli saremo ragionevolmente sicuri che funzioni tutto.

Dagli annunci di ieri è saltato fuori che l'Evo-data (e moduli che lo usano, quindi Evobox e Wikilib-evos) non funziona senza ndex, quindi è da fixare (mi metto al lavoro).

**Comment by flavio-a** [comment]
Sono usciti SpSc, chiudo come da commento.
