### ISSUE TITLE
Luoghi di Kanto da rendere accettabili (in vista di LGPE)

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#63]
Visto che sui social è in programma una sorta di walkthrough, non sarebbe male aggiornare man mano i luoghi di Kanto in modo che i visitatori si trovino delle pagine almeno accettabili.
- [x] https://wiki.pokemoncentral.it/Biancavilla
- [x] https://wiki.pokemoncentral.it/Percorso_1_(Kanto)
- [x] https://wiki.pokemoncentral.it/Smeraldopoli
- [x] https://wiki.pokemoncentral.it/Percorso_22_(Kanto)
- [x] https://wiki.pokemoncentral.it/Percorso_2_(Kanto)
- [x] https://wiki.pokemoncentral.it/Bosco_Smeraldo
- [x] https://wiki.pokemoncentral.it/Museo_della_Scienza_di_Plumbeopoli
- [x] https://wiki.pokemoncentral.it/Palestra_di_Plumbeopoli
- [x] https://wiki.pokemoncentral.it/Percorso_3_(Kanto)
- [x] https://wiki.pokemoncentral.it/Percorso_4_(Kanto)
- [x] https://wiki.pokemoncentral.it/Monte_Luna
- [x] https://wiki.pokemoncentral.it/Celestopoli
- [x] https://wiki.pokemoncentral.it/Percorso_24_(Kanto)
- [x] https://wiki.pokemoncentral.it/Percorso_25_(Kanto)
- [x] https://wiki.pokemoncentral.it/Miramare
- [x] https://wiki.pokemoncentral.it/Palestra_di_Celestopoli
- [x] https://wiki.pokemoncentral.it/Percorso_5_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Via_Sotterranea_(Percorsi_5-6)
- [ ] https://wiki.pokemoncentral.it/Percorso_6_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Aranciopoli
- [ ] https://wiki.pokemoncentral.it/Percorso_11_(Kanto)
- [ ] https://wiki.pokemoncentral.it/M/N_Anna
- [ ] https://wiki.pokemoncentral.it/Palestra_di_Aranciopoli
- [ ] https://wiki.pokemoncentral.it/Grotta_Diglett
- [ ] https://wiki.pokemoncentral.it/Percorso_2_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_9_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_10_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Tunnel_Roccioso
- [ ] https://wiki.pokemoncentral.it/Lavandonia
- [ ] https://wiki.pokemoncentral.it/Torre_Pokémon
- [ ] https://wiki.pokemoncentral.it/Percorso_8_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Via_Sotterranea_(Percorsi_7-8)
- [ ] https://wiki.pokemoncentral.it/Percorso_7_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Azzurropoli
- [ ] https://wiki.pokemoncentral.it/Centro_Commerciale_di_Azzurropoli
- [ ] https://wiki.pokemoncentral.it/Villazzurra
- [ ] https://wiki.pokemoncentral.it/Casinò_di_Azzurropoli
- [ ] https://wiki.pokemoncentral.it/Rifugio_Rocket_(Azzurropoli)
- [ ] https://wiki.pokemoncentral.it/Palestra_di_Azzurropoli
- [ ] https://wiki.pokemoncentral.it/Percorso_12_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_13_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_14_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_15_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_16_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_17_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_18_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Fucsiapoli
- [ ] https://wiki.pokemoncentral.it/GO_Park
- [ ] https://wiki.pokemoncentral.it/Palestra_di_Fucsiapoli
- [ ] https://wiki.pokemoncentral.it/Zafferanopoli
- [ ] https://wiki.pokemoncentral.it/Dojo_Lotta
- [ ] https://wiki.pokemoncentral.it/Silph_SpA
- [ ] https://wiki.pokemoncentral.it/Palestra_di_Zafferanopoli
- [ ] https://wiki.pokemoncentral.it/Percorso_19_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_20_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Isole_Spumarine
- [ ] https://wiki.pokemoncentral.it/Percorso_21_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Centrale_Elettrica
- [ ] https://wiki.pokemoncentral.it/Isola_Cannella
- [ ] https://wiki.pokemoncentral.it/Laboratorio_Pokémon
- [ ] https://wiki.pokemoncentral.it/Villa_Pokémon_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Palestra_dell'Isola_Cannella
- [ ] https://wiki.pokemoncentral.it/Palestra_di_Smeraldopoli
- [ ] https://wiki.pokemoncentral.it/Percorso_22_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Percorso_23_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Via_Vittoria_(Kanto)
- [ ] https://wiki.pokemoncentral.it/Altopiano_Blu
- [ ] https://wiki.pokemoncentral.it/Sala_d'Onore
- [ ] https://wiki.pokemoncentral.it/Grotta_Celeste

**Comment by davla** [comment]
Come siamo messi qui?

**Comment by lucas992x** [comment]
Questa ormai non serve più, chiudo
