### ISSUE TITLE
Rendere responsive il PrevNext dei Pokémon

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#65]
## Descrizione
Quando i nomi dei Pokémon sono troppo lunghi il prevnext si vede maluccio su mobile. È comunque leggibile ma pur sempre migliorabile. Sarebbe anche carino se si riuscisse a risolvere il problema del MS di Melmetal.

## Screenshot
![screenshot_20181124-235355_samsung internet](https://user-images.githubusercontent.com/38588039/48985570-1985d100-f109-11e8-9388-56c90cc2aa9f.jpg)

![immagine](https://user-images.githubusercontent.com/38588039/48985539-c9a70a00-f108-11e8-9c8d-37e8c08865de.png)

## Risoluzione del problema
Credo che riciclando qualche altro layout o smanettando coi flex si riesca a fare qualcosa di carino. Potrei volendo farlo io, ma non sono troppo convinto.

**Comment by flavio-a** [comment]
Secondo me basterebbe mandare sempre a capo il nome e mettere le freccette centrate verticalmente per renderlo carino da mobile, e non dovrebbe neanche essere molto difficile. Tipo a capo su `xs` (o `sm` se esistono Pokémon con nomi così lunghi) e un bel `align-middle` alle freccette potrebbe funzionare.

**Comment by Cruifer** [comment]
stavo pensando che volendo si potrebbe anche togliere da lì il ndex. Mi sembra abbastanza superfluo, anche perché bisogna considerare che c'è subito sotto nell'infobox

**Comment by flavio-a** [comment]
@Cruifer In effetti ci sta

**Comment by Cruifer** [comment]
allora, mi sono reso conto che togliendo l'ndex si risolve anche il problema con Jirachi (e sono piuttosto sicuro che funzioni anche con gli altri che hanno lo stesso problema), quindi io lo lascerei così. Per quanto riguarda lo sprite di Melmetal ho messo uno `style="padding-left: 0.4em;"` nello span della freccia (ovviamente right nell'altra). Così la freccia non si sovrappone con lo sprite, inoltre la differenza negli altri è praticamente trascurabile quindi direi che siamo a posto. Se volete vedere c'è tutto in [sandbox](https://wiki.pokemoncentral.it/Utente:Cruifer/Sandbox/4), ovviamente. Ah se nessuno ha nulla in contrario volendo il modulo lo posso editare pure io

**Comment by flavio-a** [comment]
Di base non ci sono problemi se editi il modulo, però poi devi aggiornarlo anche su GitHub o avvisare qualcuno che lo faccia.

**Comment by lucas992x** [comment]
Fermi tutti. Visto che stiamo cercando di uniformizzare il wiki, ha senso creare un modulo PrevNext e basare poi tutti i template e moduli di questo tipo su di lui?

**Comment by flavio-a** [comment]
@lucas992 Può avere senso. Se lo ritenete utile si può fare.

PS: uniformizzare? Cosa ti ha fatto l'italiano?

**Comment by lucas992x** [comment]
Avendo una buona quantità di template PrevNext e almeno un modulo (non so se ce ne siano altri), secondo me può essere utile.

P.S. Non si dice _uniformizzare_?

**Comment by CiaobyDany** [comment]
@lucas992 Uniformare, porca troia, dimmi che stavi scherzando o sei da ricovero.

**Comment by Cruifer** [comment]
siamo sicuri che un eventuale modulo sarebbe compatibile con tutti i vari prevnext che abbiamo? Per fare un esempio, il [Template:DungeonPrevNext](https://wiki.pokemoncentral.it/Template:DungeonPrevNext) richiede un `rowspan`, al contrario di altri, così come per esempio il prevnext dei Pokémon ha dei minisprite che gli altri non hanno. Un altro possibile ostacolo che mi viene in mente è che questo lavoro lo dovrebbe eventualmente fare dedalo o flavio che magari hanno altre cose a cui lavorare in programma (o no?)

comunque uniformizzare secondo la treccani è corretto

**Comment by lucas992x** [comment]
Se uno di noi scrive il codice come se fosse un template, penso che poi per loro due sia relativamente rapido "convertirlo" in un modulo, o sbaglio?
Comunque vorrei anche vedere un esempio di caso in cui quel template richiede un `rowspan`, visto che in apparenza non c'è. Per i MiniSprite non penso sia un problema non risolvibile con un `if`.

**Comment by flavio-a** [comment]
@lucas992 https://wiki.pokemoncentral.it/Isola_Zero_Ovest
Comunque è vero, ci vuole poco a farne un modulo

**Comment by Cruifer** [comment]
allora, ho incominciato a tirare giù una bozza [qui](https://wiki.pokemoncentral.it/Utente:Cruifer/Sandbox/7), ma ho un piccolo problema col `colorscheme`. Cioè, io ho:

`<div class="roundy-20 flex flex-row flex-main-space-between flex-items-center width-xl-100" style="{{#invoke: css | horizGrad | type = {{{type|sconosciuto}}}| type2 = {{{type2|{{{type|sconosciuto}}}}}}}} padding: 0.2em;">`

che ovviamente non è compatibile col `colorscheme`, che serve per il [Template:VolumePrevNext](https://wiki.pokemoncentral.it/Template:VolumePrevNext). Il problema in teoria è quel `type`, ho provato a gestirlo con un `ifeq` ma non funziona. Io ora devo staccare, ma comunque qualcuno ha in mente soluzioni per questo problema?

**Comment by flavio-a** [comment]
@Cruifer andrà fatto in un modulo, quindi non si useranno questi strumenti di WikiCode. Tieni semplicemente conto di un parametro per indicare se si vuole usare colore o colorscheme e poi dal modulo si gestisce abbastanza decentemente

**Comment by lucas992x** [comment]
Proposta: se usassimo [questo layout](https://wiki.pokemoncentral.it/Template:PrevNext)? A me sinceramente piace di più.

**Comment by Cruifer** [comment]
@flavio-a ok, non avevo realizzato, hai ragione. Quindi un problema in meno.

@lucas992 a me non convince troppo da mobile, nel senso che secondo me mettendo i tre box a capo si perde un po' il senso del prevnext. Però sono democratico, quindi facciamo un sondaggio.

**Comment by flavio-a** [comment]
Ma quindi? Com'era rimasto il sondaggio? Siamo ancora in parità?

**Comment by Cruifer** [comment]
@flavio-a In realtà no, io mi sono arreso e ho lasciato carta bianca a Luca

**Comment by lucas992x** [comment]
Se ho ben capito, ciò che manca rispetto all'attuale PrevNext è:
- Possibilità di inserire due voci anziché una sia in _prev_ che in _next_.
- Possibilità di aggiungere un'immagine (è sempre un MiniSprite o ci sono altri usi?).

E poi vorremmo abolire il modulo colorscheme, il che si tradurrebbe in uno `switch` probabilmente.

**Comment by lucas992x** [comment]
https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate

Domanda per @flavio-a e @Cruifer. Nel `DungeonPrevNext`, il fatto che ci possano essere due `prev`/`next` distinti significa che il dungeon precedente/successivo varia a seconda del gioco? In tal caso, va bene metterci un `sup` per indicarlo?

**Comment by Cruifer** [comment]
Sì varia a seconda del gioco nel senso che quelli in verde sono esclusivi di cielo mentre in blu sono quelli di TOC (vedi ad es [Isola Zero Ovest](https://wiki.pokemoncentral.it/Isola_Zero_Ovest) per capire meglio). Solo che non sono sicuro che un semplice sup sia chiarissimo dato che cielo comparirebbe in entrambi (dunque non sono esclusivi, cioè in cielo si trovano entrambi) o quantomeno terrei almeno la struttra su due righe (senza necessariamente scomodarci con due div bianchi diversi, basta un a capo)

**Comment by lucas992x** [comment]
@Cruifer Infatti ho messo un semplice a capo per questi casi (v. sandbox), che è anche molto più semplice da gestire come codice. Se secondo voi è il caso di metterci un sup ci metto un attimo ad aggiungerlo, basta aggiungere un parametro opzionale (o meglio, 4 parametri opzionali sostanzialmente identici).

**Comment by Cruifer** [comment]
sorry, non avevo proprio visto la sandbox. Io non sono sicurissimo al 100%, @flavio-a ?

**Comment by flavio-a** [comment]
Sarò franco: secondo me non si capisce gran chè. La verità però è che non si capisce molto neanche nell'originale. Se lo combini con il fatto che dubito quei template abbiano una grande utilità, direi che un sup e messi su due righe può bastare.

**Comment by lucas992x** [comment]
Ok, allora penso che ci siamo. https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate

**Comment by flavio-a** [comment]
No aspetta, come sup però metti solo TO, non TOC. Perché è il successivo solo in TO, in C non sono consecutivi (Perché c'è l'altro in mezzo).

**Comment by lucas992x** [comment]
@flavio-a Vabbè è un esempio che si corregge in un attimo, guarda il resto :P

**Comment by flavio-a** [comment]
Ah boh sì, il resto mi va bene. Quando devo farci un modulo voi chiamatemi (e assegnatemi l'issue).

**Comment by lucas992x** [comment]
Direi che il template è [pronto](https://wiki.pokemoncentral.it/Template:PrevNext), @flavio-a. Escludendo `bag` che comunque non serve, non ho nemmeno usato altri template, quindi dovrebbe essere facile modulizzarlo.

**Comment by flavio-a** [comment]
Ma quindi adesso io creo il modulo PrevNext che fa le stesse cose del template ma è un modulo, voi lo usate nei vari template al posto del template PrevNext e io lo uso nel PokéPrevNext, giusto? O mi ricordo male io?

**Comment by Cruifer** [comment]
riapro l'issue perché il [GlitchPrecSucc](https://wiki.pokemoncentral.it/Modulo:GlitchPrecSucc) è rimasto tale e quale a prima (immagino perché è un modulo)
