### ISSUE TITLE
Differenze di genere in UselessForms-data

### ISSUE THREAD

**Issue by flavio-a** [pokemoncentral/wiki-project#67]
A quanto pare ingame le differenze di aspetto tra i generi che cambiano anche il MS (Unfezant, Frillish, Jellicent, Pyroar) non sono considerate forme alternative (e per una volta la cosa ha senso) quindi sono da rimuovere dalla pagina [differenze di forma](https://wiki.pokemoncentral.it/Differenze_di_forma). I più attenti però avranno notato che non è questo l'argomento dell'issue. La mia proposta è la seguente: di fatto l'unico motivo per avere questi Pokémon nell'UselessForms-data è per il MS: sul Wiki 1 MS <-> 1 forma (banalmente perché serve un nome del file e tornava comodo così quando è stata decisa la nomenclatura). La mia proposta è quindi di usare come etichetta per entrambe le forme la stringa vuota (come per Dugtrio non Alola, per intenderci) dato che, non esistendo ingame, non hanno un nome proprio.

A qualcuno (@davla) vengono in mente controindicazioni per questa scelta? Altrimenti si può pensare proprio di toglierle dal modulo dati, ma questa soluzione è sicuramente più laboriosa.

**Comment by CiaobyDany** [comment]
@flavio-a Approvo con una eccezione mandatory che è Meowstic, che appare effettivamente come forma alternativa nei dump (e che effettivamente non hai indicato nell'elenco quindi probabilmente siamo d'accordo).

**Comment by lucas992x** [comment]
Infatti Meowstic non è una forma useless (e per fortuna non va usato nel Catch perché non esiste selvatico).

**Comment by flavio-a** [comment]
Sì, Meowstick è escluso perché non è Useless. Aspetto il parere di Maze e se non segnala controindicazioni procedo.

**Comment by davla** [comment]
Ricordo già di un caso di label vuota, e non vi sono stati problemi. Quindi approvo :+1:
