### ISSUE TITLE
DebRes in Poipole ha il div delle debolezze non a larghezza 100%

### ISSUE THREAD

**Issue by davla** [pokemoncentral/wiki-project#7]
## Descrizione
Il DebRes nella pagina di [Poipole](https://wiki.pokemoncentral.it/Poipole) ha un problema di rendering. Per assurdi motivi il `div` delle debolezze non prende la larghezza al 100%. Con un `with : 100%` la situazione si risolve, ma non dovrebbe essere necessario.

## Screenshot
![marcondirondirondello](https://user-images.githubusercontent.com/12073088/39089339-2a2c2ca6-45c5-11e8-854c-8a66bd558398.png)

## Pagine affette
- [Poipole](https://wiki.pokemoncentral.it/Poipole)
- Potenzialmente altro

## Risoluzione del problema
Spero che sia il mio browser.

@pokemoncentral/wiki Controllate please che non lo faccia a voi. Se lo fa solo a me sono disposto ad accettare questa forma di discriminazione.

**Comment by CiaobyDany** [comment]
@davla Da me da mobile in versione desktop è 100%. Non sto ad abilitare la versione mobile perché lì immagino lo sia di default. Domattina controllo il fisso

**Comment by Cruifer** [comment]
@davla sinceramente questo problema lo vedo anche io. In più aggiungo che non è soltanto relativo al div delle debolezze ma potenzialmente anche agli altri (vedi [Litten](https://wiki.pokemoncentral.it/Litten)). Altra cosa che ho notato è che questo problema nasce quando sopra al template c'è un'immagine, ho fatto un test e questo è il risultato:

Questa è una pagina senza alcuna immagine

![schermata 2018-04-22 alle 11 56 43](https://user-images.githubusercontent.com/38588039/39093833-28246b7e-4626-11e8-97d3-f3a6be84b58d.png)
&nbsp;
Stessa pagina ma con un'immagine

![schermata 2018-04-22 alle 11 56 38](https://user-images.githubusercontent.com/38588039/39093832-28042f3a-4626-11e8-949b-6410e64407d4.png)

**Comment by flavio-a** [comment]
Il problema dovrebbe essere che il div.pull-center container ignora la presenza di oggetti in float ai lati (per esempio le immagini, ma anche il PokémonInfo) mentre i div interni no, quindi la loro larghezza viene ridotta per non sovrapporsi a tali elementi. Due immagini che ritengo parecchio esplicative:

![screenshot_22-04_12 47](https://user-images.githubusercontent.com/11007745/39094179-d26084c4-462b-11e8-82f0-031f8f12cfd2.png)
![screenshot_22-04_12 46](https://user-images.githubusercontent.com/11007745/39094181-d3da5ca8-462b-11e8-9105-52c3e52ce7e3.png)

Si potrebbe risolvere con un elemento in clear: both appena sopra il debres, anche se non so quanto sia bello da vedere tutto quello spazio bianco in più.

**Comment by davla** [comment]
Non so perché, ma un `overflow: auto` risolve il problema. Vedete che non era malaccio l'idea di metterlo ovunque?

EDIT: E invece sì. Però sarebbe bene che Tutti fossero a conoscenza della sua esistenza e lo provassero a casaccio per risolvere problemi.

**Comment by mexicat** [comment]
`clear: both` sul div contenitore del box risolve il problema e non dovrebbe avere controindicazioni, se non eventualmente l'aggiunta di un po' di spazio bianco (che è comunque preferibile alla sovrapposizione di div). Potrebbe avere senso aggiungerlo a tutti i template che vengono mostrati centrati? Così ci evitiamo sempre le sovrapposizioni.

**Comment by flavio-a** [comment]
In realtà io preferisco l'``overflow: auto``, l'effetto mi sembra più naturale dello spazio bianco (perché con ``overflow: auto`` considera come larghezza massima quella escludendo gli elementi di lato e ne occupa quindi l'80%).
@davla come dovremmo provarlo? Cioè, in che modo riesco ad aggiungerlo a tutte le pagine ma solo per me?

**Comment by davla** [comment]
Non lo aggiungi a tutte le pagine, perché fa troppo casino. Faccio una classe scema che aggiunga solo quello (`.overflow-auto`) e la aggiungi a mano dove serve. Bisognerebbe propagare la conoscenza dell'`overflow: auto` agli altri, @pokemoncentral/wiki. Io stesso ancora non ho capito bene come funzioni, ma risolve tanti problemi.

Fatto in [6b9b76a](https://github.com/pokemoncentral/wiki-styles/commit/6b9b76a4e916991bb599b438f06fe5c574aab176).

**Comment by Cruifer** [comment]
Scusate se riapro l'issue, ma ho notato lo stesso bug in [? (EC)](https://wiki.pokemoncentral.it/%3F_(EC)) e in [p ID](https://wiki.pokemoncentral.it/P_ID) (ma probabilmente c'è anche in altri pkmn glitch).

**Comment by flavio-a** [comment]
A quanto pare non avevo modificato il DebRes su Github (mi sembra strano, ma non trovo il commit in cui l'ho aggiunto), quindi con il recente aggiornamento di Maze l'overflow-auto si è perso. Adesso sistemo.
