### ISSUE TITLE
Errore 403 su alcuni Pokémon glitch

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#74]
## Descrizione
Come da titolo, quando cerco di aprire queste pagine restituisce un errore 403. Unico dettaglio in più è che sembra comportarsi così solo da mobile

## Pagine affette
* https://m.wiki.pokemoncentral.it/._p%E3%82%A5

* https://m.wiki.pokemoncentral.it/.8

* https://m.wiki.pokemoncentral.it/.PkMn

* https://m.wiki.pokemoncentral.it/._%E3%82%A5_(_.I%27_.

* https://m.wiki.pokemoncentral.it/.g

**Comment by lucas992x** [comment]
Confermo, anche a me apre normalmente la pagina desktop ma dà errore 403 se provo ad aprire la versione mobile, pure da PC (ho provato sia con Firefox che con Opera).

**Comment by flavio-a** [comment]
10 a 1 che è colpa del punto all'inizio del nome. @mexicat è l'unico che può farci qualcosa, credo

**Comment by lucas992x** [comment]
@flavio-a Mi sa che hai ragione, anche se provo ad aprire altre pagine inesistenti che iniziano con il punto mi dà questo errore

**Comment by Cruifer** [comment]
@flavio-a È quello a cui ho pensato anch'io in realtà, però ad esempio https://m.wiki.pokemoncentral.it/…… funziona

**Comment by mexicat** [comment]
Ora funziona. Era colpa di questa riga della conf di nginx:

```
location ~ /\. {
  deny all;
}
```

Che era fatta principalmente per evitare di mostrare file nascosti (tipo le directory `.git`.). L'ho resa più specifica, sperando che in futuro non ci siano Pokémon glitch che iniziano con ".git".
