### ISSUE TITLE
Template navigazione meccaniche di gioco

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#76]
Apro questa issue se no va a finire che me ne dimentico.

## Descrizione
Tecnicamente abbiamo un [template navigazione](https://wiki.pokemoncentral.it/Template:Meccaniche_di_gioco) per le meccaniche di gioco, ma ci sono solo 5 voci delle 180+ esistenti. Ce ne vorrebbe uno completo.

## Pagine affette
https://wiki.pokemoncentral.it/Categoria:Meccaniche_di_gioco

## Cose da fare/discutere
https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate/AltreProveTemplate5
- [x] Controllare le voci sulle Gare (credo ne manchino)
- [x] Controllare gli spin-off:
    - [x] Aggiungere le voci mancanti di GO (mi darà una mano Giglietto)
    - [x] Controllare che ci siano tutte le voci di MD
    - [x] Aggiungere le voci su Ranger (sempre se esistono pagine dedicate, non ne ho idea)
    - [x] Aggiungere eventuali voci su altri spin-off (come sopra)
- [x] Decidere come dividere le voci (per generazioni o per categorie)
- [x] Se opteremo per una suddivisione in categorie, decidere cosa farne delle voci in *Boh* (inserirle in *Altre meccaniche* o qualcosa del genere, oppure trovare loro un posto nelle altre categorie?)
- [x] Decidere se vogliamo togliere o lasciare le "sottovoci" in piccolo fra parentesi
- [x] Decidere se vogliamo tutto visibile o solo ciò che riguarda la voce specifica (per intenderci, una roba tipo il template *Strumenti base* che in ciascuna pagina mostra solo le generazioni in cui quello strumento è disponibile come strumento base: [esempio](https://wiki.pokemoncentral.it/Chiarolite#Vedi_anche), [esempio](https://wiki.pokemoncentral.it/Gemma_blu#Vedi_anche))

Altre voci da discutere:
- Allenamento Pokémon
- Cartello
- Eeveeluzione
- Elenco strumenti per numero d'indice (quarta generazione)
- Fotoclub di Alola
- Ghicomixer
- Introforza
- Macinabacche
- Miele
- Mixer Bacche
- Numero d'indice
- Pioggia Acida
- Poké Ball
- Pokémon notturni
- Spettro di Lavandonia
- Tier
- Trappola
- Trucco
- Varianti abilità/mossa

**N.B.** Nel secondo template ho inserito le voci "dubbie" in più categorie possibili, si fa prima a controllare cosa togliere piuttosto che cosa aggiungere.

**Comment by flavio-a** [comment]
A me piacerebbe dividere in base a dove intervengono, ma bisogna poi vedere quanto vengono grossi i gruppi, perché se dividi in 3 gruppi enormi è come non dividere.
Come proposte di categorie vi sparo "in lotta", "in gara", "esplorazione", "allevamento" (accoppiamento, allenamento pro, ... tutte quelle cose che riguardano appunto l'allevamento di un Pokémon), "stato" (robe tipo abilità, IV, EV, statistiche, natura, mosse, ... in pratica le cose che trovi nella schermata di stato di un Pokémon).

Per gli stati io nel template metterei solo il link alla pagina "problemi di stato", in altri casi valuterei volta per volta (anche in base a quante voci sono tra parentesi).

**Comment by lucas992x** [comment]
Ora che ci penso, bisogna anche considerare che alcune voci andranno in più categorie: per esempio le abilità andranno sia nella categoria __Lotta__ che in __Esplorazione__, e forse pure altrove. C'è da sperare che non siano troppe voci a fare così, altrimenti il template si allungherebbe parecchio.

Comunque, se non avete altre idee/proposte nei prossimi giorni provo a realizzare entrambe le possibilità, così ci facciamo un'idea più precisa.

**Comment by lucas992x** [comment]
Meanwhile, creiamo anche la sottocategoria __Meccaniche di gioco spin-off__?

**Comment by flavio-a** [comment]
Se proprio hai voglia di sistemare le pagine sì

**Comment by lucas992x** [comment]
Se con "sistemare le pagine" intendi "aggiungere la categoria alle pagine e metterle in coda nella lista di cose che sarebbero da fare ma nessuno ne ha voglia" allora sì :D

**Comment by lucas992x** [comment]
Ho messo [qua](https://wiki.pokemoncentral.it/Utente:Lucas992/ProveTemplate/AltreProveTemplate5) le due proposte e aggiornato il post iniziale per scrivere tutte le cose da fare, in particolare invoco @flavio-a @Cruifer @StygianIrene per MD, Ranger e quant'altro. Ora le mie considerazioni sui vari punti da discutere.
- La divisione per generazioni ha il vantaggio che non ci sono ambiguità né doppioni, quindi il template è anche più breve (ma resta comunque molto grosso quindi non penso che quest'ultimo sia un gran vantaggio). Però preferisco la divisione per categoria, mi sembra più ordinata e "naturale" da sfogliare.
- L'attuale "categoria" *Boh* la chiamerei *Altre meccaniche* o qualcosa del genere e lascerei lì le voci che non sappiamo dove mettere.
- Le voci in piccolo fra parentesi io le lascerei.
- Terrei tutte le categorie visibili e non solo quelle che riguardano la pagina.

E infine ciò che farei sulle altre voci:
- Allenamento Pokémon: pagina da rifare completamente, e probabilmente da togliere dalla categoria *Meccaniche di gioco*.
- Cartello: togliere dalle meccaniche di gioco.
- Eeveeluzione: togliere.
- Elenco strumenti per numero d'indice (quarta generazione): togliere.
- Fotoclub di Alola: boh, forse la lascerei.
- Ghicomixer: togliere. È uno strumento, non possiamo metterci lì a includere tutti gli strumenti e neanche solo quelli con meccaniche particolari.
- Introforza: togliere (come sopra).
- Macinabacche: togliere (come sopra).
- Miele: splitterei in due pagine, *Miele* per lo strumento e *Alberi del Miele* per spiegare la meccanica di DPPt, e quest'ultima ovviamente da inserire nelle meccaniche di gioco.
- Mixer Bacche: togliere (come sopra).
- Numero d'indice: togliere.
- Pioggia Acida: togliere (come sopra).
- Poké Ball: togliere, c'è già la pagina sulla cattura e quella sul tasso di cattura.
- Pokémon notturni: indeciso.
- Spettro di Lavandonia: togliere.
- Tier: togliere.
- Trappola: sono indeciso.
- Trucco: togliere.
- Varianti abilità/mossa: indeciso.

**Comment by flavio-a** [comment]
Per Ranger: bisogna aggiungere [Poké Tattica](https://wiki.pokemoncentral.it/Pok%C3%A9_Tattica), [Mossa (Ranger)](https://wiki.pokemoncentral.it/Mossa_(Ranger)) e direi anche [Styler di Cattura](https://wiki.pokemoncentral.it/Styler_di_cattura), a cui provvederò ad aggiungere la sezione sulla cattura (che c'è già su Bulba, basta tradurre quella).
Per MD: mi pare ci sia tutto (in sostanza la pagina delle meccaniche e tutte quelle che vengono linkate da lì come voci principali).

La categoria _Boh_ la possiamo chiamare felicemente _Altro_.
Le voci tra parentesi sono un grande boh. Da un lato la versione senza parentesi è effettivamente molto più corta (mi sono permessa di metterla in sandbox), dall'altra sono effettivamente utili. Io rimango della mia idea di valutare caso per caso (per esempio, toglierei i vari tipi di lotta dato che c'è anche un template apposta e i problemi di stato visto che sono anche facilmente raggiungibili dalla pagina principale, ma terrei le abilità speciali perché non sono così facili da raggiungere neanche dalla pagina delle abilità, linkata nel template).

Per le altre voci concordo con tutte quelle che hai detto di togliere, in più toglierei anche Allenamento Pokémon, Pokémon notturni, Varianti abilità/mossa, e concordo con lo split "Miele"/"Alberi del miele".

**Comment by lucas992x** [comment]
Comunque direi che siamo d'accordo sulla divisione in categorie, a meno che qualcun altro non usi argomentazioni abbastanza convincenti da farci cambiare idea, quindi ho tolto la divisione per generazioni.
Per le sottovoci, ne ho tolte un po' (secondo box) e penso che quelle rimaste si possano lasciare.

**Comment by flavio-a** [comment]
@lucas992 A me piace il secondo

**Comment by lucas992x** [comment]
Domanda prima di renderlo definitivo: come colore lasciamo sempre `pcwiki` o ne mettiamo uno appropriato per ogni pagina?

**Comment by flavio-a** [comment]
@lucas992 pcwiki ignorante

**Comment by lucas992x** [comment]
Ok, con comodo lo inserirò nelle pagine e poi chiuderò la issue.

**Comment by CiaobyDany** [comment]
Proposta: e se mettessimo il link a Lotta Pokémon nel div di intestazione come per le Gare e lo togliessimo dall'elenco? In alternativa anche le Gare avranno il link in elenco e non nell'intestazione, questa asimmetria triggera molti OCD, lo so.

**Comment by lucas992x** [comment]
La casella arancione con l'etichetta _Lotte_ è già un link. In effetti da lì si può togliere la voce _Lotta Pokémon_.

**Comment by CiaobyDany** [comment]
@lucas992 Ah, che pirla, avevo fatto il check dalla pagina stessa di Lotta Pokémon ed ovviamente lì non mi apriva nulla 😂😂😂😂
