### ISSUE TITLE
Proposte github/pcw

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#77]
Mi erano venute in mente due idee e ho pensato di condividerle con voi, magari ne caviamo fuori qualcosa di utile. Pensavo in primis di aggiungere tre label per dare un'idea di quanto è prioritaria un issue (ad es priorità bassa/media/alta con colori diversi e facilmente riconoscibili); fra l'altro è anche abbastanza complementare ai milestones (anche se non hanno un grosso seguito da noi lol). L'altra cosa a cui avevo pensato era di aggiungere il collegamento a github in sidebar nel wiki, anche se non è un social in effetti ma un link dal wiki può essere utile (io ad esempio lo userei per comodità, oppure un utente un po' più esperto può usarlo per segnalare qualche problema di sorta).

**Comment by lucas992x** [comment]
Mi piacciono entrambe le proposte. Per la prima però io farei solo una label "Alta priorità", o al massimo due, lasciando senza questa label le issue a bassa priorità. Ci vedrei bene come colore il rosso, eventualmente si può cambiare la label "Bug" in arancione o giallo per non far confusione.

**Comment by Cruifer** [comment]
@lucas992 Avevo proposto di mettere anche la label per priorità bassa per una questione di raggruppamento, così uno che ha un po' di tempo libero può mettersi lì e vederle tutte e decidere quale risolvere, però sono aperto anche alla tua proposta

**Comment by Cruifer** [comment]
nessun'altro ha nulla da dire in merito a questa issue?

**Comment by CiaobyDany** [comment]
Ci ho messo 3 minuti per entrare qui dentro quindi sì, mettiamo il cazzo di link in sidebar. Va bene anche per le priorità.

**Comment by Cruifer** [comment]
ok, a questo punto c'è bisogno dell'iconcina svg da mettere a sinistra del link. Qualcuno sa/si ricorda come era stato fatto per i social? Ah e serve anche un burocrate per editare il css e la sidebar

**Comment by lucas992x** [comment]
> Ah e serve anche un burocrate per editare il css e la sidebar

Oppure un Gika che si decida a modificare i permessi :D

**Comment by Cruifer** [comment]
Chiudo perché ho visto che il buon @Snorlite ha aggiunto il link
