### ISSUE TITLE
Articolo sulle differenze di forma

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#78]
## Descrizione
Questa pagina è piuttosto lunga, e peggiorerà sempre di più. Vediamo cosa si può togliere o spostare.

## Pagine affette
https://wiki.pokemoncentral.it/Differenze_di_forma

## Risoluzione del problema
Ecco le prime cose di cui vorrei discutere, poi ovviamente se ce ne sono altre dite pure (adesso ho guardato la pagina di fretta perché fra non molto devo staccare).
- Pikachu: avendo millemila forme alternative e più di una pagina dedicata ad esse, in questa lascerei solo un link a [Varianti di Pikachu](https://wiki.pokemoncentral.it/Varianti_di_Pikachu) (che magari andrà riordinata e completata) e giusto due righe per riassumere le cose più importanti.
- Differenze di sesso: le sposterei in [Sesso#Differenze tra i sessi](https://wiki.pokemoncentral.it/Sesso#Differenze_tra_i_sessi), lasciando due righe riassuntive, come sopra.

**Comment by StygianStar** [comment]
Mi addosso io l'onore di sistemare l'articolo delle varianti di Pikachu.

**Comment by CiaobyDany** [comment]
Una divisione per generazioni è troppo drastica? Posto che comunque non avere dei riferimenti precisi negli articoli dei singoli Pokémon secondo me è molto confusionario per chi non sa che esiste quell'articolo.

**Comment by flavio-a** [comment]
La divisione per generazioni ha il problema che le prime due restano vuote (se spostiamo Pikachu nella pagina apposta la prima gen è solo un "Vedi la pagina per Pikachu" e la seconda gen è proprio vuota), e forse è troppo frammentaria soprattutto considerato che non tutti sanno a memoria in che gen è stato introdotto ogni Pokémon. Un'alternativa che mi è venuta in mente adesso è di spostare tutti i contenuti in sottopagine dei singoli Pokémon, e tenere in questa un elenco di "Articolo principale: ..." e la sezione "Altri Pokémon". In questo modo uno ha l'elenco completo in questa pagina e non deve ricordarsi la generazione.
Per quanto riguarda i riferimenti precisi nelle pagine dei Pokémon approvo, sia che si sposti nella sottopagina sia che lasciamo Differenze di forma dobbiamo spammare link in modo che la gente trovi le info se le cerca.

**Comment by CiaobyDany** [comment]
Ma sai che la trovo veramente geniale come soluzione? Richiederà tanto tempo, ma mi pare una soluzione definitiva, coerente, usufruibile e ordinata. Voto per le sottopagine singole in cui metterei anche roba tipo modelli ecc. (a sto punto anche per Pikachu e simili)

**Comment by StygianStar** [comment]
Anche a me piace molto come soluzione, ottima idea!

Pikachu potrebbe essere il primo a subire questa sorte

**Comment by flavio-a** [comment]
Dopo aver scritto ieri su Tg che mancano le sezioni di Eternatus, Urshifu e forse altri alla pagina "differenze di forma" mi è venuta in mente questa issue e ho voluto fare una prova per Eternatus:
https://wiki.pokemoncentral.it/index.php?title=Utente:Ff300/sandbox2&oldid=825887 (questa cosa dei link permanenti è molto comoda, così resta la cosa giusta nella discussione anche se poi modifico la pagina)

Comincio io con i commenti:
1. facendo una sezione per ogni forma poi le sottosezioni vengono forse poco distinguibili (le vorrei con 2 =, non con 3). Forse si potrebbero invertire l'ordine di nidificazione, anche perché mi immagino che certe sezioni vengano generali per tutte le forme (per esempio i confronti), quindi forse ha senso dividere le singole sezioni per forma quando serve invece di dividere tutta la pagina per ogni forma. Sì, ripensandoci ora probabilmente è meglio così. Vorrei anche il vostro parere ma me ne sto convincendo. Mi rendo conto che Eternatus sia un brutto esempio per questo, ma immaginate per esempio la sottopagina di Blastoise che deve contenere le info sia della Mega che della Giga, o quella di Slowing con Mega e forma di Galar.
2. Molte delle informazioni sono duplicate rispetto alla pagina principale. Per esempio, le sezioni "nell'anime" e "nel manga". Io le ho messe nella bozza perché se no la pagina veniva davvero corta, però si potrebbe valutare di tenerla volutamente minimale.
3. Forse Eternatus non è stato l'esempio migliore perché non avendo giocato Spudo ho solo scopiazzato info in giro (Bulba, altre pagine nostre) ma magari altri riescono a scrivere qualcosa di meglio ^^'.

Altri pareri/commenti/idee per il contenuto?

**Comment by StygianStar** [comment]
1. Per quanto riguarda la suddivisione, per me va bene quello che hai proposto. 
2. Ecco, per questa parte sono meno convinta. Non sono sicura sia un bene metterla anche lì, però capisco che così diventerebbe corte.
3. Lycanroc potrebbe essere un buon esempio

**Comment by flavio-a** [comment]
Non ho capito una cosa: nel punto 1 intendi quello che ho scritto nel commento o quello che ho fatto nella pagina?

E per il 2 allora direi di non mettere le sezioni duplicate e lasciare solo le cose nell'articolo del Pokémon, piuttosto lasciamo le pagine corte. In generale non sono un grande fan delle cose duplicate (deformazione professionale) perché vuol dire dover aggiornare da due parti, e se è vero che per l'utente può essere comodo avere le stesse info in due pagine diverse per evitarsi di dover cambiare pagina, non mi sembra questo il caso per le apparizioni in anime e manga delle forme alternative.

Per il punto 3 magari provo a fare la pagina di Lycanroc e vediamo che succede.
EDIT: ho aggiunto Lycanroc (vedi https://wiki.pokemoncentral.it/index.php?title=Utente:Ff300/sandbox2&oldid=826025). Non mi è venuto in mente nulla da mettere nella sezione "nei giochi", e anche se avrei potuto aggiungere la sezione "nell'anime" copiandola dalla pagina di Lycanroc non mi è sembrato il caso dato che non sarebbe stata particolarmente legata alle forme di Lycanroc, quanto al Pokémon in generale. Io terrei le pagine così, molto succinte, giusto con l'introduzione e i confronti di statistiche/forme. Ovviamente le altre sezioni si possono aggiungere se servono (per esempio, Eternatus per cui è proprio la forma alternativa che ha un ruolo importante nella trama secondo me ci sta la parte "nei giochi"), ma di base io non cercherei a tutti i costi di metterle.

**Comment by StygianStar** [comment]
Nel punto 1 intendevo dire che, secondo me, la suddivisione che hai messo nella tua sandobox va bene.

Sono d'accordo anche io su questo. Quindi eviterei sezioni anime e manga in più.

Ok, direi che con questo Pokémon si ha un'idea migliore di quello che devo uscire... Anche se diverse forme saranno molto differenti da loro. 

Per il resto non ho nient'altro da dire e non mi viene in mente nulla. Altri?

**Comment by StygianStar** [comment]
Direi che stasera provo a creare la sotto pagina di qualche forma.

Inoltre vi aggiorno che Bulba ha deciso di accorpare tutte le voci del Pokédex delle forme dei Pokémon. Non so come spiegarlo, per capire andate a vedere una qualsiasi voce del dex di un Pokémon con le forme (Alcremie, Toxtricity, Cramorant, Venusaur, Charizard, ecc.).

**Comment by CiaobyDany** [comment]
@StygianIrene Quello che voleva dire è che ora c'è un solo box dedicato alle entry del dex suddiviso per forme. Esempio: https://bulbapedia.bulbagarden.net/wiki/Charizard_(Pok%C3%A9mon)

**Comment by StygianStar** [comment]
Ok, per casi di Pokémon come Alcremie (sì, mi voglio veramente male) che hanno delle forme puramente estetiche che sezione mettiamo per i modelli? Qualcosa come "Aspetto"?

**Comment by StygianStar** [comment]
Ho provato con Alcremie: [qui](https://wiki.pokemoncentral.it/index.php?title=Alcremie/Forme&oldid=826770).
Che ne dite? 
C'è sempre la questione del nome delle sezione e, inoltre, ho deciso di dividere in sottosezioni per evitare un [muro del genere](https://wiki.pokemoncentral.it/index.php?title=Utente:Stygian/Sandbox4&oldid=826769).

**Comment by CiaobyDany** [comment]
@StygianIrene Me gusta

**Comment by StygianStar** [comment]
_Non so se volete saperlo, ma mancherebbero i modelli di HOME di Alcremie cromatico..._
Ah, giusto, non saprei nemmeno che categorie mettere. Dobbiamo creare qualcoda ad-hoc?

**Comment by flavio-a** [comment]
La pagina di Alcremie mi piace.

Poi due cose:
- i modelli statici shiny di HOME non dovrei averne caricato nessuno perché non abbiamo mai avuto gli statici shiny, se però mi dite che li vogliamo ci posso lavorare
- se vi piacciono anche le pagine di Eternatus e Lycanroc sposto anche quelle nel mainspace

**Comment by StygianStar** [comment]
@flavio-a - Boh, in realtà non so quanto e quando potranno tornare ancora utili i modelli statici shiny di HOME... Però anche averli non sarebbe male... 
Se carichiamo solo quelli di Alcremie facciamo una cosa molto puzzolente?
- Per la sottopagina di Lycanroc cambierei solo il langtable come ho fatto in Alcremie, solo perché da mobile si legge incasinato (almeno finché non avremo una versione mobile del template)... Il testo iniziale invece è aggiornato a Bulba? Altrimenti poi ci passo io a controllarlo.
- Per la sottopagina di Eternatus direi che va bene. Per un attimo non ero convinta della sottosezione "Nei giochi", ma ci sono altri casi come Giratina e Necrozma che potrebbero avere una cosa simile, quindi mi sono convinta che vada bene.

**Comment by flavio-a** [comment]
Lycanroc: l'introduzione è aggiornata a quello che dice Bulba, e ho sistemato il langtable. Ad un certo punto sposterà nella pagina adeguata.
Eternatus: quando sposterò Lycanroc lo farò anche con Eternatus.
Modelli shiny: si possono anche caricare tutti, il problema sono le forme alternative che sono da rinominare come per i modelli base. Caricare quelli di Alcremie da soli si può anche fare, il punto è che se carichiamo quelli prima o poi vorremo caricare anche gli altri, ne sono certo. D'altra parte possiamo dire che diventa un problema dei noi del futuro, e quindi ignorarlo per ora.

**Comment by StygianStar** [comment]
@flavio-a Ottimo! 
Stasera vedo di fare qualche altra forma (teoricamente abbiamo fatto quella più sbatti). 

Allora carichiamo anche tutti i modelli cromatici, a questo punto. Se vuoi spartirli come l'altra volta, scrivimi pure in privato. 
E comunque le forme shiny di Alcremie sono solo 7, per fortuna.

**Comment by StygianStar** [comment]
Update: ho creato le sottopagine di [Cramorant](https://wiki.pokemoncentral.it/Cramorant/Forme), [Toxtricity](https://wiki.pokemoncentral.it/Toxtricity/Forme), [Eiscue](https://wiki.pokemoncentral.it/Eiscue/Forme) e [Morpeko](https://wiki.pokemoncentral.it/Morpeko/Forme).
Ho aggiornato anche il [template Boxforme](https://wiki.pokemoncentral.it/Template:Boxforme), ne aveva bisogno, ora da mobile si vede decisamente meglio e ho tolto del codice in eccesso.
Quesiti:
- Che categoria mettiamo a queste sottopagine?
- Non voglio darlo per scontato, ma per Pokémon che Bulba tratta insieme (vedi [Zacian e Zamazenta](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_form_differences#Zacian_and_Zamazenta), [Sinistea e Polteageist](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_form_differences#Sinistea_and_Polteageist), ecc.), noi facciamo due sottopagine distinte?

**Comment by CiaobyDany** [comment]
@StygianIrene Dato come le stiamo organizzando direi di sì. Bene anche le altre sottopagine, mi piace come stanno venendo

**Comment by flavio-a** [comment]
Dobbiamo per forza metterci una categoria? Comunque nel caso qualcosa tipo `[[Categoria:Sottopagine forme]]` sulla falsa riga delle [Sottopagine Sprite e modelli](https://wiki.pokemoncentral.it/Categoria:Sottopagine_Sprite_e_modelli)
Anch'io direi di fare due pagine separate per i Pokémon trattati insieme (es: Zacian e Zamazenta).

Anche a me piacciono molto come stanno venendo le sottopagine, ma vorrei fare qualche osservazione sul resto:
- Nell'articolo differenze di forma vogliamo lasciare proprio solo il "articolo principale"? Si potrebbe pensare di scrivere due righe anche lì, tipo quante e quali forme ha il Pokémon, così l'utente può farsi un'idea generale direttamente nella pagina, e poi andare nella sottopagina per i dettagli. Esempio: "{{principale/Lycanroc/Forme}} Lycanroc può assumere tre forme diverse, la Forma Giorno, la Forma Notte e la Forma Crepuscolo. La forma viene determinata al momento dell'evoluzione in base al gioco e al momento della giornata."
- Queste sottopagine hanno troppi pochi link in entrata. La gente AMA le forme alternative, quindi queste pagine potenzialmente potrebbero avere un sacco di visite, ma gli utenti devono arrivarci per sapere che esistono. Ora non dico di fare una controllo a tappeto di tutto il sito, ma quando modificate una pagina e vi sembra che si parli di una forma alternativa, spammate i link. Ah, e secondo me ci vuole __almeno__ un link dalla pagina del Pokémon a questa sottopagina. Bisogna solo capire dove metterlo (introduzione, quando si parla delle forme? Sezione biologia, quando si parla delle forme? Una sezione apposta con "articolo principale"? Proponete).

PS: ho spostato le sottopagine.
PPS: non mi sono scordato dei modelli shiny, solo non ci lavoro oggi

**Comment by CiaobyDany** [comment]
@flavio-a Sì alla categoria, nelle differenze di forma io farei un paragrafo leggermente discorsivo introduttivo che rimanda alla categoria, avevo già pensato a mettere un link alle forme alternative in ingresso dalla pagina principale del Pokémon ma lo farei tipo in primissima frase. Coso possiede [[/forme|ventordici forme]].

**Comment by StygianStar** [comment]
@flavio-a 
- Per la categoria, sì, io la metterei (l'ho già messa) assolutamente perché è comoda sia per l'utente che per noi.
- Nelle varie sottosezioni in Differenze di forma metterei al massimo "Tizio possiede tot forme". Non mi dilungherei di più perché ci sono casi estremi come Alcremie o Vivillion. 
- Dagli articoli dei Pokémon è sicuro che ci va un link in entrata a queste sottopagine. Ok per come ha detto @CiaobyDany di aggiungerlo nell'intestazione. Ultimamente stavo lavorando sulla [standardizzazione delle intestazioni](https://wiki.pokemoncentral.it/Utente:Stygian/Intestazioni_Pok%C3%A9mon) (ho fatto i primi 250 Pokémon) quindi qualcosa mi invento. 
Un "articolo principale" lo aggiungerei alla sezione "Biologia"... oppure a "Forme"?

**Comment by flavio-a** [comment]
> Nelle varie sottosezioni in Differenze di forma metterei al massimo "Tizio possiede tot forme". Non mi dilungherei di più perché ci sono casi estremi come Alcremie o Vivillion.

Ha senso non volersi dilungare, e a questo punto direi anch'io di non mettere niente, tanto anche solo il numero delle forme è abbastanza inutile da solo. Se uno vuole i dettagli va nella principale.

> Un "articolo principale" lo aggiungerei alla sezione "Biologia"... oppure a "Forme"?

Se c'è già nell'intestazione forse non serve l'"articolo principale" in giro. Basta ricordarsi di mettere il link se e quando si parla di una forma alternativa nell'articolo.

**Comment by StygianStar** [comment]
@flavio-a Ho cominciato a linkare alcune sottopagine negli articoli principali, vedi Urshifu e Lycanroc (ho messo i link anche su Rockruff e Kubfu).

Sorge spontanea un'altra domanda.
Visto che abbiamo redirect del tipo MegaVenusaur/Venusaur Gigamax > Venusaur, per i nomi delle forme sarebbe da fare una cosa analoga? Se sì, il redirect va all'articolo principale o a quello delle sottopagine delle forme?

**Comment by flavio-a** [comment]
Non saprei quanto gli utenti li cerchino. C'è da dire che dei redirect non possono fare danni, ma secondo me non vale la pena di crearli in massa. Si fanno quando capita.
Io li farei alle pagine principali, perché mi immagino che uno cerchi la forma per sapere i dati di gioco (che sono nella pagina principale).

**Comment by CiaobyDany** [comment]
@flavio-a Concordo con Flavio, i redirect vanno fatti alla principale perché comunque la maggior parte delle informazioni rimangono lì. Però potremmo optare per qualcosa di più invasivo tipo una sorta di disambigua in top (a livello di grafica, ovviamente rivedendo contenuti con un template ad hoc), anche se forse è troppo invasivo. D'altro canto Bulba mette in disclaimer i redirect alle sezioni di GO...

**Comment by StygianStar** [comment]
Diciamo che per la cosa dei redirect dei nomi delle forme posso pensarci più avanti... Ora che le ho provate tutte a sulla mia pelle ci ho ripensato. Comunque ormai diciamo che manca poco a finire tutte le sottopagine.

Per quel disclaimer che parla Dany, potrebbe essere un'idea interessante? Magari da incorporare nel prevnext come fa bulba? La prima è quello che fa Bulba (con GO)  e la seconda è una mia idea: https://i.imgur.com/XScdzIh.png

**Comment by CiaobyDany** [comment]
@StygianIrene Interessante l'idea di metterlo nel prevnext perché lo rende meno invasivo. E la tua idea lo rende ancora meno invasivo, ma forse fin troppo? Il rischio è che non venga notato perché nessuno è mai stato abituato a cercare cose lì. Gli altri che ne dicono?

**Comment by StygianStar** [comment]
Le sottopagine sono state create, l'articolo delle differenze di forma aggiornato.

**Comment by flavio-a** [comment]
Come potete vedere da qua sopra ho aggiornato i moduli per linkare le sottopagine delle forme. Questo vuol dire che adesso tutte le cose che usano i moduli per i link alle forme alternative (per esempio gli elenchi automatici o semi-automatici, come l'[ndex](https://wiki.pokemoncentral.it/Elenco_Pok%C3%A9mon_secondo_il_Pok%C3%A9dex_Nazionale)) puntano alle sottopagine, eccezion fatta per le forme di Alola/Galar/Megaevo/Gigamax che puntano alla pagina generale della meccanica.
Il "problema" è che c'erano un paio di casi particolari, ovvero Pichu e Pikachu, che pur avendo delle forme non avevano le sottopagine (Pichu usava la pagina di Pichu Spunzorek e Pikachu ne usa 5231 diverse), per ora ho risolto con dei redirect (Pichu/Forme -> Pichu Spunzorek, Pikachu/Forme -> Varianti di Pikachu), se avete idee migliori ovviamente si possono cambiare le cose (stiamo comunque parlando di due casi particolari, secondo me i redirect vanno più che bene).

Visto che Irene ha finito di creare le pagine, se nessuno ha altro da dire io tra qualche giorno chiudo.

**Comment by StygianStar** [comment]
@flavio-a Grazie mille. Avrei dovuto scrivere qui per la cosa dei moduli, ma non ci ho più pensato. 
Avevo sistemato anche un paio di template con le differenze di forma, poi mi sono trovata di fronte al problema di Pikachu e non ho continuato. Quello che hai trovato tu è un compromesso accettabile comunque (anche se nelle varianti di Pikachu non ci sono solo le forme -che di fatto sarebbero solo i cosplay e i berretti- ma anche il resto, però direi anche sticazzi).

(nota: direi che ora ci sono un po' di link in entrata nelle sottopagine)
