### ISSUE TITLE
Rimuovere i ":" superflui nelle label di tutti i template informativi

### ISSUE THREAD

**Issue by mexicat** [pokemoncentral/wiki-project#8]
## Descrizione
In alcuni template informativi è presente un `:` dopo le label, in altri no. Questi `:` sono superflui perché il fatto che si tratti di una label è già deducibile dalla struttura grafica; propongo quindi di risolvere questa inconsistency globale rimuovendoli ovunque.

## Screenshot

**❌ NO:**

![screen shot 2018-04-23 at 12 24 01](https://user-images.githubusercontent.com/699380/39121257-5f322478-46f1-11e8-9da8-feb998a83d35.png)

**✅ SÌ:**

![screen shot 2018-04-23 at 12 24 22](https://user-images.githubusercontent.com/699380/39121317-88d87372-46f1-11e8-9533-2db72d52de42.png)

## Pagine affette

* Infobox: https://github.com/pokemoncentral/wiki-project/issues/8#issuecomment-383561190
* Altri template: https://github.com/pokemoncentral/wiki-project/issues/8#issuecomment-384094050

## Risoluzione del problema

- [x] Individuare tutte le pagine affette
- [x] Modificare i template rimuovendo i `:`

**Comment by lucas992x** [comment]
Template:Console infobox
Template:DeckInfobox
Template:InfoboxDungeon
Template:InfoboxDW
Template:InfoboxGioco
Template:LibroInfobox
Template:PokéWalkerInfobox
Template:RegioneInfobox

Tra gli infobox, questa dovrebbe essere la lista completa.

**Comment by Cruifer** [comment]
In realtà lo stesso tipo di problema lo hanno anche i template di navigazione ad esempio [questo](https://wiki.pokemoncentral.it/Template:AllenatoriRinger). In più sono abbastanza sicuro che ci sono molti template non categorizzati (o categorizzati male) che andrebbero controllati.

**Comment by flavio-a** [comment]
Non è strettamente legato al tema di questa issue ma vorrei proporre anche di uniformare il colore delle label: come si può vedere dall'immagine ok di Gika la scritta "Provenienza" è in grigio mentre le altre sono in nero. Questo è dovuto al fatto che ai link il colore viene inserito tramite il template:Colore2 ed è 000, nel caso del testo normale il default (che arriva da .mw-body) è #252525.
Io sarei per usare il nero. Credo che l'idea di mettere come colore di default #252525 sia perché è un po' meno fastidioso di #000 ma comunque ben leggibile su sfondo bianco. Per le label, che sono parti molto piccole di testo, non credo sia necessario questo accorgimento.

**Comment by lucas992x** [comment]
@flavio-a Metterei il testo di default nero con un parametro opzionale per renderlo bianco (|text=fff), come abbiamo fatto nel template InfoCittà, per evitare che infobox come questo diventassero illeggibili: https://wiki.pokemoncentral.it/Ultramegalopoli

**Comment by Cruifer** [comment]
Ho fatto un elenco dei vari template di navigazione da sistemare, che hanno lo stesso identico problema, e sono questi:
[Senza titolo.txt](https://github.com/pokemoncentral/wiki-project/files/1944742/Senza.titolo.txt)
Sono tanti, quindi non penso che riuscirò a sistemarli io perché non ho tempo, comunque a questo punto dovremmo avere tutti i template problematici

**Comment by Cruifer** [comment]
Per ora ho sistemato gli infobox, nei prossimi giorni vedo se ho tempo di fare anche i template di navigazione

EDIT: ho finito di sistemare tutti i template. Ho risolto anche il problema segnalato da Flavio, quindi chiudo.
