### ISSUE TITLE
Aggiornamento SpSc: parte tecnica

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#80]
Come al solito metteremo sul forum la parte sui contenuti e qui le questioni tecniche (che aggiungeremo man mano che ci vengono in mente).
- [x] https://wiki.pokemoncentral.it/Template:Zone
- [x] https://wiki.pokemoncentral.it/Template:Dex:
    - [x] Aggiungere le entry per SpSc (fatto, appaiono solo se presenti)
    - [x] Decidere se vogliamo nascondere le voci non presenti o mostrare l'avviso di mancata disponibilità
- [x] https://wiki.pokemoncentral.it/Template:Sprite: si veda #55
- [x] https://wiki.pokemoncentral.it/Template:Catch/entry8
    - [x] Creare il template
    - [x] Metterci le immagini nuove
- [x] https://wiki.pokemoncentral.it/Template:Pokémon
- [x] https://wiki.pokemoncentral.it/Template:InfoPercorso (per le mosse nascoste)
- [x] https://wiki.pokemoncentral.it/Template:MTInfo
- [x] https://wiki.pokemoncentral.it/Template:ItemInfobox
- [x] https://wiki.pokemoncentral.it/Template:Item
- [x] https://wiki.pokemoncentral.it/Template:MossaInfobox (per le MT e le mosse tutor)
- [x] https://wiki.pokemoncentral.it/Template:Maps
- [x] https://wiki.pokemoncentral.it/Template:Helditems
- [x] Moveset nelle pagine dei Pokémon: nelle sottopagine `/Mosse apprese in settima generazione` ci spostiamo tutti o solo quelli presenti in SpSc?

**Comment by flavio-a** [comment]
In realtà ci sono da aggiornare anche movelist e learnlist (non solo con i dati ma proprio per supportare l'ottava gen), ma diventa inutile se riesco a chiudere #73 in tempo (e penso di farcela, alla peggio uso un workaround brutto finché non riesco a sistemare davvero).

Per quanto riguarda i Pokémon che non ci sono in SpSc: io farei come nel [template zone](https://wiki.pokemoncentral.it/Template:Zone) per LGPE, ovvero segnalerei che il Pokémon non si trova in questi giochi, magari anche mettendo uno sfondo più scuro. Userei questa soluzione in tutti i template che lo richiedono: zone, dex, sprite, etc.

Altra cosa: non sarebbe male mettere un soft lock sulle pagine dei Pokémon ed iniziare ad aggiornarle in locale per poi caricarle tutte in massa al day 1, come abbiamo fatto per SL (anche se questo non c'entra con l'aggiornamento dei template e quindi penso andrebbe scritto sul forum)

**Comment by CiaobyDany** [comment]
@flavio-a Ok Flavio tu cortesemente lavora solo alla #73 e nessuno fa nulla su quel fronte finché tu non hai finito (niente workaround brutti, non voglio perdite di tempo)

Proposta per i giochi in cui non sono codificati i Pokémon: è tanto impossibile fare varianti alternative delle sigle in b/n per evidenziare maggiormente l'assenza in senso assoluto, incluso tramite scambi? Ha senso farlo? Discuss.

Per il soft lock e il topic del forum sto aspettando di capire se possiamo coprire i leak. In teoria abbiamo una risposta domani in merito, direi di aspettare quello prima di fare qualsiasi altra cosa perché la situazione cambia drasticamente

**Comment by lucas992x** [comment]
Per il template Dex io manterrei la soluzione usata per la settima generazione, che mi sembra piuttosto efficace, ecco un esempio:
![scr](https://user-images.githubusercontent.com/38510975/68297340-fa245180-0096-11ea-869e-f5d1cdc89998.png)

Per Zone, non sarebbe male rifarlo completamente in modo che sia simile a Dex (in modo da avere un layout più consistente possibile per i vari template nelle pagine dei Pokémon), ma immagino che al momento nessuno abbia davvero tempo e voglia di farlo. Comunque per la questione sollevata da Dany sul mettere in evidenza l'assenza totale, per un rimedio rapido magari possiamo valutare una cosa del genere:
![scr](https://user-images.githubusercontent.com/38510975/68297803-242a4380-0098-11ea-8605-d347f04611df.png)

Per Sprite non abbiamo ancora i modelli di LGPE e se arriveranno loro e quelli di SpSc ce ne vorrà di tempo, quindi per ora l'ottava generazione sarà completamente assente per tutti. Ci penseremo a tempo debito, ma anche qui userei la soluzione già presente in Dex.

**Comment by flavio-a** [comment]
>Ok Flavio tu cortesemente lavora solo alla #73 e nessuno fa nulla su quel fronte finché tu non hai finito (niente workaround brutti, non voglio perdite di tempo)

I tempi non dipendono (troppo) da me, devo fare prove sul sito quindi sono limitato ad un tentativo al giorno la mattina presto (il bot carica, vedo cosa non va e o fixo sul momento o reverto), e anche andare di sandbox ha i suoi limiti perché provare sulle pagine vere mi fa trovare più bug. Quindi ho tempo per fare altro dopo che ho preparato la prova del giorno successivo.

> Proposta per i giochi in cui non sono codificati i Pokémon: è tanto impossibile fare varianti alternative delle sigle in b/n per evidenziare maggiormente l'assenza in senso assoluto, incluso tramite scambi? Ha senso farlo? Discuss.

Il primo problema che mi viene in mente è che la differenza tra NB colorati e in bianco e nero temo non si vedrà a colpo d'occhio, io opterei più per una cosa stile zone di Luca (però più chiaro pls)

**Comment by CiaobyDany** [comment]
@flavio-a Ah, claro, allora organizzati come meglio credi

NB non mi paiono un vero problema perché fino alla sesta tutti i Pokémon sono presenti nel codice di gioco, quindi quelli non presenti sono solo quelli introdotti successivamente ma in quel caso si mette il solito avviso "questo Pokémon è stato introdotto in n-esima generazione" togliendo i box delle generazioni precedenti. Posto che la soluzione di Luca mi piaciucchia, fa molto effetto morte incombente ma temo che con il 90% dei colori dei giochi sia impraticabile (però sì, nero su nero non va bene, al massimo testo bianco)

**Comment by flavio-a** [comment]
Nota a caso per chiunque aggiorni il `MossaInfobox`: prova a guardare https://wiki.pokemoncentral.it/Modulo:MovesData

**Comment by lucas992x** [comment]
Sto iniziando a dare un'occhiata al template `MossaInfobox`, e c'è una cosa di cui vorrei discutere. Giustamente Flavio ci fa notare che alcune info le potremmo prendere dal modulo apposito per non dovercene più preoccupare; vorrei però far notare due controindicazioni.
- Gli utenti non potranno più aggiornare queste info, dovrà farlo uno di noi (sperando che non sia uno di quei moduli da editare solo di notte).
- Spariranno le annotazioni su eventuali cambiamenti ([esempio](https://wiki.pokemoncentral.it/Vuototetro)).

Dato che queste info se cambiano lo fanno una volta ogni tot anni, e che in quei casi bisogna comunque aggiornare la pagina della mossa, io non sono convinto che sia una buona idea usare `MovesData` in questo infobox. Voi cosa dite?

**Comment by CiaobyDany** [comment]
Considerando la mole di errori che ho trovato persistenti da anni e che sicuramente qualcosa mi sarà sfuggito sono totalmente favorevole ad inserire il riferimento dal modulo, ma direi che la cosa può avere priorità bassa ora che ho già sistemato tutto a mano.

**Comment by flavio-a** [comment]
Le annotazioni sui cambiamenti comunque si possono tirare fuori dai moduli, solo che a quel punto si fa un bel modulo tipo PokémonInfo/BoxTipo per potenza/precisione/PP della mossa che crea tutti i boxettini di quella riga. Se volete si può fare (con priorità bassa), però nel caso apro una issue apposta.

**Comment by CiaobyDany** [comment]
Approvo anche se con sto fatto che adesso passiamo dal post-uscita al pre-uscita in due mesi è veramente pesante stare dietro a tutto. Non potevano fare l'annuncio per l'anniversario come fanno sempre?
