### ISSUE TITLE
Modelli di Pokémon Spada e Pokémon Scudo

### ISSUE THREAD

**Issue by CiaobyDany** [pokemoncentral/wiki-project#85]
## Descrizione
Sono usciti i modelli di Spada e Scudo powered by pkparaiso.
https://www.pkparaiso.com/espada_escudo/sprites_pokemon.php
Ovviamente sono tra le cose più richieste dal nostro pubblico, anche perché credo che continuiamo a non avere alcuni artwork e quindi mancano immagini più grandi dei MS 40*40 per diversi Pokémon che non è il massimo della vita.

## Proposte di inserimento
Io propenderei per avere i file a risoluzione originale da qualche parte, ma al posto di avere dimensioni standard per ogni modello mi limiterei ad averli quadrati e marginless sulla dimensione più lunga, eventualmente anche sforando dal limite di 1280 giustificato dall'uso di file originali in-game. Dopodiché, se come mi auguro nelle pagine vengono richiamati i file "compressi" delle immagini a risoluzione inferiore si decide una dimensione standard applicata a tutti (200px? 250px?) e si usano quelli. In alternativa, essendo oggettivamente impraticabile avere dei file da 3MB l'uno nelle pagine, sarà necessario caricare delle varianti ridotte da inserire nelle pagine vere e proprie.

Quindi discuss per capire se la proposta va bene o se suggerite altro, e poi spiegateci cosa può essere fatto da un bot e cosa invece deve essere fatto a mano.

- [x] Scaricare tutti i modelli in locale
- [x] Decidere come caricarli su PCW
- [x] Resizarli in base a quanto deciso
- [x] Rinominarli con la nomenclatura standard
- [x] Upparli in massa su PCW
- [ ] Inserirli negli articoli (dovrebbero esserci già i link rossi per i template delle squadre allenatori, probabilmente c'è da aggiornare il template sprite e basta)

**Comment by davla** [comment]
I file "compressi" si chiamano thumbnail.

Tuttavia, se ben ti ricordi, rimpicciolire le cose le sgrana. Era il motivo per cui hai voluto i modelli XY a 192px (e poi tornasti strisciando che li volevi a 150px), perché se no poi ne sgranavano troppi. Indi, preparati a vedere le cose sgranate.

Detto ciò, la tua proposta è ragionevole. Se non ricordo male/sono spuntati impedimenti vari è tutto fattibile con bot e script nostri, previa modifica di questi ultimi. Modifiche che dovrebbero essere easy per design. Ma lascio l'ultima parola a @flavio-a.

Also, off-topic immenso. più si va avanti e più sprite e modelli ci sono nelle pagine dei Pokémon che già sono pesantissime. Propongo di fare un po' come le mosse e tenere solo quelli dell'ultima generazione, spostando le altre immagine in sottopagine `Sprite e modelli` per *tutti* i Pokémon. Perché chi vuole vedere lo sprite di Spinarak in Smeraldo è uno di nicchia, e può tranquillamente fare un click in più.

**Comment by CiaobyDany** [comment]
@davla Le sgrana sì, ma non in modo così brutto se si dimezzano o più le dimensioni. Il problema è se parti da un affare da 210×210 e lo trasformi in 192×192. Qui partiamo da 400+ mi pare di aver capito, quindi è molto meno evidente. Also: grazie per aver infierito sul mio cambio di idea, ricordo quando dicevi che me l'avresti rinfacciato per il resto della mia vita, ma non pensavo fossi così serio. CARO IL MIO SIGNOR BR.

Ciò detto. L'off topic non mi pare così immenso, ma la questione della sottopagina degli sprite e modelli la affronterei in futuro, possibilmente rendendola simile alla imagerie che hanno i francesi (quindi includendo gli artwork ed eventuale altra roba degli spin-off), e dopo aver fatto le sottopagine delle forme alternative come aveva suggerito Flavio nonricordodove.

**Comment by flavio-a** [comment]
Non mi intrometto nella questione delle immagini sgranate, litigate voi.
Come osservato su Telegram, MediaWiki crea delle thumbnail (cfr: [immagine a risoluzione intera](https://media.pokemoncentral.it/wiki/3/31/OPJ03.png), [thumbnail](https://media.pokemoncentral.it/wiki/thumb/3/31/OPJ03.png/200px-OPJ03.png)), quindi la cosa di caricare immagini grosse ed avere comunque pagine non pesantissime è ragionevole.
Io eviterei comunque sprelli di 30MB, un minimo di resize la farei comunque, tipo 600x600 mi sembra comunque ragionevole ed evita immagini enormi che non servono davvero (perché le mettiamo riscalate) e riempono il server (è vero che Gika dice che non ci sono problemi, ma 400x5MB = 2GB di sprelli potrebbero infastidirlo).
> Scaricare tutti i modelli in locale
Resizarli in base a quanto deciso
Rinominarli con la nomenclatura standard
Upparli in massa su PCW

Queste quattro si dovrebbero fare con script/bot e dovrebbe essere relativamente facile, verificherò gli script quando ho tempo. Aggiungerei che si possono anche passare tutti con FileOptimizer, anche se il mio pc mi odierà se lo faccio.
Approvo anch'io spostare le immagini in sottopagine. Domanda: facciamo una sottopagina unica per tutti gli sprelli o una per generazione come le mosse?

**Comment by CiaobyDany** [comment]
@flavio-a Mi stai chiedendo di avere una conferma da gika sul limite dimensione immagini? Spero di no.

**Comment by CiaobyDany** [comment]
Mi stai chiedendo di avere una conferma da gika sul limite dimensione immagini? Spero di no.

A parte quello. Comprendo il tuo punto di vista logico sul resize perché le immagini non appaiono mai a dimensione intera nelle pagine, ma posso replicare dicendo che è vero per il 90% delle immagini del wiki più grandi degli sprite, quindi dovete convincermi meglio.

Per la sottopagina direi unica. I moveset interessano nel 99% dei casi per un gioco specifico perché vuoi tirarti su il Pokémon e ti interessa sapere se impara qualcosa di più utile di Azione prima del livello 50 o se forse è meglio cestinarlo. Le immagini ce le vedo molto più nel reame del "vediamo come si è evoluta la rappresentazione di tizio in 20+ anni di giochi". Also: i moveset sono elenchi molto lunghi, metterne più di uno in una pagina la renderebbe molto difficile da navigare. Gli elenchi degli sprelli in linea di massima non sono così lunghi (e implicherebbe avere delle sottopagine con letteralmente 4 immagini. Non mi entusiasma troppo sinceramente...)

**Comment by flavio-a** [comment]
Che le altre sono poche.
Da https://wiki.pokemoncentral.it/Speciale:MediaStatistics
> image/jpeg | .jpeg, .jpg, .jpe | 5 416 (6,44%) | 1 163 762 630 byte (1,08 GB; 6,42%)
image/gif | .gif | 9 766 (11,6%) | 1 596 982 982 byte (1,49 GB; 8,81%)
image/png | .png, .apng | 68 817 (81,9%) | 15 328 394 329 byte (14,28 GB; 84,6%)

Totale 16,85 GB. Ti ho convinto che caricare altri 2GB ogni generazione (in realtà di più, perché ho considerato solo 400 sprelli quando in realtà sono front/back e sono più di 400 Pokémon perché ci sono anche i DLC) non sembra una buona idea?

**Comment by CiaobyDany** [comment]
@flavio-a In realtà sono 1800 quindi più che 2GB parliamo di 9 GB che sono meno di due terzi del totale!!1! Pertanto non comprendo l'insistere su tali argoment...
Ok, hai vinto tu. Resize sia.

**Comment by davla** [comment]
> @davla Le sgrana sì, ma non in modo così brutto se si dimezzano o più le dimensioni. Il problema è se parti da un affare da 210×210 e lo trasformi in 192×192. Qui partiamo da 400+ mi pare di aver capito, quindi è molto meno evidente. Also: grazie per aver infierito sul mio cambio di idea, ricordo quando dicevi che me l'avresti rinfacciato per il resto della mia vita, ma non pensavo fossi così serio. CARO IL MIO SIGNOR BR.

Ah, se dici tu che non sgrana mi fido. Se poi ritorni strisciando, affar tuo :smiling_imp: 

Per la pagina, sì, una per Pokémon.

> Io propenderei per avere i file a risoluzione originale da qualche parte.

E sono stato ninjato, ma io il resize lo davo per scontato. Il "da qualche parte" era Dropbox, o roba del genere

**Comment by flavio-a** [comment]
Quindi che dimensioni? La domanda giusta in realtà è "a che dimensione vogliamo usarli?", perché poi da lì si prende qualcosa tra il doppio e il triplo per non averle sgranate.

**Comment by CiaobyDany** [comment]
@flavio-a Non vanno bene le dimensioni di quelli di sesta? Che il Signor Br ha gentilmente ricordato essere stati ridotti a 150.

**Comment by flavio-a** [comment]
In che senso? Intendi le dimensioni originali? Perché i file pkparaiso (che credo siano quelli che abbiamo preso noi) sono 192x192 (salvo eccezioni), che mi sembra poco.

**Comment by CiaobyDany** [comment]
@flavio-a No, le dimensioni d'uso "da lì poi si prende qualcosa tra il doppio e il triplo per non averle sgranate".
Also: ci son da fare gli statici pure e quelli direi che vanno a 1280/dimensioni massime.

**Comment by StygianStar** [comment]
(Non so cosa potrei fare in tutto ciò, probabilmente nulla, ma durante i fine settimana posso essere disponibile)

**Comment by flavio-a** [comment]
> No, le dimensioni d'uso "da lì poi si prende qualcosa tra il doppio e il triplo per non averle sgranate".

Al momento se non sbaglio li usiamo a 192px, da cui delle dimensioni sensate possono essere 450px o 500px. Vi faccio poi sapere quanto spazio occupano nelle due versioni quando finisco il resize (senza FileOptimizer, dato che ci metterà tantissimo e non voglio farlo andare a vuoto).
Nota: 500px ha ovviamente il vantaggio di essere più "future proof", nel senso che se vorremo aumentare le dimensioni d'uso potremo farlo di più.

> Il "da qualche parte" era Dropbox, o roba del genere

"Dropbox, o roba del genere" non sembra un'opzione fattibile visto che 4 GB non ci stanno sul mio Dropbox. Per ora sono sul mio hard disk, ma non sembra una posizione così accessibile a tutti. Avete proposte?

**Comment by CiaobyDany** [comment]
@flavio-a Al momento li usiamo a 150, perché "sono tornato strisciando" da Maze a chiedergli di cambiarli. Sul 450/500 vorrei prima capire quanto cambia a livello di dimensioni.

Per l'upload nel caso si può usare il drive di pokemoncentral00@gmail.com

**Comment by flavio-a** [comment]
Dopo una comodissima giornata passata a resizare modelli (non è vero, ho solo dovuto avviare tre script a distanza di 3 ore e mezza, ma credo che il mio pc mi stia comunque odiando) posso finalmente portarvi le statistiche!
In totale ci sono 1116 modelli, che in originale pesano 4,6GB. Riducendo quelli più grandi ad una certa dimensione otteniamo:
- 500px -> 3,2GB
- 450px -> 2,9GB
- 400px -> 2,5GB
Notare che questi numeri vanno ancora passati con FileOptimizer, che probabilmente riduce le dimensioni di un altro po'.
Se le dimensioni d'uso sono 150px si possono tenere a 400px (siamo ben oltre il doppio, e potenzialmente possiamo usarli anche a 200px) con un consumo di spazio alto ma forse accettabile. In realtà bisognerebbe sentire Gika quanto spazio c'è sul server: se dice che abbiamo 1TB allora possiamo anche caricarli a dimensione intera, se invece ci restano 10 GB magari li rimpiccioliamo a 150 direttamente.

**Comment by StygianStar** [comment]
Abbiamo chiesto a Gika quanto spazio c'è?

**Comment by CiaobyDany** [comment]
@StygianIrene Ovviamente mi sono dimenticato, ma è un'ottima motivazione per rompergli il cazzo

**Comment by StygianStar** [comment]
Visto che è stato scritto solo nel gruppo Telegram, riporto anche qui che ci sono 70gb liberi, quindi non ci sono problemi

**Comment by flavio-a** [comment]
Abbiamo i modelli animati. Credo tutti alla dimensione giusta. Adesso devo lavorare sugli statici (che abbiamo detto metto a dimensione originale, tanto se sono un singolo frame invece di 3 miliardi dovrebbero occupare una quantità di spazio ragionevole).

**Comment by flavio-a** [comment]
Abbiamo anche i modelli statici. Adesso mancano solo un po' di redirect e poi ho finito

**Comment by flavio-a** [comment]
Ho fatto i redirect ma ci sono ancora due cose di cui vorrei discutere.
1. La nostra dimensione d'uso dei modelli è 150px. Ci sono alcuni modelli che sono sotto quella dimensione e altri che sono sopra ma sotto i 300px, e che quindi mostrano degli artefatti quando riscalati per essere alla dimensione giusta ([esempio con Tympole](https://wiki.pokemoncentral.it/Tympole#Evoluzioni)). Che facciamo? Una proposta è aggiungere del padding per arrivare a 150 (chi è sotto) o 300 (chi è tra 150 e 300), ma questo avrebbe il problema di avere alcune immagini perfettamente tagliate e altre con lo spazio bianco, che si tradurrebbe di fatto, visto che usiamo tutto a 150px, in modelli "più grandi" e "più piccoli". Altre idee? Lasciamo così?
2. Visto che i nuovi modelli statici non sono a 150px di loro bisogna aggiornare tutti i template/pagine che li usano per fissare la dimensione ed evitare [cose del genere](https://wiki.pokemoncentral.it/index.php?title=Pok%C3%A9mon_pseudo-leggendari&oldid=775208).

**Comment by flavio-a** [comment]
La maggioranza (Dany) ha votato di tenere come sono i modelli grossi ma non abbastanza grossi. Tenete presente il punto 2 del messaggio precedente, ma direi che si può chiudere.
