### ISSUE TITLE
Aggiornamento GCCNote e Infobox per Pokémon V e VMAX

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#87]
## Descrizione
Promemoria per me di cosa fare quando avrò tempo (mai)

## Pagine affette
* https://wiki.pokemoncentral.it/Lapras_VMAX_(Spada_e_Scudo_50)
* https://wiki.pokemoncentral.it/Morpeko_V_(Spada_e_Scudo_79)
* https://wiki.pokemoncentral.it/Snorlax_VMAX_(Spada_e_Scudo_142)
* https://wiki.pokemoncentral.it/Morpeko_VMAX_(Spada_e_Scudo_80)

## Risoluzione del problema
C'è anche da aggiungere le immagini accanto al nome nell'infobox

**Comment by Cruifer** [comment]
Il mio lavoro qui è finito, ma solo per il momento. C'è da modificare di nuovo il modulo per aggiungere il template per lo stadio dei Pokémon VMAX nell'infobox (`EvoVMAX` e `EvoVMAXG`) I template li creo io, ma non so come funziona per il modulo. Inoltre manca la categorizzazione da aggiungere, anche per i Pokémon GX (`GX` insieme a `RedGX`, `TTGX` insieme a `RedTTGX`) oltre che per V e VMAX (con due categorie separate). Anche qui non ho capito benissimo come funziona, dato che devono esserci due alias, credo. Assegno a @flavio-a subito sennò mi scordo. (non odiarmi)

**Comment by flavio-a** [comment]
Che modulo/i?

PS: quando ho letto
> Il mio lavoro qui è finito

ho pensato troppo al [meme di sailor moon](https://knowyourmeme.com/memes/my-job-here-is-done)

**Comment by Cruifer** [comment]
[questo qui](https://wiki.pokemoncentral.it/Modulo:Pok%C3%A9moncardInfobox).
L'intento era un po' quello, ma non è proprio vero perché ci ho messo un'ora per editare il GCCNote lol

**Comment by flavio-a** [comment]
Ok, rispiegami per bene cosa devo fare @Cruifer

**Comment by Cruifer** [comment]
@flavio-a Allora, una cosa da fare è facile ed è categorizzare le pagine come ho scritto sopra. Per l'altra invece, hai notato che nell'infobox sotto la foto della carta c'è lo stadio del Pokémon? Bene, quella parte è gestita dal modulo, che mette il template giusto a seconda dei casi. Template che mancano al momento per i V e VMAX, che posso creare io, però non so come farli gestire al modulo. Se non è ancora chiaro dimmelo che non so nemmeno io come spiegarlo bene

**Comment by flavio-a** [comment]
Va, commento oggi così ho commentato esattamente ogni 30 giorni. Premessa: quel modulo è mediamente inutile perché di fatto fa il lavoro di uno `switch` (che forse è anche più efficiente in questo caso), quindi forse vorremmo toglierlo. Il che renderebbe inutile il mio aggiornarlo, ma facciamo finta di niente.
Per V e VMAX, se ho capito bene cosa devo fare mi serve sapere quali valori del parametro `evostage` devono produrre il template `EvoVMAX` e quali il template `EvoVMAXG`.
Per le categorie invece mi sono perso qualcosa perché mi risulta che quel modulo non metta nessuna categoria da nessuna parte.

**Comment by CiaobyDany** [comment]
@flavio-a Era stato Maze a dire che uno switch lì non andava bene, quindi confrontatevi per decidere se è un'altra br-like situation.

**Comment by flavio-a** [comment]
Prima o poi lo scriverà anche @davla, comunque ne abbiamo parlato e ha dato il suo benestare a togliere il modulo e sostituirlo con un switch. Da cui:
1. in un certo momento non troppo lontano (forse stasera) toglierò alcune chiamate a quel modulo dal template e le sostituirò con i corrispondenti switch
2. a quel punto Crusca potrà aggiungere la cosa dei VMAX e VMAXEVO da solo (riduzione delle interazioni => risparmio di tempo ed energie per entrambe le parti)
3. per la cosa delle categorie, sempre Crusca deve capire se è davvero un modulo (quale?) a mettere le categorie (dove?), poi eventualmente ricontattarmi

**Comment by Cruifer** [comment]
ho guardato ora per la parte delle categorie. Effettivamente c'è una sorta di switch nel modulo PokémoncardInfobox in fondo, ma in realtà quella funzione (è corretto parlare di funzione?) non è mai invocata nel template.

**Comment by davla** [comment]
Ah, ricordo quel modulo. Mi era stato chiesto di mettere mano a quel template, e siccome mi si incrociavano gli occhi ci ho fatto un modulo.

Se Flavìo vuole incrociarsi gli occhi, ben venga. Fatto sta che quel modulo non è molto utile così com'è ora. Non esegue abbastanza codice lua da far sì che valca la pena il context switch da PHP a lua

**Comment by flavio-a** [comment]
@davla Ed è qui il trucco: se non c'è il modulo non devo lavorarci io, quindi non mi si incrociano gli occhi.
