### ISSUE TITLE
Bug nei learnlist dei Pokémon Glitch

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#88]
## Descrizione
I learnlist di vari Pokémon Glitch hanno un paio di problemi:
1. I link in cima non funzionano, e questo è il problema minore
2. Alcune mosse non hanno il box del tipo, suppongo siano quelle con tipo Glitch o simili

## Pagine affette
Ne elenco solo alcune perché non le ho controllate tutte (ovviamente)
* https://wiki.pokemoncentral.it/%E3%82%A17g
* https://wiki.pokemoncentral.it/%E2%80%A6%E2%80%A6
* https://wiki.pokemoncentral.it/%E3%82%A5_(D9)
* https://wiki.pokemoncentral.it/%3F%3F%3F%3F%3F_(00)

**Comment by flavio-a** [comment]
Assegnatemi le issue pls. Comunque ho capito il bug, dovrebbe essere easy ma devo trovare tempo e voglia.
Per me: non esiste la classe `box-glitch` e simili, bisogna cambiare in `box-sconosciuto` per tutti gli alias.

**Comment by Cruifer** [comment]
@flavio-a Scusa, volevo assegnartela ma non ero sicuro tu avessi il tempo di guardarci (e mi è anche passato di mente). Se dici che è easy meglio, calcola comunque che ho messo la priorità bassa perché almeno Missingno è risparmiato da questi bug, quindi guardaci pure con calma. Poi pensavo per i link, che in effetti non hanno molto senso di esistere quindi io direi di toglierli direttamente.

**Comment by Cruifer** [comment]
segnalo anche una cosa strana [qui](https://wiki.pokemoncentral.it/Ibrido_di_quarta_generazione#Aumentando_di_livello), alcune mosse hanno solo un `[[ ]]` senza il nome

**Comment by flavio-a** [comment]
Questo è perché la mossa si chiama " " (uno spazio vuoto) e il modulo evidentemente sostituisce il "&nbsp;" in modo che non piaccia a MediaWiki per il link.

**Comment by Cruifer** [comment]
Interessante, ma è risolvibile?

**Comment by flavio-a** [comment]
Update: ho fatto un po' di cose.
- I link in cima sono da sistemare nelle pagine, ma adesso il modulo supporta 0 come ultimo parametro dell'header per far sparire per sempre il box "In altre generazioni" ([esempio](https://wiki.pokemoncentral.it/index.php?title=Ibrido_di_quarta_generazione&action=historysubmit&type=revision&diff=822560&oldid=749095))
- Il box del tipo adesso dovrebbe esserci per tutte le mosse
- Le mosse senza nome adesso si possono fare, ma bisogna esplicitamente mettere come nome della mossa "&nbsp ;" (senza spazio, ma se lo metto direttamente non si vede nella pagina qua su GitHub). Di nuovo ho già corretto io l'ibrido di quarta gen, ma se ce ne sono altri in giro sono da cercare, trovare e ~~uccidere~~ correggere
