### ISSUE TITLE
Aggiornamento PMDDX: parte tecnica

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#89]
Alcune proposte/cose da fare, aggiungete pure se vi viene in mente qualcosa:
- ~~[Template:InfoboxDungeon](https://wiki.pokemoncentral.it/Template:InfoboxDungeon): Aggiungere in fondo all'infobox la posizione dei dungeon, come abbiamo nei luoghi della serie principale, sulla base del [modello tedesco](https://www.pokewiki.de/Fantasiepass) (o [francese](https://www.pokepedia.fr/Canal_Fantaisie), ma mi convince meno). Pareri?~~
- [x] [Template:Mdloc](https://wiki.pokemoncentral.it/Template:Mdloc): Utilizzare gli sprelli del gioco appropriati, dato che li abbiamo, come fanno i francesi (vedi link sopra) e gli [spagnoli](https://www.wikidex.net/wiki/Paso_Fantas%C3%ADa).
- [x] [Template:Zone PMD](https://wiki.pokemoncentral.it/Template:Zone_PMD): Per ora ho fatto io, lo tengo perché magari lo cambiano su bulba.
- [x] [Modulo:Sigle/data](https://wiki.pokemoncentral.it/Modulo:Sigle/data): Aggiungere sigla per PMDDX.
    - [x]  [Modulo:Colore](https://wiki.pokemoncentral.it/Modulo:Colore): Aggiungere i colori per la sigla.
- [x] Controllare le tabelle degli sprite nelle pagine dei personaggi.
- [x] [Template:Squadra MD](https://wiki.pokemoncentral.it/Template:Squadra_MD): Aggiornare la grafica
- [x] [Template:Squadre Mystery Dungeon](https://wiki.pokemoncentral.it/Template:Squadre_Mystery_Dungeon): Aggiornamento grafico
- [x] Aree Amico -> Campi Base

**Comment by flavio-a** [comment]
Osservazioni generiche:
- per fare le mappe come i tedeschi c'è da copiare un loro template che mette tutti i link alle varie pagine sopra l'immagine. Non è un problema ma è da fare
- gli sprelli dei giochi appropriati non so se ce li abbiamo anche per i Pokémon nuovi, ma probabilmente sì
- il modulo colore a quanto pare non è aggiornato solo il cielo sa perché, visto che io avevo programmato l'upload sia di quello che del modulo Sigle/data e il secondo l'ha aggiornato. Comunque rimedierò

**Comment by Cruifer** [comment]
allora, in ordine:
- per fare quella cosa c'è bisogno dell'estensione ImageMap, e già qui la cosa si fa lunga. Secondo me non è veramente necessario anche perché non lo abbiamo fatto neanche per le zone della serie principale
- per gli sprelli ricordo di averti fatto caricare quelli di cielo, ma gli altri ci sono? se no, comunque non dovrebbe essere un problema upparli, posso farlo anch'io
- LOL

**Comment by flavio-a** [comment]
non sono sicurissimo che serva, forse si può fare con un widget. Potrei mettermi a guardarci, però direi che ha priorità -1000.
E per gli sprelli bisogna vedere se ce li ha Bulba

**Comment by Cruifer** [comment]
ah ok, io lo avevo escluso sulla base del fatto che serviva l'estensione. Come cosa sarebbe carina da avere, anche se non è prioritaria. Vedi tu se avrai mai tempo/voglia.
Gli sprelli non si possono prendere dagli spagnoli o dai francesi?

**Comment by StygianStar** [comment]
Più che altro, gli sprelli che ci sono su DX sono quelli di Squadra Rossa e Blu?

**Comment by flavio-a** [comment]
Ok, ho controllato e non abbiamo gli sprelli dopo Cielo, e in realtà anche di Cielo non abbiamo un po' di forme alternative (tipo Giratina Originale e Shaymin Cielo, ma non ho controllato tutto). La nomenclatura attuale è `MDP<ndex>` (che credo sia "Mystery Dungeon Potrait") e sono ragionevolmente convinto che siano presi da Cielo.

Da un rapido controllo su Bulba e Wikidex sembra che esistano solo tre versioni di ogni sprello di MD: una da Esploratori (e credo Squadra, che quindi chiamerò sprelli DS), uno che chiamano 3DS sia Bulba che Wikidex e quindi immagino venga usato in Portali e Super, e uno che chiamano Switch e che quindi penso sia di MDDX. Purtroppo non ho la cartuccia di Super sotto mano per controllare, ma sono fiducioso che sia così.
Forse vale la pena sottolineare che gli sprelli Switch sono solo una versione a definizione più alta (quasi il triplo) di quelli 3DS, mentre quelli DS sono effettivamente diversi. Per un esempio guardate le "Cara de Metagross" qua: https://www.wikidex.net/wiki/Categor%C3%ADa:Metagross

Ciò detto: possiamo caricare tutti questi sprelli, ma per usarli nel template credo dobbiamo andare con quelli 3DS. Il motivo è che il template non sa per quale gioco sta venendo usato, quindi dobbiamo usare un default, e l'unico default che ha tutti i Pokémon è il 3DS (dato che quelli DS arrivano solo alla 4 gen, e quelli Switch solo alla terza + forme alternative + Lucario). Questo a meno che non abbiate voglia di correggere tutte le pagine per specificare il gioco in ogni entry.

**Comment by Cruifer** [comment]
@flavio-a Se abbiamo le pagine categorizzate per bene dovrebbe essere relativamente fattibile metterli col bot, no? Un altro utilizzo di quegli sprelli che mi viene in mente è di metterli negli spindata, dove al momento usiamo credo gli sprelli sbagliati (o comunque gli stessi per tutti i md). Poi potrebbero tornare utili in futuro se vogliamo delle pagine con tutti gli sprelli di un certo pkmn in tutte le generazioni (come fanno i francesi). In ogni caso io li caricherei che potrebbero tornare utili in futuro

**Comment by Cruifer** [comment]
update: guardavo i francesi e loro hanno anche degli sprite dei Pokémon, mi riferisco a 
![immagine](https://user-images.githubusercontent.com/38588039/92326296-5ce8cf80-f051-11ea-85d8-4cf4a1448a63.png)
che si trova [qui](https://www.pokepedia.fr/Bulbizarre/Imagerie#Pok.C3.A9mon_Donjon_Myst.C3.A8re). Solo che non esistono (temo) per tutti i PMD, è anche vero però che nei dungeon si vedono gli sprite, quindi forse sarebbero più appropriati. Cosa vogliamo fare?

**Comment by flavio-a** [comment]
In teoria da Super in poi ci sono i modelli, e secondo me ne abbiamo già abbastanza con i modelli della serie principale (che non si trovano mai perché nessuno li rippa). Io resterei sui potrait (iniziamo ad usare questo nome che se li chiamiamo tutti sprelli non si capisce niente), che tanto sono comunque rappresentativi e sappiamo già esserci in giro.

**Comment by Cruifer** [comment]
@flavio-a Mi sembra ragionevole

**Comment by Cruifer** [comment]
update: alla luce di #93 credo che valga la pena caricare anche gli sprite oltre ai potrait, fermo restando che nelle pagine dei dungeon usiamo i secondi

**Comment by flavio-a** [comment]
Vabbe, diciamo che li caricheremo, tanto non li troveremo mai quindi dirlo o meno non cambia nulla.

**Comment by Cruifer** [comment]
Come sei pessimista. Ad ogni modo, ho iniziato a creare la [categoria per i potrait di PMDDX](https://wiki.pokemoncentral.it/Categoria:Ritratti_Pok%C3%A9mon_Mystery_Dungeon_SSDX), dato che Franky ne aveva già caricati alcuni. Io direi di mantenere la nomenclatura che hanno questi per semplificarci un po' la vita. La domanda è: come gestiamo [i cromatici](https://www.pokepedia.fr/Cat%C3%A9gorie:Miniature_Pok%C3%A9mon_chromatique_(Donjon_Myst%C3%A8re_:_%C3%89quipe_de_Secours_DX))  e le forme alternative? Sempre in termini di nomenclatura intendo. Deciso questo poi posso procedere anche io a caricarli se tu non hai voglia/tempo

**Comment by flavio-a** [comment]
@Cruifer Per la nomenclatura io toglierei gli spazi anche solo per uniformarsi agli altri sprelli degli spin-off (quindi `MDPDX***-alt.png`, dove `***` sta per l'ndex con le solite convenzioni per le forme alternative, e alt per la variante (tipo sorpresa, sorriso etc). E categorizziamoli bene che, se faranno un altro MD su Switch, ti quoto il riciclo dei potrait al 100% e così li possiamo spostare facilmente con un bot.
Le forme si gestiscono nell'ndex come al solito, e i cromatici con un sh prima o dopo l'ndex (sembra sensato prima sia per uniformarsi agli sprelli della serie principale, sia perché sh dopo si può confondere con la sigla della forma alternativa).

Conclusione: io come forma standard userei `MDP<sigla del gioco><eventuale sh per i cromatici><ndex con eventuale abbr della forma>-<descrizione della variante>.png`
- MDP sta per Mystery Dungeon potrait
- la sigla del gioco può essere TOC (Tempo, Oscurità e Cielo) per i potrati DS, Super per quelli 3DS e (per ora) DX per quelli Switch
- la descrizione della variante si tiene com'è perché tanto si usano solo nelle gallerie

Per rinominare: io comincerei spostando gli attuali `MDP***` alla nomenclatura nuova `MDPTOC***` aggiungendogli anche una categoria "potrait di esploratori", poi sposterei quelli che ha caricato Ale, e poi procederei a caricare tutto quello che troviamo da francesi e spagnoli.

**Comment by Cruifer** [comment]
Tengo i redirect o li tolgo?

**Comment by flavio-a** [comment]
@Cruifer si possono anche tenere

**Comment by Cruifer** [comment]
> la sigla del gioco può essere TOC (Tempo, Oscurità e Cielo) per i potrati DS, Super per quelli 3DS e (per ora) DX per quelli Switch

allora, ho rinominato quelli di toc e dx, caricati quelli che non avevamo di dx (inclusi i cromatici). RImangono quelli per 3ds. Ora, i francesi hanno due categoria, una per [psi](https://www.pokepedia.fr/Cat%C3%A9gorie:Miniature_Pok%C3%A9mon_(Donjon_Myst%C3%A8re_:_les_portes_de_l%27infini)) e una per [psmd](https://www.pokepedia.fr/Cat%C3%A9gorie:Miniature_Pok%C3%A9mon_(M%C3%A9ga_Donjon_Myst%C3%A8re)). Ora, il mio sospetto è che siano gli stessi file ma caricati due volte, ma non avendo giocato a nessuno dei due giochi non ne sono sicuro. Quindi, se mi confermi che sono tutti uguali e che quelli di psi sono un sottoinsieme di quelli di psmd allora li carico come abbiamo (hai) deciso, altrimenti c'è da decidere una nomenclatura anche per quelli

**Comment by flavio-a** [comment]
@Cruifer Premesso che neanch'io ho giocato a Portali (esistono persone che l'hanno fatto?) ho controllato e sono leggermente diversi, nel senso che sono le stesse immagini ma un po' più scure (Portali)/chiare (Super)
Quindi fai un po' te, per me si possono comunque caricare solo quelle di Super ma se volete averli entrambi ok. Nomenclatura quella di sopra con PSI come sigla del gioco, direi

**Comment by flavio-a** [comment]
@flavio-a nota per me: devo prendere le maledette gif nella [categoria di Esploratori](https://wiki.pokemoncentral.it/Categoria:Ritratti_Pok%C3%A9mon_Mystery_Dungeon:_Esploratori_del_Tempo,_dell%27Oscurit%C3%A0_e_del_Cielo), separare i frame e caricarli come file singoli delle varie forme

**Comment by Cruifer** [comment]
@flavio-a occhio che non ci sono solo gif ma anche apng, tipo [questa](https://wiki.pokemoncentral.it/File:MDPTOC483.png).

**Comment by Cruifer** [comment]
Update: ho messo un parametro `pot` (abbreviazione di potrait) al template `mdloc` e messo nelle pagine col bot, quindi ora nei dungeon usiamo ufficialmente i potrait anzichè gli sprite della serie principale. Visto che mi andava, li ho messi anche nel template dell'elenco di pkmn delle aree amico. L'unica cosa che non mi fa impazzire è che non si adattano bene al roundy in fondo
![image](https://user-images.githubusercontent.com/38588039/94143937-ca2d9a80-fe70-11ea-8cff-b72f2c4957ef.png)
La domanda è: non è che c'è un modo per metterci un po' di padding intorno? un po' come si mette la class `img-fluid` per intendersi.
Altra domanda: nomenclatura per gli sprite?

**Comment by flavio-a** [comment]
Bisogna anche metterli nel template spindata.

Il padding intorno si può mettere dal template no? Tipo alla cella con l'immagine, o wrappando l'immagine in un `div`.

Nomenclatura: io ho due proposte: `Sprmd<sigla gioco><ndex>.png` e `MDSpr<sigla gioco><ndex>.png`.
Il primo è allineato alla nomenclatura degli sprelli della serie principale, ma c'è l'md che li distingue. Ovviamente se poi escono Pokémon Mucca Demente e Rinoceronte Brutto ci divertiamo con la sigla mdrb, motivo per cui potremmo optare per la seconda nomenclatura, che mettendo MD prima di "spr" non si può sovrapporre alla serie principale. A naso la seconda sembra un'idea migliore, in effetti (anche se dubito avremo mai il nostro Pokémon Mucca Demente).

**Comment by Cruifer** [comment]
nel template spindata non ci sono già?
Ottima idea per il div, non ci avevo pensato, provo subito.
Per gli sprelli tutto bellissimo ma mi sono scordato di dire che ci sono due sprite, uno per [rb](https://www.pokepedia.fr/Cat%C3%A9gorie:Sprite_Pok%C3%A9mon_(Donjon_Myst%C3%A8re_:_%C3%89quipe_de_Secours_Rouge_et_Bleue)) e uno per [TO(C)](https://www.pokepedia.fr/Cat%C3%A9gorie:Sprite_Pok%C3%A9mon_(Donjon_Myst%C3%A8re_:_Explorateurs_de_l%27Ombre_et_du_Temps)).

**Comment by flavio-a** [comment]
@Cruifer Spindata: sì ma c'è il link con il redirect, bisogna correggerli

Sprelli: eh appunto a quello serve la sigla del gioco: rb o toc a seconda del gioco di provenienza

**Comment by Cruifer** [comment]
per lo spindata correggo subito.
Probabilmente ho letto troppo di fretta e non mi ero accorto della sigla. Scelgo la seconda opzione btw

**Comment by flavio-a** [comment]
Quindi possiamo segnare la questione potrait/sprelli come conclusa?
Allora io passerei a discutere l'ultimo punto rimasto della issue, e poi ad aprire un altro, quello delle Aree Amico/Campi Base (che ne abbiamo parlato un po' su Tg ma poi si è perso tutto).

**Posizione del dungeon in fondo all'infobox**: io sono per il nì, nel senso che è carina l'idea (ma non la trovo fondamentale visto che a differenza dei giochi della serie principale in cui la posizione geografica conta qualcosa qui è solo di bellezza dato che selezioni il dungeon da un elenco) ma ci sono un po' di ostacoli nella pratica:
- c'è lo sbatti pazzesco di caricare tutte le immagini della mappa con colorato il dungeon di turno, perché vanno rinominate traducendo il nome del dungeon dal tedesco (quindi no bot).
- per Squadra ed Esploratori tutto bello, ma [per quanto riguarda Super](https://www.pokewiki.de/Glitzerberg) la mappa è minuscola e non ha il dungeon specifico colorato, quindi ha senso davvero metterla? Non ho guardato Portali, ma tanto a nessuno importa di Portali.
Verdetto: io sarei per il no, ma se qualcuno si offre per sistemare questi due problemi non mi opporrò

**Aree Amico**: allora, ho ripreso in mano il gioco e posso confermare che i Campi Base _sono_ le Aree Amico, quindi bisogna spostare la pagina, cambiare i nomi, etc. La cosa che mi aveva un po' confuso all'inizio è che certi Campi Base hanno cambiato nome tra RB e DX, quindi quelli saranno da spostare (ovviamente lasciando il vecchio nome nelle pagine di RB, che però credo saranno poche visto che condividono quasi tutto con DX).

**Comment by Cruifer** [comment]
Se hai sistemato la questione delle gif dei portrait di TOC allora sì, è conclusa.

Per la storia dei Dungeon io la trovavo una cosa carina da avere, ma in effetti è troppo lavoro non giustificato da un utilità pratica. Facciamo che magari per il momento si lascia perdere.

Per le aree amico, io ho già caricato un po’ di tempo fa gli artwork delle aa in dx (scusa se le chiamo così anche quelle di dx ma ormai è abitudine), quindi c’è da mettere quello nelle infobox e un box con la mappa in rb come bulba (o comunque qualcosa di simile, mi dispiacerebbe non mettere da nessuna parte come apparivano prima). Hai voglia di lavorarci tu a questa roba?

**Comment by Cruifer** [comment]
per i portrait: ho visto solo ora che sono rimasti alcuni di TOC/Super caricati da Ale che non ho spostato e categorizzato. Alcuni hanno anche la descrizione della variante con due parole (e quindi uno spazio nel mezzo)

**Comment by flavio-a** [comment]
@Cruifer Ho caricato le versioni "statiche" delle gif, però non ho cancellato i vecchi file perché non mi sembra ci sia la necessità, ma se pensate sia meglio mi sembra ragionevole.

Per le aree amico mi posso prendere io l'impegno, però con un po' di calma.

La cosa dei potrait caricati da Ale non l'ho capita, stai chiedendo consiglio o è un memo per te?

**Comment by Cruifer** [comment]
Boh io forse le cancellerei per evitare confusione ma in fondo chissenefrega.

Tranquillo, nessuna fretta per le aa (anche se gli artwork di DX sono veramente belli da avere in pagina)

E sì, quello è un promemoria per me. Solo che non so come gestire il fatto dello spazio nella descrizione, perché mi sembra che tu avessi detto di non volere spazi nei nomi dei file, quindi sto anche chiedendo consiglio

**Comment by flavio-a** [comment]
@Cruifer Ok dai, allora li cancello.

Per gli spazi nei nomi delle immagini: potrei aver detto di evitarli, ma (1) non è un vincolo forte, è più una preferenza e (2) non conta davvero se le immagini non vanno inserite automaticamente in un template/modulo (tipo le immagini delle aa che vengono scelte dal template in automatico usando il nome). Quello che invece va assolutamente evitato nel nome delle immagini sono i caratteri non alfanumerici, spazi o trattini/underscore (probabilmente molti funzionano ma meglio non rischiare)

**Comment by flavio-a** [comment]
Reminder per me: devo spostare Aree Amico -> campi base (non so le maiuscole) e cambiare i nomi di alcune Aree Amico

**Comment by flavio-a** [comment]
Stavo iniziando a guardare un po' per aggiornare i Campi Base/Aree Amico, e mi è venuto un dubbio: se nell'infobox mettiamo l'artwork di DX, dove mettiamo l'immagine di MDRB? Bulba fa una sezione "Appearance" in cui mette solo un box con quella, l'alternativa sarebbe metterla come immagine tipo sotto l'infobox. Oppure direttamente nell'infobox mettiamo due immagini. Oppure boh, proponete e commentate.

**Comment by Cruifer** [comment]
Boh. Posto che a me non convince tantissimo, perché non provare le tabs? Nell'infobox intendo

**Comment by lucas992x** [comment]
Mi intrometto perché leggo _tabs_ e _infobox_ nello stesso commento: dato che `Infobox/image` gestisce una sola immagine e non vorrei stravolgerlo, è il caso di creare un template del tipo `Infobox/images` in cui usare i tab? È una cosa che poi si potrebbe usare anche in altri contesti, per esempio il `PokémonInfo`.

**Comment by flavio-a** [comment]
Allora, se vuoi crearlo è plausibile che verrà usato prima o poi, ma mi sembra più una cosa da discutere in #83, anche considerato che né a me né a Crusca convince troppo l'idea.
Io personalmente preferirei due immagini una sotto l'altra se le vogliamo entrambe nell'infobox (tanto non sono così grandi), oppure adottare un'altra soluzione.

**Comment by flavio-a** [comment]
@Cruifer https://wiki.pokemoncentral.it/Utente:Ff300/sandbox come ti sembra così l'infobox? Ho provato a mettere entrambe le immagini, e vorrei anche portare la tua attenzione sulla parte bassa con metodo per ottenere e prezzi separati (ho copiato l'idea dei tedeschi).
Personalmente la doppia immagine mi convince meno di quanto pensassi, e unirei i prezzi in un unico box, ma mi piace molto l'idea di separare metodo per ottenere e prezzo (ovviamente il prezzo non compare se il Campo Base si ottiene in altri modi).

**Comment by Cruifer** [comment]
@flavio-a Sai che a me non dispiace affatto avere le due immagini così? Io lo approvo

Btw, i prezzi magari uniamoli mettendo sup / sup. per il resto ok

**Comment by flavio-a** [comment]
Ok, allora io vado così. Inizio ad aggiornare proprio le pagine.

**Comment by flavio-a** [comment]
A quanto pare esistono Campi Base con Pokémon diversi da quelli che avevano in Squadra Rossa: 
https://bulbapedia.bulbagarden.net/wiki/Evolution_Forest
Secondo me se ne aggiungono e basta, ma bisogna capire come gestire questa cosa. Un'alternativa che mi è venuta in mente alla soluzione di Bulba è di mettere un bel separatore con scritto "Solo in MDDX" e poi mettere le entry normali (senza sup) sotto. Resta però il problema che non abbiamo i potrait di Sylveon da MDRB (per ovvi motivi). Se però usiamo la soluzione con il separatore secondo me ci può stare usare potrait di MDDX per tutte le entry dopo, visto che sono Pokémon solo di MDDX.
Ho fatto una prova di questa cosa in [sandbox](https://wiki.pokemoncentral.it/Utente:Ff300/sandbox), e secondo me ci sta

**Comment by Cruifer** [comment]
@flavio-a Approvo, va benissimo così

**Comment by Cruifer** [comment]
@flavio-a Leggo dal LMOPCW che l’aggiornamento a campi base è terminato, si può chiudere?

**Comment by flavio-a** [comment]
Sì è vero, ho finito. Chiudo
