### ISSUE TITLE
Manca il margine destro nei thumb delle immagini

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#9]
## Descrizione
Come da titolo, non c'è il margine sulla destra nelle miniature delle immagini, mentre è presente nelle altre 3 parti. Il problema non c'è nelle gallery.

## Screenshot
![schermata 2018-04-24 alle 15 04 21](https://user-images.githubusercontent.com/38588039/39188990-6bb6d758-47d1-11e8-9fb3-5780cb406332.png)

## Pagine affette
Tutte quelle in cui è presente almeno un'immagine. Lo screenshot viene da [qui](https://wiki.pokemoncentral.it/Buffet_Lotta).

## Risoluzione del problema
Può darsi che il problema sia nel css, ma non sono sicuro.

**Comment by davla** [comment]
È un `box-sizing: border-box` che ho messo everywhere. L'ho fatto secoli fa, e causa solo problemi marginali come questo, quindi siamo a cavallo. Sistemo appena possibile.
