### ISSUE TITLE
Migliorie da implementare su github

### ISSUE THREAD

**Issue by Cruifer** [pokemoncentral/wiki-project#92]
## Descrizione
Ho visto che ci sarebbero un paio di cose da fare. Non molto prioritarie, ma sarebbe carino averle. 

- Aggiungere il logo giallo anziché quello vecchio grigio. Non va quello blu perché non c'è solo roba per la wiki (anche se è la maggior parte)
- Aggiungere il link a twitter accanto al link al wiki e alla mail. Ho visto prima che si può fare, magari può essere utile per aumentare il ranking del social su google. NB: non serve il link dell'url ma basta aggiungere il nome del profilo, ovvero `pokemoncentral`.

Domanda: a chi assegno questa issue? Chi è che può modificare i settings dell'organization?
PS: modificate pure le label se non vanno bene, non sapevo cosa metterci

## Pagine affette
* https://github.com/pokemoncentral

## Risoluzione del problema

- [x] Logo giallo
- [x] Link a twitter

**Comment by flavio-a** [comment]
@Cruifer Gika e forse Maze
